### ISSUE TITLE
[bug] json output is off by one

### ISSUE THREAD

**Issue by cameronbrill** [ast-grep/ast-grep#1002]
# ⏯ Playground Link

[Playground link with relevant code](https://ast-grep.github.io/playground.html#eyJtb2RlIjoiQ29uZmlnIiwibGFuZyI6InB5dGhvbiIsInF1ZXJ5IjoicnVsZTpcbiAga2luZDoga2V5d29yZF9hcmd1bWVudFxuICByZWdleDogKD9pKSg/Olxce2lkXFx9fFxcey4rX2lkXFx9fFxcey4rXFwuaWRcXH0pXG4gIGluc2lkZTpcbiAgICBwYXR0ZXJuOiBEYXRhZG9nSGVscGVyLmluY3JlbWVudF9tZXRyaWMoJCQkKVxuICAgIHN0b3BCeTogZW5kIiwicmV3cml0ZSI6ImxvZ2dlci5sb2coJE1BVENIKSIsImNvbmZpZyI6InJ1bGU6XG4gIGtpbmQ6IGtleXdvcmRfYXJndW1lbnRcbiAgcmVnZXg6ICg/aSkoPzpcXHtpZFxcfXxcXHsuK19pZFxcfXxcXHsuK1xcLmlkXFx9KVxuICBpbnNpZGU6XG4gICAgcGF0dGVybjogT2JqZWN0TmFtZS5pbmNyZW1lbnRfY291bnRlcigkJCQpXG4gICAgc3RvcEJ5OiBlbmQiLCJzb3VyY2UiOiJPYmplY3ROYW1lLmluY3JlbWVudF9jb3VudGVyKFxuICBmb289XCJiYXJcIixcbiAgdGFncz1bXG4gICAgZlwidGFnX25hbWU6J3t0YWdfdmFsdWUuYW5faWR9J1wiXG4gIF0sXG4pXG5cbk9iamVjdE5hbWUuaW5jcmVtZW50X2NvdW50ZXIoXG4gIGZvbz1cImJhclwiLFxuICB0YWdzPVtcbiAgICBmXCJ0YWdfbmFtZTone3RhZ192YWx1ZX0nXCJcbiAgXSxcbilcblxuT2JqZWN0TmFtZS5pbmNyZW1lbnRfY291bnRlcihcbiAgZm9vPVwiYmFyXCIsXG4pIn0=)

# 💻 Code

Code:

```
ObjectName.increment_counter(
  foo="bar",
  tags=[
    f"tag_name:'{tag_value.an_id}'"
  ],
)
```

Pattern:

```yml
rule:
  kind: keyword_argument
  regex: (?i)(?:\{id\}|\{.+_id\}|\{.+\.id\})
  inside:
    pattern: ObjectName.increment_counter($$$)
    stopBy: end
```

# 🙁 Actual behavior

The start and end lines for all json output are off by one. I am using a VS Code task with a problem matcher to display squiggly lines when ast-grep finds an error, but the squiggly lines currently show up on the wrong line because of this.

- ✅ `ast-grep scan` shows the correct start line and column (3:3)
- ✅ `ast-grep scan --format github` shows the correct start and end lines (line=3,endLine=5)
- ❌ `ast-grep scan --json=stream` lines off by one (`{start: {line: 2}, end: {line:4}}`)
- ❌ `ast-grep scan --json=pretty` lines off by one (`{start: {line: 2}, end: {line:4}}`)
- ❌ `ast-grep scan --json=compact` lines off by one (`{start: {line: 2}, end: {line:4}}`)

# 🙂 Expected behavior

I expect the start and end lines in the json output to be the same as those from other output formats.
- ✅ `ast-grep scan --json=stream` should show (`{start: {line: 3}, end: {line:5}}`)
- ✅ `ast-grep scan --json=pretty` should show (`{start: {line: 3}, end: {line:5}}`)
- ✅ `ast-grep scan --json=compact` should show (`{start: {line: 3}, end: {line:5}}`)

**Comment by HerringtonDarkholme** [comment]
JSON's output line and column is zero-based because most of programming language is zero based.

**Comment by HerringtonDarkholme** [comment]
Also, if you need to display errors. https://marketplace.visualstudio.com/items?itemName=ast-grep.ast-grep-vscode the official LSP plugin is recommended.

**Comment by cameronbrill** [comment]
okay that's fair, we were trying this because the vs code extension doesn't work on my teams codebase right now. but, that's unrelated to this repo, so I'll just open an issue on the vs code extension repo
