### ISSUE TITLE
[bug] php(alpha) can not match pattern

### ISSUE THREAD

**Issue by heheda123123** [ast-grep/ast-grep#1040]
# ⏯ Playground Link

[Playground link with relevant code](https://ast-grep.github.io/playground.html#eyJtb2RlIjoiUGF0Y2giLCJsYW5nIjoicGhwIiwicXVlcnkiOiJwcmludCgkQUFBKTsiLCJyZXdyaXRlIjoiIiwiY29uZmlnIjoiIyBZQU1MIFJ1bGUgaXMgbW9yZSBwb3dlcmZ1bCFcbiMgaHR0cHM6Ly9hc3QtZ3JlcC5naXRodWIuaW8vZ3VpZGUvcnVsZS1jb25maWcuaHRtbCNydWxlXG5ydWxlOlxuICBhbnk6XG4gICAgLSBwYXR0ZXJuOiBjb25zb2xlLmxvZygkQSlcbiAgICAtIHBhdHRlcm46IGNvbnNvbGUuZGVidWcoJEEpXG5maXg6XG4gIGxvZ2dlci5sb2coJEEpIiwic291cmNlIjoiPD9waHBcbiRhID0gMTIzO1xuZWNobyAkYTtcbiRiID0gJF9HRVRbJ3h4eCddO1xuZWNobyAkYjtcblxuZWNobyAkX0dFVFsnampqJ107XG5lY2hvKDEyMyk7XG5wcmludCgkYSk7In0=)

# 💻 Code

Code:

```
<?php
$a = 123;
echo $a;
$b = $_GET['xxx'];
echo $b;

echo $_GET['jjj'];
echo(123);
print($a);
```

Pattern:

```yml
print($AAA);
```
I also tried the echo, also failed match.

# 🙁 Actual behavior

it shows "No match found."

# 🙂 Expected behavior

highlight the call

**Comment by HerringtonDarkholme** [comment]
This is expected because `print($AAA);` is parsed as html.
You need `<?php` prefix and pattern object to pick up `print` https://ast-grep.github.io/guide/rule-config/atomic-rule.html#pattern

**Comment by heheda123123** [comment]
thank you ! it's worked
![image](https://github.com/ast-grep/ast-grep/assets/97490782/e8cab86e-0dd3-4d4d-9d23-4349d7d43dd2)
