### ISSUE TITLE
[feature] search in git changed files

### ISSUE THREAD

**Issue by tjx666** [ast-grep/ast-grep#1055]
VSCode builtin search not plan to ship this feature, but I think it's useful sometimes.

ref: https://github.com/microsoft/vscode/issues/154211

**Comment by HerringtonDarkholme** [comment]
nope, ast-grep search will follow VSCode's decision.

**Comment by HerringtonDarkholme** [comment]
Also, you can use the command

```bash
git diff --name-only | xargs -I % sg -p 'pattern' %
```
