### ISSUE TITLE
[feature] support glob path match in CLI.

### ISSUE THREAD

**Issue by alexzhang1030** [ast-grep/ast-grep#1062]
# ⭐ Suggestion

Sometimes, we want to match some paths by a `glob` pattern. That will be really great if the `ast-grep` CLI supports a glob pattern like the [`configuration file globbing`](https://ast-grep.github.io/reference/yaml.html#globbing).

The VSCode extension which uses `ast-grep` CLI as its backend, will also support glob if this feature is addressed.

# 💻 Use Cases

**Comment by reidbarber** [comment]
Is this not already supported? https://github.com/ast-grep/ast-grep/discussions/715#discussioncomment-7902065

**Comment by MagicDuck** [comment]
@reidbarber problem is that is that shell globs are not smart enough to avoid .gitignored stuff like `node_modules` which is a significant perf impact

**Comment by MagicDuck** [comment]
I guess something like `--glob` from `ripgrep` would be ideal...
I believe that ripgrep is also written in rust, so maybe it uses a common crate for the glob stuff that could be reused here?

**Comment by MagicDuck** [comment]
yep, it uses this one:
https://crates.io/crates/globset

**Comment by HerringtonDarkholme** [comment]
> I guess something like --glob from ripgrep would be ideal...

Agree. ripgrep's API design is a pretty good fit for ast-grep as well.

**Comment by MagicDuck** [comment]
Thank you!
