### ISSUE TITLE
[bug] Discrepencies in results between JavaScript and TypeScript

### ISSUE THREAD

**Issue by Pamplemousse** [ast-grep/ast-grep#1087]
Trying to match and rewrite lambda functions in TypeScript, I get a simple pattern that doesn't work, but matches correctly in JavaScript.

# ⏯ Playground Link

Issue can't be reproduced in a single playground, as it is about inconsistencies between pattern matching in JavaScript and TypeScript.

# 💻 Code

```typescript
# yolo.ts
const foo = (x) => bar(x);
```

# 🙁 Actual behavior

```bash
$ ast-grep run -p '($P) => $F($P)' yolo.ts
# nothing

$ ast-grep run --lang typescript -p '($P) => $F($P)' yolo.ts
# nothing

$ ast-grep run --lang javascript -p '($P) => $F($P)' yolo.ts
yolo.ts
1│const foo = (x) => bar(x);
```

# 🙂 Expected behavior

I was expecting the first pattern to match the code in TypeScript, like it does when the language is explicitly set to JavaScript.

**Comment by HerringtonDarkholme** [comment]
I can reproduce it on playground

https://ast-grep.github.io/playground.html#eyJtb2RlIjoiUGF0Y2giLCJsYW5nIjoidHlwZXNjcmlwdCIsInF1ZXJ5IjoiKCRQKSA9PiAkRigkUCkiLCJyZXdyaXRlIjoibG9nZ2VyLmxvZygkTUFUQ0gpIiwiY29uZmlnIjoicnVsZTpcbiAgYW55OlxuICAgIC0gcGF0dGVybjogfFxuICAgICAgICBkZWZtb2R1bGUgJE0gZG8gXG4gICAgICAgICAgSU8ucHV0cygkQSlcbiAgICAgICAgZW5kXG50cmFuc2Zvcm06XG4gIE5FV19NT0Q6XG4gICAgcmVwbGFjZTpcbiAgICAgIGJ5OiBDb25jcmV0ZUZhY3RvcnlJbXBsXG4gICAgICByZXBsYWNlOiAkXG4gICAgICBzb3VyY2U6ICRNXG5maXg6IHxcbiAgZGVmbW9kdWxlICRORVdfTU9EIGRvIFxuICAgIGRlZiBtc2coJEEpIGRvIFxuICAgICAgSU8ucHV0cyg6c3Rkb3V0LCRBKVxuICAgIGVuZCBcbiAgZW5kIiwic291cmNlIjoiY29uc3QgZm9vID0gKHgpID0+IGJhcih4KTsifQ==

**Comment by HerringtonDarkholme** [comment]
The problem is first `$P` captures `requried_parameter` instead of `identifier`. But the second `$P` expects `identifier`

![image](https://github.com/ast-grep/ast-grep/assets/2883231/64672079-1d56-4a1c-9fa6-a5f9eed41f6b)

**Comment by HerringtonDarkholme** [comment]
https://ast-grep.github.io/playground.html#eyJtb2RlIjoiQ29uZmlnIiwibGFuZyI6InR5cGVzY3JpcHQiLCJxdWVyeSI6IiIsInJld3JpdGUiOiJsb2dnZXIubG9nKCRNQVRDSCkiLCJjb25maWciOiJydWxlOlxuICBwYXR0ZXJuOiAoJEEpID0+ICRCKCRDKVxuY29uc3RyYWludHM6XG4gIEE6XG4gICAgaGFzOlxuICAgICAgcGF0dGVybjogJEMiLCJzb3VyY2UiOiJjb25zdCBmb28gPSAoeCkgPT4gYmFyKHgpOyJ9

You can use this yaml rule as work around

<img width="694" alt="image" src="https://github.com/ast-grep/ast-grep/assets/2883231/4211b7b6-9df0-475f-b61c-a3d76017040d">
