### ISSUE TITLE
Change output colors?

### ISSUE THREAD

**Issue by schneiderfelipe** [ast-grep/ast-grep#111]
How can I change the output colors `sg` gives me? The current ones seem pretty unusable for me,

![Screenshot from 2022-12-11 12-12-12](https://user-images.githubusercontent.com/37125/206911763-27face3e-34aa-4feb-8095-c81398bad19f.png)

I think the issue here is that I'm using a light font color, which doesn't contrast well with the pink/light green highlights. Maybe related to #2?

**Comment by HerringtonDarkholme** [comment]
Thanks for the input! I will change the default output style!
