### ISSUE TITLE
[bug] cargo install --path ./crates/cli failed

### ISSUE THREAD

**Issue by tizee** [ast-grep/ast-grep#1118]
# 🙁 Actual behavior

```
error[E0277]: the trait bound `TSLanguage: From<tree_sitter::Language>` is not satisfied
  --> crates/language/src/parsers.rs:36:34
   |
36 |     tree_sitter_html::language().into()
   |                                  ^^^^ the trait `From<tree_sitter::Language>` is not implemented for `TSLanguage`, which is required by `tree_sitter::Language: Into<_>`
   |
   = help: the trait `From<tree_sitter::Language>` is implemented for `TSLanguage`
   = help: for that trait implementation, expected `tree_sitter::Language`, found `tree_sitter::Language`
   = note: required for `tree_sitter::Language` to implement `Into<TSLanguage>`
```

# 🙂 Expected behavior

Install `ast-grep` by building it from source using `cargo install --path ./crates/cli`

# My workaround

My workaround is simple. Build `ast-grep` with `cargo build --release -p ast-grep` then copy the binary executable to ~/.cargo/bin manually.

**Comment by HerringtonDarkholme** [comment]
This is caused by incompatible tree-sitter version release.

You can try this 

```bash
cargo install ast-grep --frozen
```

**Comment by HerringtonDarkholme** [comment]
nope, this is tree-sitter's issue. Tree-sitter's version does not follow semver. 

Instead, use `cargo install --locked` is recommended.

**Comment by jubalh** [comment]
It won't be so easy for me. Our package pulls down all dependencies in a vendor tarball because the build system doesn't support having an internet connection. I'll try to research if I can somehow tell the service to use the locked versions.
