### ISSUE TITLE
JSON output? (Or other structured non-ANSI-colored format)

### ISSUE THREAD

**Issue by vergenzt** [ast-grep/ast-grep#112]
I'm trying to simply _search_ for all expressions that match a pattern and summarize them in a downstream piped command. It'd be nice to not have to parse ANSI codes to do that. 😕 Great tool otherwise!

**Comment by HerringtonDarkholme** [comment]
Sure! I'm always planning to support json out put! Probably I will add an Vim compatible output later.

**Comment by HerringtonDarkholme** [comment]
Fixed in 0c031c19e2654c88ed2506ce151423fb013768e7!

**Comment by HerringtonDarkholme** [comment]
Example showcase!

![image](https://user-images.githubusercontent.com/2883231/208296231-761a9d8c-775f-4568-9a25-bac8ca6a087f.png)
