### ISSUE TITLE
Any plans to support win32-ia32 and win-arm64? 

### ISSUE THREAD

**Issue by 10Derozan** [ast-grep/ast-grep#113]
# What happened?
![image](https://user-images.githubusercontent.com/50694858/207801560-a20e5d3d-c06f-4519-a233-b13242874703.png)

Any tips would be appreciated, thanks!

**Comment by HerringtonDarkholme** [comment]
Hi, are you using napi or cli? You are currently using the napi package. Would you like to explain your use case?

Or, you can install the cli by 
```
npm install --global @ast-grep/cli
```

**Comment by 10Derozan** [comment]
Yes, I am using napi, i am a library author, i want to parse js code to match 'require()',  i need to invoke js api, so cli does not apply to my scenario.  [here](https://github.com/modern-js-dev/libuild/blob/main/packages/libuild/src/plugins/redirect.ts#L151) is my use case.  Now, my library is not working  in win32

**Comment by HerringtonDarkholme** [comment]
Supported in 0.1.13! https://www.npmjs.com/package/@ast-grep/napi?activeTab=dependencies
