### ISSUE TITLE
[bug] `ast-grep` prebuilt binaries are missing from release

### ISSUE THREAD

**Issue by sapphi-red** [ast-grep/ast-grep#1130]
# ⏯ Playground Link
N/A

# 💻 Code
N/A

# 🙁 Actual behavior

Only `sg` binaries are attached to releases.
https://github.com/ast-grep/ast-grep/releases/tag/0.22.0

# 🙂 Expected behavior

`ast-grep` binaries and `sg` binaries are both attached to releases (ideally bundled in a single zip file to reduce network bandwidth).

`sg` and `ast-grep` binaries behaves almost the same except `sg --help` / `ast-grep --help`. The usage output differs: `Usage: sg <COMMAND>`/`Usage: ast-grep <COMMAND>`. I might be missing other parts. 
Also [the VSCode extension searches for the `ast-grep` binary](https://github.com/ast-grep/ast-grep-vscode/blob/3c76748414e94098d4675a1171d2a12663307694/src/extension/common.ts#L9-L32), not the `sg` binary, so I'll have to make sure I rename/copy the binary to `ast-grep` or set the `astGrep.serverPath` settings in vscode.

Alternatively, distributing only the `ast-grep` binary and let users set an alias would work too.

It's not a big deal but would be nice to make it work OOTB.

**Comment by HerringtonDarkholme** [comment]
Fix this is too hard. installing from npm/cargo is recommended.

**Comment by sapphi-red** [comment]
Thanks for taking a look!
