### ISSUE TITLE
[feature] Ability to know if variable is declared

### ISSUE THREAD

**Issue by coderaiser** [ast-grep/ast-grep#1131]
# ⭐ Suggestion

I didn't find information about getting declared variables in documentation. It is possible with Babel, but I wander if it is possible with Ast-Grepz

# 💻 Use Cases

I want to write transformation rule, according to [React 19 Upgrade Guide](https://react.dev/blog/2024/04/25/react-19-upgrade-guide#removed-reactdom-render):

```js
// Before
import {render} from 'react-dom';
render(<App />, document.getElementById('root'));

// After
import {createRoot} from 'react-dom/client';
const root = createRoot(document.getElementById('root'));
root.render(<App />);
```

But the variable named `root` can already exist. Is it possible to know it variable named `root` isn't exist? I want to skip transformation for this case.

**Comment by HerringtonDarkholme** [comment]
You can use relational rule https://ast-grep.github.io/guide/rule-config/relational-rule.html

`follows` and `precedes` can be used to find if a variable declaration exists.

That said, it is impossible to detect arbitrary variable declarations using YAML. Say, your use case here is finding a fresh identifier that is not defined in the scope. But you can detect if the specific identifier `root` is defined.

**Comment by coderaiser** [comment]
It should be something like this?

```yml
pattern: render($JSX, $ELEMENT);
follows:
  pattern: $BINDING;
```

Could you please tell me how should I determine if variable is declared? Should I write all ways of declaration: var/const/let/import/function argument, or there is a keyword for this?

**Comment by HerringtonDarkholme** [comment]
@coderaiser  play around the playground is recommended.  https://ast-grep.github.io/playground.html

You can also ask questions on https://stackoverflow.com/questions/tagged/ast-grep
