### ISSUE TITLE
[bug] ast-grep at v. 0.21.x doesn't work on MacOS Intel machines

### ISSUE THREAD

**Issue by laurenmbeatty** [ast-grep/ast-grep#1140]
The version `2.1.0` of `@ast-grep/napi` doesn't work on MacOS Intel machines.

When using the latest version of `vite-plugin-lib-inject-css`, my build fails. The latest version of this package included `@ast-grep/napi` as a dependency (at version `2.1.0`). 

The error I was getting:

![Screen Shot 2024-05-12 at 7 22 03 AM](https://github.com/ast-grep/ast-grep/assets/10378331/0a521970-efde-43b7-a0e5-51aaebffc6bb)
 
`Error: Cannot find module @ast-grep/napi-darwin-x64`.

When I looked at my `pnpm-lock.yaml` file I could see that there were options for different OS:

![Screen Shot 2024-05-12 at 9 04 19 AM](https://github.com/ast-grep/ast-grep/assets/10378331/dc5e6394-5cc6-42f5-ad7d-0c320d9730d1)

I'm on MacOS, but not on an arm machine.

When I explicitly installed `@ast-grep/napi-darwin-x64` as a devDependency, then my build succeeds. 

It looks like `@ast-grep/napi-darwin-x64` is only available up to version `0.20.5` but not beyond.

![Screen Shot 2024-05-12 at 9 37 14 AM](https://github.com/ast-grep/ast-grep/assets/10378331/11f121ab-24a3-4c2c-a4fc-ad34832e37cd)

Related [issue](https://github.com/emosheeep/vite-plugin-lib-inject-css/issues/23).

[Minimal reproduction.](https://github.com/laurenmbeatty/inject-lib-css-repro).

Note, you'll need to be on a MacOS Intel machine.

**Comment by HerringtonDarkholme** [comment]
In napi 0.20.x publish workflow:

https://github.com/ast-grep/ast-grep/actions/runs/8592707349/job/23543271091

<img width="994" alt="image" src="https://github.com/ast-grep/ast-grep/assets/2883231/e0ddabf6-b5d5-494f-a859-87fd2b184ae4">


In napi 0.22.x publish workflow:
https://github.com/ast-grep/ast-grep/actions/runs/9007554793/job/24747805358#logs

<img width="988" alt="image" src="https://github.com/ast-grep/ast-grep/assets/2883231/73ee40cf-c63e-43b5-a24a-4a42ed9e08c8">


I guess the problem may be napi workflow's issue

**Comment by HerringtonDarkholme** [comment]
Confirm it is because GitHub runner now uses Apple Chip instead of Intel's. 

Reference https://github.com/napi-rs/napi-rs/issues/2076

**Comment by laurenmbeatty** [comment]
It looks like the fix will be [available in 3.X](https://github.com/napi-rs/napi-rs/releases/tag/%40napi-rs%2Fcli%403.0.0-alpha.55)

**Comment by HerringtonDarkholme** [comment]
Released in https://www.npmjs.com/package/@ast-grep/napi-darwin-x64

**Comment by laurenmbeatty** [comment]
Thanks @HerringtonDarkholme !
