### ISSUE TITLE
Is there any way to configure custom language support when using the Python API?

### ISSUE THREAD

**Issue by vergenzt** [ast-grep/ast-grep#1143]
I'm not seeing anywhere in the API where an `sgconfig.yaml` can be defined. 😕 I've been exploring both the docs and the source code and am not seeing how to do it. Any suggestions?

docs I've looked at:
- https://ast-grep.github.io/guide/api-usage/py-api.html
- https://ast-grep.github.io/reference/api.html
- https://github.com/ast-grep/ast-grep/blob/0.22.3/crates/pyo3/src/py_node.rs

**Comment by HerringtonDarkholme** [comment]
It is not supported yet. Custom language will be supported after fix API.

**Comment by HerringtonDarkholme** [comment]
Added as an experimental API.

Example usage:

https://github.com/ast-grep/ast-grep/blob/main/crates/pyo3/tests/test_register_lang.py
