### ISSUE TITLE
[feature] Command line flag to output rewrites only

### ISSUE THREAD

**Issue by collosi** [ast-grep/ast-grep#1145]
# ⭐ Suggestion

Currently, the only output style supported for rewrites is a "diff-like" format (correct me if I'm wrong).   I would like a flag to show the rewrites only, with no context or line number information.

# 💻 Use Cases

I wanted to use the tool to summarize a code base, by selecting certain elements and showing them to the user.  This would be easier if there were a flag to "show rewrites only".

Currently, I'm using something like this:
`sg run -l rust -p 'fn $NAME($$$ARGS) -> $$$RET { $$$ }' -r 'fn $NAME($$$ARGS) -> $$$RET;' src/parser.rs |grep '^   ' | cut -d'+' -f2-`
To show all the function signatures in a rust file (I know something like cargo doc can do this too, it's just an example).

**Comment by HerringtonDarkholme** [comment]
You can already do that via [`--json`  flag](https://ast-grep.github.io/reference/cli/run.html#json-style)

Also the doc https://ast-grep.github.io/guide/tooling-overview.html#json-mode

**Comment by HerringtonDarkholme** [comment]
No. grep is not rewriting your code like ast-grep.
