### ISSUE TITLE
[RFC] Using fix in JS/Python API

### ISSUE THREAD

**Issue by HerringtonDarkholme** [ast-grep/ast-grep#1172]
# Context
Previously napi/pyo3 does not support fix. We proposed a new API to support easier rewriting. 

# Design
We cannot provide a mutable interface unfortunately due to tree-sitter's limitation. To apply fix, you need
1. find relevant AST node using the API
2. call `edit = node.replace(text)` to get the `Edit` object
3. call `node.commitEdits([edit])`  to apply edit, the return value is a string.

# Example test code:
* napi: https://github.com/ast-grep/ast-grep/blob/c0e9a65dc197bb4abcae6fdebc65c8b128b0467e/crates/napi/__test__/index.spec.ts#L92-L113
* pyo3: https://github.com/ast-grep/ast-grep/blob/c0e9a65dc197bb4abcae6fdebc65c8b128b0467e/crates/pyo3/tests/test_fix.py#L16-L33

**Comment by HcySunYang** [comment]
Teacher 海 please, I am going to use this tool for Edge WebUI-related things, really need this feature, you are the best I believe.

**Comment by HerringtonDarkholme** [comment]
Hi @HcySunYang, glad to hear Edge is using ast-grep. Let me know if you have questions or need help when using ast-grep. Cheers 🥂

**Comment by HerringtonDarkholme** [comment]
See https://ast-grep.github.io/guide/api-usage/js-api.html

**Comment by jondlm** [comment]
Wow, this is an awesome API. Thank you for making this!
