### ISSUE TITLE
[bug] The `import_statement` syntax does not match the internal string node

### ISSUE THREAD

**Issue by zxhd863943427** [ast-grep/ast-grep#1173]
In the `import_statement` statement, you cannot use `import $B from $A` to match a text node, but only `import $B from "$A"` can be used to match a text node.

# ⏯ Playground Link

[Playground link with relevant code](https://ast-grep.github.io/playground.html#eyJtb2RlIjoiQ29uZmlnIiwibGFuZyI6ImphdmFzY3JpcHQiLCJxdWVyeSI6ImNsYXNzIFBERlZpZXdlckFwcGxpY2F0aW9ueyQkJF99IiwicmV3cml0ZSI6IiIsImNvbmZpZyI6IiMgWUFNTCBSdWxlIGlzIG1vcmUgcG93ZXJmdWwhXG4jIGh0dHBzOi8vYXN0LWdyZXAuZ2l0aHViLmlvL2d1aWRlL3J1bGUtY29uZmlnLmh0bWwjcnVsZVxubGFuZ3VhZ2U6IGpzXG5pZDogd2ViUGF0aFxucnVsZTpcbiAga2luZDogaW1wb3J0X3N0YXRlbWVudFxuICBwYXR0ZXJuOiBpbXBvcnQgJEEgZnJvbSAkQiAjIGltcG9ydCAkQSBmcm9tIFwiJEJcIlxuXG4iLCJzb3VyY2UiOiJpbXBvcnQgeyBQREZMYXllclZpZXdlciB9IGZyb20gXCJ3ZWItcGRmX2xheWVyX3ZpZXdlclwiO1xuaW1wb3J0IHsgUERGT3V0bGluZVZpZXdlciB9IGZyb20gXCJ3ZWItcGRmX291dGxpbmVfdmlld2VyXCI7XG5pbXBvcnQgeyBQREZQcmVzZW50YXRpb25Nb2RlIH0gZnJvbSBcIndlYi1wZGZfcHJlc2VudGF0aW9uX21vZGVcIjtcbmNsYXNzIEF7XG4gIGNvbnN0cnVjdG9yKCl7XG5cbiAgfVxufSJ9)

# 💻 Code

Code:

```js
import { PDFLayerViewer } from "web-pdf_layer_viewer";
import { PDFOutlineViewer } from "web-pdf_outline_viewer";
import { PDFPresentationMode } from "web-pdf_presentation_mode";
class A{
  constructor(){

  }
}
```

Pattern:

```yml
language: js
id: webPath
rule:
  kind: import_statement
  pattern: import $A from $B # import $A from "$B"
```

# 🙁 Actual behavior

The pattern `import $B from $A` cannot be matched to a text node within the `import_statement` statement.

# 🙂 Expected behavior

You can directly use `$A` in `import $B from $A` to match text nodes, without the need for `import $B from "$A"`.

**Comment by HerringtonDarkholme** [comment]
`import $B from $A` is not a valid tree-sitter pattern.

> Pattern code must be valid code that tree-sitter can parse.

https://ast-grep.github.io/guide/pattern-syntax.html#pattern-matching

<img width="297" alt="image" src="https://github.com/ast-grep/ast-grep/assets/2883231/c3dd666f-7ecc-484f-b2e3-b58e488fa23b">

**Comment by zxhd863943427** [comment]
I see, I apologize for not reading the document carefully.
