### ISSUE TITLE
[bug] Identifiers in C++ initializer lists or as class members not detected 

### ISSUE THREAD

**Issue by arvid-norlander** [ast-grep/ast-grep#1187]
# ⏯ Playground Link
This playground doesn't seem to work for C++ at all for some unknown reason.

[Playground link with relevant code](https://ast-grep.github.io/playground.html#eyJtb2RlIjoiUGF0Y2giLCJsYW5nIjoiY3BwIiwicXVlcnkiOiJtX21lbWJlciIsInJld3JpdGUiOiJtX21lbWJlck5ld05hbWUiLCJjb25maWciOiIjIFlBTUwgUnVsZSBpcyBtb3JlIHBvd2VyZnVsIVxuIyBodHRwczovL2FzdC1ncmVwLmdpdGh1Yi5pby9ndWlkZS9ydWxlLWNvbmZpZy5odG1sI3J1bGVcbnJ1bGU6XG4gIGFueTpcbiAgICAtIHBhdHRlcm46IGNvbnNvbGUubG9nKCRBKVxuICAgIC0gcGF0dGVybjogY29uc29sZS5kZWJ1ZygkQSlcbmZpeDpcbiAgbG9nZ2VyLmxvZygkQSkiLCJzb3VyY2UiOiJjbGFzcyBEdW1teVxue1xucHVibGljOlxuICAgRHVtbXkoaW50IHZhbHVlKVxuICAgOiBtX21lbWJlcih2YWx1ZSlcbiAgIHtcbiAgIH1cblxuICAgaW50IG1fbWVtYmVyO1xuXG4gICBpbnQgZ2V0TXlNZW1iZXIoKVxuICAge1xuICAgICAgcmV0dXJuIG1fbWVtYmVyO1xuICAgfVxufTtcbiJ9)

# 💻 Code

Code:

```c++
class Dummy
{
public:
   Dummy(int value)
   : m_member(value)
   {
   }

   int m_member;

   int getMyMember()
   {
      return m_member;
   }
};

```

Pattern:

```yml
id: no-m-prefix
language: cpp
rule:
  pattern: $VARIABLE
  kind: identifier
  regex: "m_.*"

transform:
  RENAME:
    replace:
      source: $VARIABLE
      replace: m_(.*)
      by: "$1"

fix: '$RENAME'
```

# 🙁 Actual behavior

```console
❯ ast-grep scan -r no-m-prefix.yml reproducer.cpp                                                                 
reproducer.cpp
help[no-m-prefix]: 
@@ -9,6 +9,6 @@
10 10│ 
11 11│    int getMyMember()
12 12│    {
13   │-      return m_member;
   13│+      return member;
14 14│    }
15 15│ };
```

# 🙂 Expected behavior

All instances of the member should be replaced, not just those inside functions. As far as I can tell from the playground, all mentions of m_member classify as "identifier", but even a plain non-yaml rule without specifying kind doesn't match all uses.

It seems ast-grep simply doesn't see class members or initializer lists in C++ for some reason. I was hoping to use ast-grep to remove [Hungarian notation](https://en.wikipedia.org/wiki/Hungarian_notation) from a massive legacy code base.

* ast-grep 0.22.6 (installed via cargo install)
* Ubuntu 22.04
* Rust: rustc 1.78.0 (9b00956e5 2024-04-29) (from rustup)

**Comment by HerringtonDarkholme** [comment]
For the tree-sitter, it is because the kind is `field_identifier`

<img width="670" alt="image" src="https://github.com/ast-grep/ast-grep/assets/2883231/0cd2861d-b636-41f9-b7af-26ecd3977362">



I will fix the C++ playground when I have time.

**Comment by HerringtonDarkholme** [comment]
You also need to add `field_identifier` to the kind list. `identifier` and `field_identifier` is treated differently in tree-sitter grammar.

<img width="819" alt="image" src="https://github.com/ast-grep/ast-grep/assets/2883231/1e90fb90-8552-4b04-93ff-52cc4d4d00d7">


https://ast-grep.github.io/playground.html#eyJtb2RlIjoiQ29uZmlnIiwibGFuZyI6ImNwcCIsInF1ZXJ5IjoiJE1FVEhPRChcbiAgICAkQSwgLy8gQ29tbWVudFxuICAgICRGXG4pIiwicmV3cml0ZSI6Im1fbWVtYmVyTmV3TmFtZSIsImNvbmZpZyI6ImlkOiBuby1tLXByZWZpeFxubGFuZ3VhZ2U6IGNwcFxucnVsZTpcbiAgcGF0dGVybjogJFZBUklBQkxFXG4gIGFueTpcbiAgLSBraW5kOiBpZGVudGlmaWVyXG4gIC0ga2luZDogZmllbGRfaWRlbnRpZmllclxuICByZWdleDogXCJtXy4qXCJcblxudHJhbnNmb3JtOlxuICBSRU5BTUU6XG4gICAgcmVwbGFjZTpcbiAgICAgIHNvdXJjZTogJFZBUklBQkxFXG4gICAgICByZXBsYWNlOiBtXyguKilcbiAgICAgIGJ5OiBcIiQxXCJcblxuZml4OiAnJFJFTkFNRSciLCJzb3VyY2UiOiJjbGFzcyBEdW1teVxue1xucHVibGljOlxuICAgRHVtbXkoaW50IHZhbHVlKVxuICAgOiBtX21lbWJlcih2YWx1ZSlcbiAgIHtcbiAgIH1cblxuICAgaW50IG1fbWVtYmVyO1xuXG4gICBpbnQgZ2V0TXlNZW1iZXIoKVxuICAge1xuICAgICAgcmV0dXJuIG1fbWVtYmVyO1xuICAgfVxufTtcbiJ9

**Comment by arvid-norlander** [comment]
Thanks for your answers. Didn't see this until now due to holidays here in Sweden.
