### ISSUE TITLE
[feature] implement more matching algorithm for pattern

### ISSUE THREAD

**Issue by HerringtonDarkholme** [ast-grep/ast-grep#1188]
# ⭐ Suggestion

At the moment, ast-grep's match algorithm strictness has only one option: `Smart`, as defined in the this [page](https://ast-grep.github.io/advanced/match-algorithm.html#deep-dive-into-ast-grep-s-match-algorithm).

However, there are cases where we need more flexibility in the matching algorithm. For example, we may want to ignore all CST trivia nodes. Or even we want to ignore comment AST nodes.

Different pattern matching algorithms can be implemented to provide more flexibility to the users.
Every pattern can have their own matching algorithm to fine-tune the matching behavior.

## Detailed Design

1. Algorithm enum

The terminology of CST/AST/Significant is defined in this doc: 
https://ast-grep.github.io/advanced/core-concepts.html#what-is-tree-sitter

```rust
enum MatchAlgorithm {
  CST, // all nodes are matched
  Smart, // all nodes except source trivial nodes are matched.
  Significant, // only significant nodes are matched
  AST, // only ast nodes are matched
  Relaxed, // ast-nodes excluding comments are matched
}
```

The enum is sorted by strictness. `CST` is the most strict, and `Relaxed` is the least strict.

More strict algorithms will make the pattern to match fewer nodes. 
Less strict algorithms will make the pattern to match more nodes.

Note the `Smart` algorithm, which is the current algorithm, differentiates between source and target.
See [explanation](https://ast-grep.github.io/advanced/core-concepts.html#significant-vs-trivial).

2. Rule Config Change

The `pattern` object in rule config will have a new optional field `strictness`.

```yaml
pattern:
  context: "$A($B)"
  selector: "function_call"
  strictness: "relaxed"
```

3. CLI change

in the CLI, a new option `--strictness` will be added to specify the strictness of the matching algorithm.

```bash
ast-grep run --strictness relaxed -p '$A($B)'
```

# 💻 Use Cases

### string quotation

Previous `import $A from 'lib'` will not match `import $A from "lib"` because the quotation is different.

Using strictness `Significant`, `AST`, `Relaxed`, the pattern will match both cases.

* comment handling

Previous `$A($B)` will not match `foo(/* cmt */ bar)` because the comment is in between.

Using strictness `Relaxed`, the pattern will match both cases.

# Task List

- [x] #1224
- [x] #1229
- [x] #1239
- [x] #1243
- [x] #1241
- [x] #1246
- [x] add documentation about the new strictness
- [x] improve the page doc https://ast-grep.github.io/advanced/match-algorithm.html

# 🌎 Ecosystem

valibot: https://github.com/fabian-hiller/valibot/issues/623

codemod operator: https://github.com/fabian-hiller/valibot/blob/main/codemod/migrate-to-v0.31.0/src/index.ts#L389

**Comment by arybitskiy** [comment]
Question: does that means that relational/composite rules can have own matching algorithm?

**Comment by HerringtonDarkholme** [comment]
@arybitskiy Relational rules already have their matching algorithm https://ast-grep.github.io/guide/rule-config/relational-rule.html#fine-tuning-relational-rule

**Comment by partner-pierre-vande-laar** [comment]
You wrote
 *    Previous `$A($B)` will not match `foo(/* $A */, bar)`
 
 Do I correctly assume the comma is wrongly present, and it should be `foo(/* $A */ bar)`?
Furthermore, I hope that the metavariable `$A` is not mandatory in the comment, so maybe
`foo(/* argument => */ bar)` is maybe even better.

**Comment by HerringtonDarkholme** [comment]
@partner-pierre-vande-laar I have updated the issue text
