### ISSUE TITLE
[bug] Some Kotlin pattern works differently between CLI and Playground

### ISSUE THREAD

**Issue by orangain** [ast-grep/ast-grep#1218]
Thank you for creating a great tool! In the course of using it, I found a strange phenomenon where the behavior is different between CLI and Playground, and I would like to report it.

# ⏯ Playground Link

[Playground link with relevant code](https://ast-grep.github.io/playground.html#eyJtb2RlIjoiQ29uZmlnIiwibGFuZyI6ImtvdGxpbiIsInF1ZXJ5IjoiY29uc29sZS5sb2coJE1BVENIKSIsInJld3JpdGUiOiJsb2dnZXIubG9nKCRNQVRDSCkiLCJjb25maWciOiJpZDogcGFyYW1ldGVyLWluLXNlcmlhbGl6YWJsZS1jbGFzc1xubGFuZ3VhZ2U6IGtvdGxpblxucnVsZTpcbiAgcGF0dGVybjpcbiAgICBjb250ZXh0OiB8XG4gICAgICBjbGFzcyBYKFxuICAgICAgICB2YWwgJE5BTUU6ICRUWVBFXG4gICAgICApXG4gICAgc2VsZWN0b3I6IGNsYXNzX3BhcmFtZXRlclxuICBpbnNpZGU6XG4gICAgc3RvcEJ5OiBlbmRcbiAgICBwYXR0ZXJuOiB8XG4gICAgICBAU2VyaWFsaXphYmxlXG4gICAgICBkYXRhIGNsYXNzICQkJFxuIiwic291cmNlIjoicGFja2FnZSBjb20uZXhhbXBsZVxuXG5pbXBvcnQga290bGlueC5zZXJpYWxpemF0aW9uLlNlcmlhbGl6YWJsZVxuaW1wb3J0IGphdmEudXRpbC5VVUlEXG5cbkBTZXJpYWxpemFibGVcbmRhdGEgY2xhc3MgQW5ub3RhdGVkKFxuICAgIHZhbCBhOiBJbnQsXG4gICAgdmFsIGI6IFVVSUQsXG4pXG5cbmRhdGEgY2xhc3MgTm90QW5ub3RhdGVkKFxuICAgIHZhbCBhOiBJbnQsXG4gICAgdmFsIGI6IFVVSUQsXG4pXG4ifQ==)

As mentioned in the issue title, the Playground works as expected.

# 💻 Code

Code:

```kt
package com.example

import kotlinx.serialization.Serializable
import java.util.UUID

@Serializable
data class Annotated(
    val a: Int,
    val b: UUID,
)

data class NotAnnotated(
    val a: Int,
    val b: UUID,
)
```

Pattern:

```yml
id: parameter-in-serializable-class
language: kotlin
rule:
  pattern:
    context: |
      class X(
        val $NAME: $TYPE
      )
    selector: class_parameter
  inside:
    stopBy: end
    pattern: |
      @Serializable
      data class $$$
```

# 🙁 Actual behavior

`sg scan --rule parameter-in-serializable-class.yml Test.kt` does not match at all.

<img width="674" alt="image" src="https://github.com/ast-grep/ast-grep/assets/532251/847486f6-b7b9-45ac-a75a-54968eb43600">

Note that when I comment out the `inside` section of the rule, `sg scan --rule after-commen-out-inside.yml Test.kt` matches with the constructor parameters.

<img width="653" alt="image" src="https://github.com/ast-grep/ast-grep/assets/532251/4f2d9e81-0f80-4fa2-ad03-e8e4d287d950">

# 🙂 Expected behavior

`sg scan --rule parameter-in-serializable-class.yml Test.kt` should match with constructor parameters inside a data class that is annotated with the `@Serializable`.

As mentioned in the issue title, the Playground works as expected.

<img width="1237" alt="image" src="https://github.com/ast-grep/ast-grep/assets/532251/ba0ef123-5c4b-43b1-9d92-d49693d9b18d">

# Environment

* ast-grep 0.23.0 (installed via homebrew)
* macOS Sonoma 14.5

**Comment by HerringtonDarkholme** [comment]
Hi! Thanks for the report! I don't have time to give it a look at the moment but I will give it back as soon as possible!
Thank you for the patience!

**Comment by HerringtonDarkholme** [comment]
In the case of tree-sitter parser cannot parse your pattern, using relational + kind rule is easier.
See [this example](https://ast-grep.github.io/playground.html#eyJtb2RlIjoiQ29uZmlnIiwibGFuZyI6ImtvdGxpbiIsInF1ZXJ5IjoiQFNlcmlhbGl6YWJsZVxuZGF0YSBjbGFzcyAkQSIsInJld3JpdGUiOiIiLCJjb25maWciOiJpZDogcGFyYW1ldGVyLWluLXNlcmlhbGl6YWJsZS1jbGFzc1xubGFuZ3VhZ2U6IGtvdGxpblxucnVsZTpcbiAgcGF0dGVybjpcbiAgICBjb250ZXh0OiB8XG4gICAgICBjbGFzcyBYKFxuICAgICAgICB2YWwgJE5BTUU6ICRUWVBFXG4gICAgICApXG4gICAgc2VsZWN0b3I6IGNsYXNzX3BhcmFtZXRlclxuICBpbnNpZGU6XG4gICAga2luZDogcHJpbWFyeV9jb25zdHJ1Y3RvclxuICAgIGZvbGxvd3M6XG4gICAgICBwYXR0ZXJuOlxuICAgICAgICBjb250ZXh0OiAnQFNlcmlhbGl6YWJsZSBkYXRhIGNsYXNzIEEoYTogSW50KSdcbiAgICAgICAgc2VsZWN0b3I6IG1vZGlmaWVyc1xuICAgICAgc3RvcEJ5OiBlbmQiLCJzb3VyY2UiOiJAU2VyaWFsaXphYmxlXG5kYXRhIGNsYXNzIEFubm90YXRlZChcbiAgICB2YWwgYTogSW50LFxuICAgIHZhbCBiOiBVVUlELFxuKVxuIn0=)

<img width="929" alt="image" src="https://github.com/ast-grep/ast-grep/assets/2883231/47be27bd-7c29-4587-855a-db6d586e5821">

I also tested it on command line it works across different parser versions.
<img width="562" alt="image" src="https://github.com/ast-grep/ast-grep/assets/2883231/2b1d5b74-3d64-466a-a06e-543442cfe18b">

**Comment by orangain** [comment]
@HerringtonDarkholme Thank you for your prompt response! I was able to extract the class parameters as intended with the rules you suggested.

> The issue is
>
>     @Serializable data class $$$
>
> is not parsed as class constructor in tree-sitter-kotlin 0.3.6

However, I am really sorry, but I feel that this explanation does not accurately describe the cause. Because the CLI does not show any parsing errors for pattern, and it seems natural that tree-sitter Kotlin cannot parse code with meta variables as it is.

Upon further reflection after receiving the response, I realized that I could make the reproducible code much smaller. In the example below, the relational rule is no longer used.

Still, the situation remains the same: no match in the CLI, but a match in the playground. Is there any other possible cause?

------

# ⏯ Playground Link

[Playground link with relevant code](https://ast-grep.github.io/playground.html#eyJtb2RlIjoiQ29uZmlnIiwibGFuZyI6ImtvdGxpbiIsInF1ZXJ5IjoiY29uc29sZS5sb2coJE1BVENIKSIsInJld3JpdGUiOiJsb2dnZXIubG9nKCRNQVRDSCkiLCJjb25maWciOiJpZDogc2VyaWFsaXphYmxlLWNsYXNzXG5sYW5ndWFnZToga290bGluXG5ydWxlOlxuICBwYXR0ZXJuOiB8XG4gICAgQFNlcmlhbGl6YWJsZVxuICAgIGRhdGEgY2xhc3MgJCQkXG4iLCJzb3VyY2UiOiJwYWNrYWdlIGNvbS5leGFtcGxlXG5cbmltcG9ydCBrb3RsaW54LnNlcmlhbGl6YXRpb24uU2VyaWFsaXphYmxlXG5pbXBvcnQgamF2YS51dGlsLlVVSURcblxuQFNlcmlhbGl6YWJsZVxuZGF0YSBjbGFzcyBBbm5vdGF0ZWQoXG4gICAgdmFsIGE6IEludCxcbiAgICB2YWwgYjogVVVJRCxcbilcblxuZGF0YSBjbGFzcyBOb3RBbm5vdGF0ZWQoXG4gICAgdmFsIGE6IEludCxcbiAgICB2YWwgYjogVVVJRCxcbilcbiJ9)

# 💻 Code
Code (Unchanged from the original):

```kt
package com.example

import kotlinx.serialization.Serializable
import java.util.UUID

@Serializable
data class Annotated(
    val a: Int,
    val b: UUID,
)

data class NotAnnotated(
    val a: Int,
    val b: UUID,
)
```

Pattern:

```yml
id: serializable-class
language: kotlin
rule:
  pattern: |
    @Serializable
    data class $$$
```

# 🙁 Actual behavior

The CLI does not match.

<img width="546" alt="image" src="https://github.com/ast-grep/ast-grep/assets/532251/ae3910c4-5c01-4307-8ad5-8cd6e50521c2">

# 🙂 Expected behavior

The CLI should match with the annotated class as the playground does.

<img width="1247" alt="image" src="https://github.com/ast-grep/ast-grep/assets/532251/d5defb73-8258-4125-a554-6053b6ecd103">

**Comment by orangain** [comment]
I have updated the title of the issue. My main concern is the difference between CLI and playground. Because such a difference would make rule development more difficult.

If the difference is due to differences in library versions, it would be nice if either of the following could be accomplished.

- The CLI and the playground show the version of the ast-grep and depending libraries including the tree-sitter so that a user can notice the difference of the versions.
- The CLI provides something like a debug mode that shows AST structure of the pattern and the input code so that a user can notice the difference of the parsed structure.

**Comment by HerringtonDarkholme** [comment]
Thanks 👍 Having a cli debug output will be very helpful. 
I will implement it in near future

**Comment by HerringtonDarkholme** [comment]
One more thing is to note is the behavior of treesitter. 
At most time web and native tree sitter behave the same. However, when the input is not valid, which is commonly seen in pattern, web and native will behave differently due to tree sitter heuristics. 

TS will try to recover from parsing error and the recovery is based on the input length. Sadly, web and native tree sitter have different string encoding so their length are different. 

This makes different parsing results

**Comment by StevenLove** [comment]
That is a fascinating explanation for why tree sitter has different behavior in a browser vs natively.
Here's an example of tree sitter behaving differently for strings of different lengths:

![GIF of tree sitter behavior](https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExMmc5dm1jbHB1Y2U2ZDBkd214a2JxNXExbThxcGtsMTJybGhiejZvdCZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/EvBSeL6mE1ySFHrKVr/giphy.gif)

**Comment by orangain** [comment]
@HerringtonDarkholme @StevenLove Thank you for clarifying the difference between web and native. I understand that the parsing result depends on the length of the input.

I am interested in the different encodings that affect the length of the input. Personally, if there is an option to use the same encoding in the CLI and playground, I would prefer to use that, even if it slows down the execution.  This is because I often refer to the playground results when developing ast-grep rules, and I consider the consistency of the results to be important.

**Comment by HerringtonDarkholme** [comment]
I have added `--debug-query=ast` in the CLI to dump tree-sitter output.

**Comment by HerringtonDarkholme** [comment]
Related documentation https://ast-grep.github.io/reference/cli/run.html#debug-query-format

**Comment by orangain** [comment]
@HerringtonDarkholme Thank you for adding the debugging feature so quickly! It will be useful for debugging patterns.

If possible, the same flag for the `sg scan` command would also make it easier to debug when we write the pattern in a yaml file.

**Comment by HerringtonDarkholme** [comment]
thanks for the suggestion. But a rule YAML usually has many patterns and displaying them in one command is not straightforward. For example, there may be multiple patterns but only one pattern is interested. Using the playground has a better debugging experience.
