### ISSUE TITLE
[bug] `has` only checks first child node when using `pattern: $CAPTURE`

### ISSUE THREAD

**Issue by StevenLove** [ast-grep/ast-grep#1225]
# **Note that this is similar to issue #1164 but slightly different!**

![GIF](https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExaWpmZ2JpdWpscjliZjA4OG1rMWF3cnV6Y3lmb2lsN3dkMXd4cXN0YyZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/9tEc2l6oA9dsqxeDou/giphy.gif)

# [Playground link with relevant code](https://ast-grep.github.io/playground.html#eyJtb2RlIjoiQ29uZmlnIiwibGFuZyI6InJ1c3QiLCJxdWVyeSI6Ii8vIERlYnVnLmFzc2VydCIsInJld3JpdGUiOiJEZWJ1Zy5hc3NlcnQiLCJjb25maWciOiJydWxlOlxuICBraW5kOiBibG9ja1xuICBoYXM6XG4gICAgcGF0dGVybjogJENBUFRVUkVcbiAgICByZWdleDogXCJjb25zdFwiXG4gICAgIiwic291cmNlIjoicHViIGZuIGF2ZXJhZ2UobnVtYmVyczogJltpMzJdKSAtPiBmMzIge1xuICAgIGxldCB4ID0gMTtcbiAgICBjb25zdCB6ID0gOTk5O1xuICAgIC8vIFdyaXRlIHlvdXIgbG9naWMgaGVyZVxuICAgIC8vIGNvbnN0IGJvb2xlYW5cbn0ifQ==)

# 💻 Code

```rust
pub fn average(numbers: &[i32]) -> f32 {
    let x = 1;
    const z = 999;
    // Write your logic here
    // const boolean
}
```
```yml
rule:
  kind: block
  has:
    pattern: $CAPTURE
    regex: "const"
```

# 🙁 Actual behavior

No match is found

# 🙂 Expected behavior

We should match the entire block because its second and fourth children both match the regex "const".  It appears to only check the first child of the block for this regex. Behavior doesn't change using `stopBy: end`. Problem only arises when we use `pattern: $CAPTURE` to also try to capture the content of the matched child.

**Comment by HerringtonDarkholme** [comment]
Good report. I think this is because the `has` rule should not write to capturing if other rules are not matched.
