### ISSUE TITLE
[feature request]  support @ast-grep/napi-linux-arm64-musl

### ISSUE THREAD

**Issue by gregoirer** [ast-grep/ast-grep#1227]
the code refers to a non existent optional package 

nativeBinding = require('@ast-grep/napi-linux-arm64-musl')

Do you plan to support it ? Is there a workaround possible ?

following optional package are available but  @ast-grep/napi-linux-arm64-musl is missing.
@ast-grep/napi-linux-x64-gnu
@ast-grep/napi-darwin-arm64
@ast-grep/napi-darwin-x64
@ast-grep/napi-linux-x64-musl
@ast-grep/napi-win32-x64-msvc
@ast-grep/napi-win32-arm64-msvc
@ast-grep/napi-win32-ia32-msvc
@ast-grep/napi-linux-arm64-gnu

**Comment by HerringtonDarkholme** [comment]
I don't have plan to support MUSL itself but contributors can take a look at it.
