### ISSUE TITLE
[feature] Is it possible to make the fields of `Range` public?

### ISSUE THREAD

**Issue by etiennebacher** [ast-grep/ast-grep#1228]
# ⭐ Suggestion

I'm making an R binding to `ast-grep` that mimicks the Python API. For the `range()` function, I'd like to access the `start` and `end` values of the `Range` struct but apparently those two fields are private. Is it possible to make them public?

# 💻 Use Cases

To return the `start` and `end` values to R, I must be able to access them (I can't return the `Range` struct at once).

**Comment by HerringtonDarkholme** [comment]
You can already access them via `node.range()`

Example code
https://github.com/ast-grep/ast-grep/blob/989f040efdb24ac4923f35e7e2b37b77b8033cd7/crates/pyo3/src/range.rs#L100-L112

**Comment by etiennebacher** [comment]
Indeed, thank you and sorry for bothering

**Comment by HerringtonDarkholme** [comment]
If you are integrating ast-grep into other programming language, the [napi](https://github.com/ast-grep/ast-grep/tree/main/crates/napi) and [pyo3](https://github.com/ast-grep/ast-grep/tree/main/crates/pyo3) folders will be very helpful.

One particular thing you may need pay attention to is the text encoding. Tree-sitter returns a byte offset in utf8 or utf16, which is usually not how programming languages handle character offsets.

**Comment by HerringtonDarkholme** [comment]
Another repo for reference https://github.com/Zheaoli/astgrep-java-unonfficial

**Comment by etiennebacher** [comment]
Thanks for the hints, I'm definitely following the pyo3 implementation
