### ISSUE TITLE
[bug] $$$ operator only inserts single element

### ISSUE THREAD

**Issue by pjljvandelaar** [ast-grep/ast-grep#1256]
# ⏯ Playground Link

https://ast-grep.github.io/playground.html#eyJtb2RlIjoiQ29uZmlnIiwibGFuZyI6ImNwcCIsInF1ZXJ5IjoiaWYgKCRDKSB7ICQkJFNIQVJFRDsgJFVOSVFVRTsgJCQkTU9SRTsgfSBlbHNlIHsgJCQkU0hBUkVEOyB9XHJcbiIsInJld3JpdGUiOiJib29sIGNvbmQgPSAkQzsgJCQkU0hBUkVEOyBpZiAoY29uZCkgeyRVTklRVUU7ICQkJE1PUkU7IH0iLCJjb25maWciOiJydWxlOlxyXG4gICAgcGF0dGVybjogaWYgKCRDKSB7ICQkJFNIQVJFRCB9IGVsc2UgeyAkJCRTSEFSRUQgfVxyXG5maXg6XHJcbiAgICBib29sIGNvbmQgPSAkQzsgJCQkU0hBUkVEIiwic291cmNlIjoidm9pZCBtYWluICgpe1xuICAgIGlmICh4IDwgeSkge1xuICAgIHgrKztcbiAgICB5Kys7XG4gIH0gZWxzZSB7XG4gICAgeCsrO1xuICAgIHkrKztcbiAgfVxuXG4gIGlmICh4IDwgeSkge1xuICAgIHgrKztcbiAgICB5Kys7XG4gICAgeCsrO1xuICB9IGVsc2Uge1xuICAgIHgrKztcbiAgICB5Kys7XG4gIH1cblxuICAgIGlmICh4IDwgeSkge1xuICAgIHgrKztcbiAgICB5Kys7XG4gICAgeCsrO1xuICAgIHkrKztcbiAgfSBlbHNlIHtcbiAgICB4Kys7XG4gICAgeSsrO1xuICB9XG59XG4ifQ==

# 💻 Code

Code:
```cpp
void main (){
    if (x < y) {
    x++;
    y++;
  } else {
    x++;
    y++;
  }
```

Pattern:

```yml
rule:
    pattern: if ($C) { $$$SHARED } else { $$$SHARED }
fix:
    bool cond = $C; $$$SHARED
```

# 🙁 Actual behavior

One gets:
 `bool cond = x < y; x++;`

![image](https://github.com/ast-grep/ast-grep/assets/18348654/9127ce3a-4a67-4a40-8c27-e75d56640010)

# 🙂 Expected behavior

One should get:
 `bool cond = x < y; x++; y++;`

**Comment by HerringtonDarkholme** [comment]
Please see https://stackoverflow.com/questions/78663351/why-is-the-last-statement-ignored-in-ast-grep-tree-sitter-with-c-in-compound
