### ISSUE TITLE
[bug] nested patterns are not matched and fixed

### ISSUE THREAD

**Issue by pjljvandelaar** [ast-grep/ast-grep#1257]
# ⏯ Playground Link

https://ast-grep.github.io/playground.html#eyJtb2RlIjoiUGF0Y2giLCJsYW5nIjoiY3BwIiwicXVlcnkiOiJpZiAoJEMpIHsgJCQkUyB9IGVsc2UgeyAkJCRTIH0iLCJyZXdyaXRlIjoiJEM7ICQkJFMiLCJjb25maWciOiIiLCJzb3VyY2UiOiJ2b2lkIHRlc3RfZnVuYygpIHtcbiAgIGlmIChjKSB7IGlmIChkKSB7IGkrKzsgfSBlbHNlIHsgaSsrOyB9fSBlbHNlIHsgaWYgKGQpIHtpKys7fSBlbHNlIHtpKys7fX1cbn0gIn0=

# 💻 Code

Code:
```cpp
void test_func() {
   if (c) { if (d) { i++; } else { i++; }} else { if (d) {i++;} else {i++;}}
} 
```

Pattern:
`if ($C) { $$$S } else { $$$S }`
Rewrite:
`$C; $$$S`

Note: we have to execute $C since it might have a side effect.
I have not been able to find filter functions to determine this? Do they exists?

# 🙁 Actual behavior

Although 3 matches are found, the code is only changed to
```cpp
c; if (d) {i++;} else {i++;}
```
# 🙂 Expected behavior

Expected changes
```cpp
c; d; i++;
```
since the pattern can also be applied to AST tree within $$$S of the first match.

**Comment by HerringtonDarkholme** [comment]
Nested match will not be replaced recursively. Recursive replacement can too easily make two rules conflict with each other.

Applying the rewrite multiple times is recommended at the moment. Or you can use the JS/Py API.
