### ISSUE TITLE
[BUG] Find_all_assignments

### ISSUE THREAD

**Issue by pjljvandelaar** [ast-grep/ast-grep#1259]
A pattern can match a AST node.

When meta variables for lists are involved, multiple assignments to these meta-variables are possible.
For example
```
f($$$BEFORE, $VALUE, $$$AFTER)
```
matches
```
f(1,2)
```
with the following possible assignments

| $$$BEFORE  | $VALUE | $$$AFTER |
| ------------- | ------------- | --------|
| 1  | 2  | empty |
| empty | 1 | 2 | 

Currently, not all assignments are considered, as is mentioned in e.g., https://github.com/ast-grep/ast-grep/discussions/1252.
As a consequence, sometimes no match is found while a match exists!

At least two options exists to implement this functionality
1. Use backtracking
2. Use a set of valid assignments

**Comment by HerringtonDarkholme** [comment]
Using backtracking will too easily slow down pattern matching algorithm to polynomial time complexity or even exponential time complexity. ast-grep is designed to be fast and adopting uncontrollable time complexity is out of scope.

**Comment by pjljvandelaar** [comment]
A petty you prefer speed over correct analysis.
Especially, since 
* complexity will only be encountered when patterns cause it (i.e., have multiple $$$ meta variables in a single list)
* although programs can have theoretically lists of any length, most lists have a rather small number of elements.

**Comment by pjljvandelaar** [comment]
Just to be certain:
When someone contributes a merge request with this functionality, and with multiple test cases showing not only the correctness but also performance in many scenarios, this community will not accept that contribution?

**Comment by HerringtonDarkholme** [comment]
@pjljvandelaar  if you need matching algorithm not supported by pattern, you can always use JS/Py API https://ast-grep.github.io/guide/api-usage.html. Pattern is **NOT** a silver bullet for every scenario.
