### ISSUE TITLE
[feature] Language request: Elixir

### ISSUE THREAD

**Issue by setop** [ast-grep/ast-grep#1262]
# ⭐ Suggestion

Add [Elixir](https://elixir-lang.org/) to the list of supported languages

# 💻 Use Cases

Elixir is getting pretty popular

![](https://github.com/ast-grep/ast-grep/assets/7794056/21ded7fe-f2be-4b8b-b43f-fe70064374cc)

and has an official [tree-sitter plugin](elixir-lang/tree-sitter-elixir)

Would be nice to have it in SG in order to perform large refactoring.

**Comment by HerringtonDarkholme** [comment]
It's already supported https://github.com/ast-grep/ast-grep/blob/main/crates/language/src/elixir.rs
