### ISSUE TITLE
[feature] Do not fail on missing directories (e.g. `utilDirs:`) or create `.keep` file in new dirs

### ISSUE THREAD

**Issue by powerman** [ast-grep/ast-grep#1273]
# ⭐ Suggestion

Ignore missing directories listed in `sgconfig.yml` or create `.keep` file in each created empty dir.

# 💻 Use Cases

1. `sg new`
```
No sgconfig.yml found. Creating a new ast-grep project...
> Where do you want to have your rules? .sg/rules
> Do you want to create rule tests? Yes
> Where do you want to have your tests? .sg/tests
> Do you want to create folder for utility rules? Yes
> Where do you want to have your utilities? .sg/utils
Your new ast-grep project has been created!
```
2. `sg new rule`
```
> Select the item you want to create: Rule
> What is your rule's name? test
> Choose rule's language Bash
Created rules at ././.sg/rules/test.yml
> Do you also need to create a test for the rule? Yes
Created test at ./.sg/tests/test-test.yml
```
3. Write some rule and tests.
```
$ find .sg
.sg
.sg/rules
.sg/rules/test.yml
.sg/utils
.sg/tests
.sg/tests/test-test.yml
```
4. `git add . && git push`
5. Use `ast-grep/action`.
6. Get error:
![изображение](https://github.com/ast-grep/ast-grep/assets/1354301/d4ec3fc9-f8e7-4d0b-9a1e-8f5c5e8c0f62)

Another option is to change `sg new` to create `.keep` file in all directories it creates, to make sure these directories will be committed into git.

**Comment by HerringtonDarkholme** [comment]
I think in this case you should answer NO when creating utils dir.

If creating `.keep` in `utils`, we should also create one in `rule` dir.

**Comment by powerman** [comment]
> I think in this case you should answer NO when creating utils dir.

In this case if I'll need to add utils dir later and open this sgconfig.yml:

```yaml
ruleDirs:
  - ./.sg/rules
testConfigs:
  - testDir: ./.sg/tests
```
it won't be clear what to write here without reading the docs first (because format isn't consistent). So it looks easier to always create all dirs while `sg new` - writing rules without tests is mostly fiction case, and needs in utils often hard to predict when we start using the tool for a project.

> If creating .keep in utils, we should also create one in rule dir.

Yep. And in tests/ too. I don't see anything wrong with that - user can remove them later if he want to.

**Comment by powerman** [comment]
> I think in this case you should answer NO when creating utils dir.

Maybe another option is to have `sg new` add (commented out) example of configuring utils dir into sgconfig.yml in case user answered NO.

**Comment by HerringtonDarkholme** [comment]
> > if I'll need to add utils dir later and open this sgconfig.yml:
>
> >  - user can remove them later if he want to.

I would argue these two are conflicting: if it is inconvenient to add fields in sgconfig.yml, it is equally inconvenient to remove `.keep`. 

That said, I think adding an example rule in test/utils/rules can be a good way to make the situation easier.

**Comment by HerringtonDarkholme** [comment]
I decided to create a keep file because more users are complaining this.
