### ISSUE TITLE
[feature][new language] Add support for SQL

### ISSUE THREAD

**Issue by alexbit-codemod** [ast-grep/ast-grep#1300]
# ⭐ Suggestion

Add support for SQL so users can use ast-grep for DB related migrations and best practices. MASSIVE opportunity.

# 💻 Use Cases
1. DB migrations
2. enforcing best practices

**Comment by php-coder** [comment]
Sounds great! Do we have examples to look at?

**Comment by vergenzt** [comment]
FYI sql is not yet listed at https://ast-grep.github.io/reference/languages.html 🙂

**Comment by engelhro** [comment]
> FYI sql is not yet listed at https://ast-grep.github.io/reference/languages.html 🙂

That's probably because **SQL was removed** again (see ticket #1743 and associated commits) 😞.

That's _very_ sad – I thought I've just found a great tool, only to discover it does not support one of the most wide-spread languages… 

Unfortunately there's also no reason given, no explanation, just a plain "removed as never supported". And also no intention mentioned to add it back and make it officially supported.

**Comment by HerringtonDarkholme** [comment]
First, SQL was introduced as experimental support only https://github.com/ast-grep/ast-grep/commit/6a7c07e49945fd2fb61585285bc2a626592e2036

> It does not support one of the most wide-spread languages

ast-grep cannot support all languages. The criterion to accept a language as builtin is that it should have official or semi-official support, either from tree-sitter org or the programming language org.

>  removed as never supported

It was never supported, as it was never announced. It was introduced as a courtesy to ast-grep's sponsor, CodeMod. 

> make it officially supported.

SQL is not a general-purpose programming language, and I also didn't see any SQL users using this tool to migrate/lint SQLs. I don't think the change broke anyone.  In fact, if you have ever used SQL with ast-grep, you will find a lot of pattern parsing issues that you need to work around. Supporting it will introduce more usage questions for the tool.

That said, you can always use https://ast-grep.github.io/advanced/custom-language.html to load your preferred programming language in ast-grep.
