### ISSUE TITLE
A way to specify which files to be scanned in sgconfig.yml or rule.yml

### ISSUE THREAD

**Issue by wlohrmann-hf** [ast-grep/ast-grep#1314]
# ⭐ Suggestion

It'd be nice to specify which files to include and which to ignore. Preferably this would be on a per-rule basis. At the moment we run `sg scan` multiple times for each rule and file set. 

# 💻 Use Cases

Some rules only make sense in certain contexts (Like a part of an app), or it may take some time to migrate an entire code base but we'd like to increase the coverage of the rule gradually over time.

**Comment by HerringtonDarkholme** [comment]
Please see 
https://ast-grep.github.io/guide/project/lint-rule.html#other-linting-fields
https://ast-grep.github.io/reference/yaml.html#globbing

**Comment by wlohrmann-hf** [comment]
Brilliant! Thanks for taking the time to answer
