### ISSUE TITLE
[bug] File path determined by scan is not consistent

### ISSUE THREAD

**Issue by soceanainn** [ast-grep/ast-grep#1343]
# 🙁 Actual behavior

I'm using `ast-grep` in two ways:
1. Run and apply updates on IDE save (runs `ast-grep scan -U path/to/file.py`.
2. Checking rules as part of a lint step in CI (runs `ast-grep scan`).

When running `ast-grep scan path/to/file.py` (full path to file) or `ast-grep scan path/` (path to some subdirectory in project containing that file), it determines the path to be: `path/to/file.py`.

When running `ast-grep scan` or `ast-grep scan .`, it determines the path of the same file to be `./path/to/file.py` (it adds a `./` prefix).

I need to add two ignores values to my rules to ignore this file successfully for every way that I run ast-grep (once with `./` prefix and once without).

# 🙂 Expected behavior

There shouldn't be a difference in how `ast-grep scan` treats the same file, when running ast-grep from my project root. Ideally my ignore entry would accept files with or without a `./` prefix, and work.

I think ideally CLI should be consistent in using one or the other.

**Comment by HerringtonDarkholme** [comment]
The behavior itself follows ripgrep, which makes sense for the search tool.

But ast-grep is not ONLY a search tool. Having a consistent file path output is important for rule ignore/include.
