### ISSUE TITLE
[feature] Allow multiple tests in a single YAML file

### ISSUE THREAD

**Issue by soceanainn** [ast-grep/ast-grep#1344]
# ⭐ Suggestion

Allow multiple tests in a single file using multiple YAML docs in a single file (i.e. using `---` ).

# 💻 Use Cases

I can add multiple rules in a single file, using `---` to separate docs, but this does not work for tests. 

As a result, I end up writing multiple related rules in a single file, and then creating a test directory to test each rule within that file separately.

It seems counterintuitive that my test file structure cannot match my rule file structure.

**Comment by HerringtonDarkholme** [comment]
Great suggestion!
