### ISSUE TITLE
[bug] Python API: `SgRoot` removes leading `\n`

### ISSUE THREAD

**Issue by etiennebacher** [ast-grep/ast-grep#1345]
# ⏯ Playground Link

/

# 💻 Code

Code:

```
from ast_grep_py import SgRoot

SgRoot("print('hello world')\n", "python").root().text()
SgRoot("\nprint('hello world')", "python").root().text()
```

# 🙁 Actual behavior

Trailing `\n` are kept, but not leading `\n`:

```
>>> SgRoot("print('hello world')\n", "python").root().text()
"print('hello world')\n"
>>> SgRoot("\nprint('hello world')", "python").root().text()
"print('hello world')"
```

# 🙂 Expected behavior

```
>>> SgRoot("print('hello world')\n", "python").root().text()
"print('hello world')\n"
>>> SgRoot("\nprint('hello world')", "python").root().text()
"\nprint('hello world')"
```

I don't know if this is a bug, but it could be worth a mention in the docs of the Python API.

**Comment by HerringtonDarkholme** [comment]
I believe this is the intended behavior since I can reproduce it in tree-sitter's playground.

Note the `root` will return `module` in Python with trailing newlines. The actual print statement is accessed via `root().child(0)`

**Comment by etiennebacher** [comment]
I see, I fixed this just by using the line start in the root's range to determine how many empty lines I need to add before. Thanks!
