### ISSUE TITLE
[feature] Report unused suppressions / 'ast-grep-ignore' comments

### ISSUE THREAD

**Issue by soceanainn** [ast-grep/ast-grep#1346]
# ⭐ Suggestion

As time goes on in a large code base, it would be good to be able to report unused 'ast-grep-ignore' comments.

# 💻 Use Cases

It's easy to miss removal of `ast-grep-ignore` comments as you are refactoring code or changing/removing rule definitions. Having an automated way to report unused `ast-grep-ignore` comments after running `ast-grep scan` would be really useful in large codebases.

**Comment by HerringtonDarkholme** [comment]
shipped in 0.28.1
