### ISSUE TITLE
[feature] Turn 'ast-grep' in a transpiler tool.

### ISSUE THREAD

**Issue by mkanada** [ast-grep/ast-grep#1348]
You all have created a really nice tool for transforming source code in the same language. But, I think that there is a need to more transpilers. I've tried to create one, but I have really low experience in creation of this type of program. My objective was translate a software from TypeScript to Dart. I've started writing de transpiler in Java with antlr, but I don't have the knowledge necessary to do it.

I think that we don't need one optmizing transpiler. I mean, a transpiler that translate to the target language as a human. But, if the software just compile, works and is human readable, will be a good start. Just imagine how much good software was written in C, JavaScript, Java and other languages. And new good languages like Rust, Dart, Zig, etc, each one with his pro and contras. Good languages that don't have all good stuff that is already written in other languages.

A step further.

I imagined this scenario. A piece of code written in the source language, and the same code written in the target language. The transpiler tool parses both code and (interactively or not) write rule to transform one AST to other AST. So, with some examples, the user could create a set of rules that will be applied to his software.

That's it. Just think about it.

**Comment by HerringtonDarkholme** [comment]
Thank you for your suggestion and for appreciating our tool!

Creating a transpiler involves more than just translating ASTs; it requires a deep semantic understanding of the programming languages and their standard libraries. This is currently beyond the scope of ast-grep.

We appreciate your input and encourage you to continue sharing your ideas!
