### ISSUE TITLE
[feature] Using WASM as custom language parser

### ISSUE THREAD

**Issue by HerringtonDarkholme** [ast-grep/ast-grep#1364]
# ⭐ Suggestion
Currently ast-grep can only load custom language parser via dynamic library in the CLI.
However, dynamic library is platform dependent and it is hard for users to distribute their own language parser.

We can follow [Zed](https://zed.dev/blog/language-extensions-part-1)'s approach to use web assembly runtime to load custom language.

This will also be easier to use custom language in JS/Py.

- [x] Upgrade tree-sitter parser version
- [ ] Add wasm-time as deps 
- [ ] add WASM dynamic library config
- [ ] add wasm support to JS
- [ ] add wasm support to Py

**Comment by HerringtonDarkholme** [comment]
Sadly wasmtime is not ready yet. Closing now.

**Comment by ribru17** [comment]
Would you mind sharing the problems with wasmtime? I was going to try this myself before I saw your issue :( sad to see it looks too difficult. Do you know what blockers must be resolved for this to be done?

**Comment by HerringtonDarkholme** [comment]
Wasmtime does not support some platforms that ast-grep supports

**Comment by ribru17** [comment]
Ah, that is a shame. Do you happen to remember which platforms are unsupported?

**Comment by HerringtonDarkholme** [comment]
https://docs.wasmtime.dev/stability-platform-support.html

**Comment by ribru17** [comment]
Correct me if I'm wrong; looks like 32 bit windows is the only release artifact published by ast-grep which is not supported by wasmtime. Maybe we can just disable support for this on that architecture?

**Comment by ribru17** [comment]
Yeah fair... this would be because NAPI cannot use wasmtime? (sorry for all the questions)

**Comment by HerringtonDarkholme** [comment]
>  because NAPI cannot use wasmtime

NAPI has even more platforms to support compared to CLI. See https://github.com/ast-grep/ast-grep/actions/runs/14855729166 and  https://github.com/ast-grep/ast-grep/actions/runs/14460256483
