### ISSUE TITLE
[bug]$$$ARGS does not match zero nodes when it appears after another node in the pattern

### ISSUE THREAD

**Issue by wlohrmann-hf** [ast-grep/ast-grep#1365]
# ⏯ Playground Link

[Playground link with relevant code](https://ast-grep.github.io/playground.html#eyJtb2RlIjoiQ29uZmlnIiwibGFuZyI6InB5dGhvbiIsInF1ZXJ5IjoiJEM6ICRUID0gcmVsYXRpb25zaGlwKCQkJEEsIHVzZWxpc3Q9VHJ1ZSwgJCQkQikiLCJyZXdyaXRlIjoiJEM6IExpc3RbJFRdID0gcmVsYXRpb25zaGlwKCQkJEEsIHVzZWxpc3Q9VHJ1ZSwgJCQkQikiLCJjb25maWciOiIjIHlhbWwtbGFuZ3VhZ2Utc2VydmVyOiAkc2NoZW1hPWh0dHBzOi8vcmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbS9hc3QtZ3JlcC9hc3QtZ3JlcC9tYWluL3NjaGVtYXMvcnVsZS5qc29uXG5cbmxhbmd1YWdlOiBQeXRob25cbnJ1bGU6XG4gIHBhdHRlcm46IHN0LiRGVU4oJCQkQVJHU19QUkUsIGtleT0kS0VZLCAkJCRBUkdTX1BPU1QpIiwic291cmNlIjoic3QucHJpbnQoKVxuc3QucHJpbnQoa2V5PVwiaGlcIilcbnN0LnByaW50KDEsIGtleT1cIndvd1wiKVxuc3QucHJpbnQoMSwgMiwga2V5PVwid293XCIsIGhlbGxvPTMpXG4ifQ==)

# 💻 Code

Code:

```python
st.print()
st.print(key="hi")
st.print(1, key="wow")
st.print(1, 2, key="wow", hello=3)
```

Pattern:

```yml
language: Python
rule:
  pattern: st.$FUN($$$ARGS_PRE, key=$KEY, $$$ARGS_POST)
```

# 🙁 Actual behavior

Only the last line of code is matched

# 🙂 Expected behavior

The three bottom lines are matched. I would expect to see `$$$ARGS_PRE` to capture 0, 1 and 2 nodes respectively and `$$$ARGS_POST` to match 0, 0 and 1 nodes. 

If I remove the `$$$ARGS_POST`, so the pattern becomes `st.$FUN($$$ARGS_PRE, key=$KEY)` then lines 2 and 3 are matched, so `$$$ARGS_PRE` captures zero or one node but it looks like `$$$ARGS_POST` must match at least one node. This is contrary to [the documentation](https://ast-grep.github.io/guide/pattern-syntax.html#multi-meta-variable) on multi meta variables. 

As a side note, what I'm really trying to achieve is to extract the `key=$KEY` pattern when it occurs inside a `st.$FUN($$$)` context but I'm not able to do that because this pattern doesn't match any of the lines:

```yml
language: Python
rule:
  pattern: key=$KEY
```

I would appreciate any help in achieving that but I also think the first issue is a bug.

**Comment by HerringtonDarkholme** [comment]
The problem is about the `,` after the `$$$PRE_ARGS`. to match the pattern, `,`, the unnamed node is matched against the source code. 

I will try to make this better with different [strictness](https://ast-grep.github.io/guide/rule-config/atomic-rule.html#strictness)

**Comment by HerringtonDarkholme** [comment]
@wlohrmann-hf  you can use this rule 

this is called object pattern style https://ast-grep.github.io/reference/rule.html#pattern

https://ast-grep.github.io/playground.html#eyJtb2RlIjoiQ29uZmlnIiwibGFuZyI6InB5dGhvbiIsInF1ZXJ5IjoiJEM6ICRUID0gcmVsYXRpb25zaGlwKCQkJEEsIHVzZWxpc3Q9VHJ1ZSwgJCQkQikiLCJyZXdyaXRlIjoiJEM6IExpc3RbJFRdID0gcmVsYXRpb25zaGlwKCQkJEEsIHVzZWxpc3Q9VHJ1ZSwgJCQkQikiLCJjb25maWciOiIjIHlhbWwtbGFuZ3VhZ2Utc2VydmVyOiAkc2NoZW1hPWh0dHBzOi8vcmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbS9hc3QtZ3JlcC9hc3QtZ3JlcC9tYWluL3NjaGVtYXMvcnVsZS5qc29uXG5cbmxhbmd1YWdlOiBQeXRob25cbnJ1bGU6XG4gIHBhdHRlcm46IFxuICAgIGNvbnRleHQ6IHAoa2V5PSRLRVkpXG4gICAgc2VsZWN0b3I6IGtleXdvcmRfYXJndW1lbnQiLCJzb3VyY2UiOiJzdC5wcmludCgpXG5zdC5wcmludChrZXk9XCJoaVwiKVxuc3QucHJpbnQoMSwga2V5PVwid293XCIpXG5zdC5wcmludCgxLCAyLCBrZXk9XCJ3b3dcIiwgaGVsbG89MylcbiJ9

**Comment by wlohrmann-hf** [comment]
Thanks so much, that's working brilliantly!

**Comment by HerringtonDarkholme** [comment]
Under strictness ast,  `st.$FUN($$$ARGS_PRE, key=$KEY, $$$ARGS_POST)` can match all these statements.

The fix will be released in next version.
