### ISSUE TITLE
[bug] napi.findFiles() issue: SgNode for file A apparently references text from file B

### ISSUE THREAD

**Issue by kyegupov** [ast-grep/ast-grep#1380]
Idea: use ast-grep napi programmatically.
# 💻 Code

```
  const matches = await ts.findInFiles(
    {
      paths: ["../src"],
      matcher: {
        rule: { pattern: "yup.object($OBJ)" },
      },
    },
    processMatch,
  );

function processMatch(err: any, sgNodes: SgNode[]) {
  for (const sgNode of sgNodes) {
    console.log(sgNode.getRoot().filename());
    const obj = sgNode.getMatch("OBJ")!;
    console.log(sgNode.range());
    console.log(obj.range());
     // THIS PRINTS CORRECT CODE:
    console.log(sgNode.text());
    // THIS PRINTS EITHER GARBAGE (text from some other file or some Chinese characters)
    // OR CRASHES (see the message below)
    console.log(obj.text());
  }
}
```

crash messages are like this:
```
thread '<unnamed>' panicked at crates/napi/src/doc.rs:95:36:
range end index 1768 out of range for slice of length 1349
```

# 🙁 Actual behavior

See comments in the code above

# 🙂 Expected behavior

The code above should print the correct source code.

**Comment by HerringtonDarkholme** [comment]
Can you also share the file you are scanning?

**Comment by HerringtonDarkholme** [comment]
There should be several ways to debug this issue:

1. it could be a concurrency issue. Can you reproduce it reliably? How many files are you scanning?
2. it could be a text encoding issue. Can you find the file you are using non-ascii code? 

You can try reduce the issue by deleting files in the repo and find the minimal reproduction.

**Comment by harrisonzhu-db** [comment]
running into a similar issue. i ran this on my codebase and got a crash similar to the above. 
I get a segfault when trying to `getMatch` an existing metavariable
```
import { tsx } from '@ast-grep/napi';

// this file will parse itself for simplicity lol

const funcWithArg = (arg: string) => arg;
funcWithArg('hello world');

async function main() {
  tsx.findInFiles({ paths: [__filename], matcher: { rule: { pattern: 'funcWithArg($KEY)' } } }, (err, results) => {
    if (err) {
      console.error(err);
      return;
    }
    results.forEach((result) => {
      console.log(`matched ${result.getMatch('NONEXISTENTKEY')?.text()}`);
      console.log(`matched ${result.getMatch('KEY')?.text()}`);
    });
  });
}

main();
```

This gives

```
❯ bin/test-ast-grep
matched undefined
[1]    48095 segmentation fault  bin/test-ast-grep
```

**Comment by harrisonzhu-db** [comment]
> @harrisonzhu-db would you like to provide a minimal reproduction? Usually it can be done by deleting scanned code.

the bug should be self-contained within the code I pasted - the script is using ast-grep to scan itself, so that should be all you need

**Comment by HerringtonDarkholme** [comment]
Thanks for the report. I found the root issue now.

**Comment by HerringtonDarkholme** [comment]
Fixed in main branch 

<img width="264" alt="image" src="https://github.com/user-attachments/assets/aa3b69bb-656c-4c17-8dc2-e5cf35fdbca6">

**Comment by harrisonzhu-db** [comment]
very awesome! thanks for this
