### ISSUE TITLE
[bug] when using --context=<num>, the context strings are not provided with --json=stream

### ISSUE THREAD

**Issue by MagicDuck** [ast-grep/ast-grep#1381]
Hi there, 

First of all thank you for this amazing tool!
I am integrating a neovim plugin, https://github.com/MagicDuck/grug-far.nvim with `ast-grep` and I've noticed that the streamed json (from `--json=stream`) does not contain context strings (see more below). 

# ⏯ Playground Link

not applicable

# 💻 Code

does not matter

Pattern:

does not matter

# 🙁 Actual behavior

running the following command:
```sh
sg run '--pattern=$A()' --context=2 ./tests/base/test_ui.lua
```
I get the match with context as normal:
```
tests/base/test_ui.lua
4│-- TODO (sbadragan): add tests for sg
5│---@type NeovimChild
6│local child = MiniTest.new_child_neovim()
7│
8│local T = MiniTest.new_set({
```

when adding the `--json=stream` flag though:
```sh
sg run '--pattern=$A()' --context=2 --json=stream ./tests/base/test_ui.lua | jq
```
I don't see any context strings to use:
```
{
  "text": "MiniTest.new_child_neovim()",
  "range": {
    "byteOffset": {
      "start": 161,
      "end": 188
    },
    "start": {
      "line": 5,
      "column": 14
    },
    "end": {
      "line": 5,
      "column": 41
    }
  },
  "file": "tests/base/test_ui.lua",
  "lines": "local child = MiniTest.new_child_neovim()",
  "language": "Lua",
  "metaVariables": {
    "single": {
      "A": {
        "text": "MiniTest.new_child_neovim",
        "range": {
          "byteOffset": {
            "start": 161,
            "end": 186
          },
          "start": {
            "line": 5,
            "column": 14
          },
          "end": {
            "line": 5,
            "column": 39
          }
        }
      }
    },
    "multi": {},
    "transformed": {}
  }
}
```

# 🙂 Expected behavior
Would expect context before and after strings to be in the streamed json

# Neovim Plugin in action if you are curious 
This functionality has not been merged yet at the time of posting this issue.
<img width="1090" alt="image" src="https://github.com/user-attachments/assets/a211a88a-45d8-45af-8a38-180df3bc5859">

**Comment by HerringtonDarkholme** [comment]
Hi @MagicDuck, thanks for building grug-far.nvim with ast-grep. 

> does not contain context strings

I can put context string in the `lines` field. Does that meet your requirements? 

I noticed you need to highlight the match string. One way to do that is:
1. read `lines` and split it into string array
2. find the matching lines by removing `context`
3. highlight the match by calculate the column

**Comment by HerringtonDarkholme** [comment]
btw, I would be more than happy if you would add grug-far.nvim in this page? https://ast-grep.github.io/guide/tools/editors.html#neovim 

Source is https://github.com/ast-grep/ast-grep.github.io/edit/main/website/guide/tools/editors.md here

**Comment by MagicDuck** [comment]
@HerringtonDarkholme thanks for the quick response! 😄 

I would say ideally the context string would go into 2 new json fields, something like `context_lines_after` and `context_lines_before`.
The problem with putting it in `lines` is that I would have to parse the context arguments (`-A`, `-B`, `C` and their other variants) specified by the user in the `Flags` input in order to figure out those numbers, so I know how much to take off of `lines`.
Alternatively, the number of context lines can be provided as part of json, I guess. That would work too...

> btw, I would be more than happy if you would add grug-far.nvim in this page? https://ast-grep.github.io/guide/tools/editors.html#neovim
will do in a bit when I merge this functionality!

**Comment by MagicDuck** [comment]
btw, don't mean to sound needy, but a `--glob=<pat>` flag same as `ripgrep` would also help in the future 😄 
Atm I am running `rg --files --glob=<pat>` to get a filtered down list of files which I then to pass on to `sg` in chunks.
It's definitely not the biggest issue since I have the workaround, but would be good to remove the need for `rg` there at some point.

see: https://github.com/ast-grep/ast-grep/issues/1062#issuecomment-2266388041

Thank you for you support! ❤️

**Comment by MagicDuck** [comment]
Created PR for adding it to integrations page 😄

**Comment by HerringtonDarkholme** [comment]
@MagicDuck implementation wise, ast-grep's DisplayContext has only leading/trailing, leading means the line content before the match and trailing means the content after match.

```ts
leading + match + trailing
e.g. suppose the match is `log`
console.log(abc)

leading: console.
match: log
trailing: (abc)
```


<img width="1087" alt="image" src="https://github.com/user-attachments/assets/630fe93c-10eb-4692-8e46-f48f88ab4097">

I'm shipping an alternative way to make it easier for plugin authors to separate `lines`.

**Comment by MagicDuck** [comment]
That works for me! Thank you so much! 😄

**Comment by MagicDuck** [comment]
Was a bit tricky to implement cause off by one errors in lua are unaviodable when it indexes everything starting with 1, but it worked 🥳 
Thank you for your support! 
<img width="1247" alt="image" src="https://github.com/user-attachments/assets/09d5ccbf-0978-4e58-a388-b71393d3e567">
