### ISSUE TITLE
[bug] Parentheses around yield statements

### ISSUE THREAD

**Issue by elbaro** [ast-grep/ast-grep#1398]
# 🙁 Actual behavior

Original code:
```py
function()
list(function())
return function()
```

Rewrite `function()` with `yield function()`:

```py
yield function()
list(yield function())  # invalid syntax
return yield function()  # invalid syntax
```

# 🙂 Expected behavior

To generate the correct AST, `yield ...` should be wrapped in extra parentheses.

```py
yield function()
list((yield function()))
return (yield function())
```

If the rewrite string is wrapped in (), ast-grep inserts () even in the plain yield statements.
These are not stripped by black.

```py
(yield function())
list((yield function()))
return (yield function())
```

**Comment by HerringtonDarkholme** [comment]
AST grep is not responsible for generating valid AST after rewrite. That means, you need to take care of if you need to add parentheses or semicolon. 

At the moment, there is no plan to support AST aware fix.
