### ISSUE TITLE
[bug] nested JSX elements won't be matched in CLI / NAPI

### ISSUE THREAD

**Issue by StevenLove** [ast-grep/ast-grep#1419]
# Overview
We expect to be able to match this pattern:
```
<StyledLink>$$$A</StyledLink>
```
In this sourcefile:
```
<div>
  <div>
    <StyledLink>hi</StyledLink>
  </div>

  <StyledLink>Styled, exciting Link</StyledLink>
</div>
```
1. It matches in the [playground](https://ast-grep.github.io/playground.html#eyJtb2RlIjoiUGF0Y2giLCJsYW5nIjoidHN4IiwicXVlcnkiOiI8U3R5bGVkTGluaz4kJCRBPC9TdHlsZWRMaW5rPiIsInJld3JpdGUiOiIiLCJzdHJpY3RuZXNzIjoic21hcnQiLCJzZWxlY3RvciI6IiIsImNvbmZpZyI6ImlkOiBuby11bnVzZWQtdmFyc1xucnVsZTpcbiAgICBraW5kOiBsb2NhbF92YXJpYWJsZV9kZWNsYXJhdGlvblxuICAgIGFsbDpcbiAgICAgICAgLSBoYXM6XG4gICAgICAgICAgICBoYXM6XG4gICAgICAgICAgICAgICAga2luZDogaWRlbnRpZmllclxuICAgICAgICAgICAgICAgIHBhdHRlcm46ICRJREVOVFxuICAgICAgICAtIG5vdDpcbiAgICAgICAgICAgIHByZWNlZGVzOlxuICAgICAgICAgICAgICAgIHN0b3BCeTogZW5kXG4gICAgICAgICAgICAgICAgaGFzOlxuICAgICAgICAgICAgICAgICAgICBzdG9wQnk6IGVuZFxuICAgICAgICAgICAgICAgICAgICBhbnk6XG4gICAgICAgICAgICAgICAgICAgICAgICAtIHsga2luZDogaWRlbnRpZmllciwgcGF0dGVybjogJElERU5UIH1cbiAgICAgICAgICAgICAgICAgICAgICAgIC0geyBoYXM6IHtraW5kOiBpZGVudGlmaWVyLCBwYXR0ZXJuOiAkSURFTlQsIHN0b3BCeTogZW5kfX1cbmZpeDogJydcbiIsInNvdXJjZSI6IjxkaXY+XG4gIDxkaXY+XG4gICAgPFN0eWxlZExpbms+aGk8L1N0eWxlZExpbms+XG4gIDwvZGl2PlxuXG4gIDxTdHlsZWRMaW5rPlN0eWxlZCwgZXhjaXRpbmcgTGluazwvU3R5bGVkTGluaz5cbjwvZGl2PlxuIn0=), with `smart` strictness ✅
2. It only matches in the CLI if we use `relaxed`, `ast`, or `signature` strictness ❓
3. It fails to match in NAPI ❌

Check out [this example repo](https://github.com/StevenLove/ast-grep-napi-examples/tree/main/jsx) to see more details and the exact NAPI file used.

# Comments

If the source file has whitespace removed so that it looks like this:
```
div><div><StyledLink>hi</StyledLink></div><StyledLink>Styled, exciting Link</StyledLink></div>
```
then we do get a match in the CLI running  `sg -p '<StyledLink>$$$A</StyledLink>'`. 

# Debug ASTs

## Pattern
`<StyledLink>$$$A</StyledLink>`
```
program (0,0)-(0,29)
  expression_statement (0,0)-(0,29)
    jsx_element (0,0)-(0,29)
      open_tag: jsx_opening_element (0,0)-(0,12)
        name: identifier (0,1)-(0,11)
      jsx_text (0,12)-(0,16)
      close_tag: jsx_closing_element (0,16)-(0,29)
        name: identifier (0,18)-(0,28)
```
## Source
same 7 line source file as above
```
program (0,0)-(7,0)
  expression_statement (0,0)-(6,6)
    jsx_element (0,0)-(6,6)
      open_tag: jsx_opening_element (0,0)-(0,5)
        name: identifier (0,1)-(0,4)
      jsx_element (0,5)-(3,8)
        open_tag: jsx_opening_element (0,5)-(1,7)
          name: identifier (1,3)-(1,6)
        jsx_element (1,7)-(2,31)
          open_tag: jsx_opening_element (1,7)-(2,16)
            name: identifier (2,5)-(2,15)
          jsx_text (2,16)-(2,18)
          close_tag: jsx_closing_element (2,18)-(2,31)
            name: identifier (2,20)-(2,30)
        close_tag: jsx_closing_element (2,31)-(3,8)
          name: identifier (3,4)-(3,7)
      jsx_element (3,8)-(5,48)
        open_tag: jsx_opening_element (3,8)-(5,14)
          name: identifier (5,3)-(5,13)
        jsx_text (5,14)-(5,35)
        close_tag: jsx_closing_element (5,35)-(5,48)
          name: identifier (5,37)-(5,47)
      close_tag: jsx_closing_element (5,48)-(6,6)
        name: identifier (6,2)-(6,5)
```

**Comment by HerringtonDarkholme** [comment]
Minimal reproduction:

Command 
```bash
sg -p '<StyledLink>hi</StyledLink>'
```

notWork.tsx
```tsx
<div>
  <StyledLink>hi</StyledLink>
</div>
```

work.tsx
```
<div> <StyledLink>hi</StyledLink>
</div>

```

-----------

The issue here is the newline. 

For a code like this

```
<div>
  <StyledLink>$B</StyledLink>
</div>
```

```
Debug CST:
program (0,0)-(2,6)
  expression_statement (0,0)-(2,6)
    jsx_element (0,0)-(2,6)
      open_tag: jsx_opening_element (0,0)-(0,5)
        < (0,0)-(0,1)
        name: identifier (0,1)-(0,4)
        > (0,4)-(0,5)
      jsx_element (0,5)-(1,29)
        open_tag: jsx_opening_element (0,5)-(1,14)
          < (0,5)-(1,3)               <------------------ note this spans two lines!!
          name: identifier (1,3)-(1,13)
          > (1,13)-(1,14)
        jsx_text (1,14)-(1,16)
        close_tag: jsx_closing_element (1,16)-(1,29)
          </ (1,16)-(1,18)
          name: identifier (1,18)-(1,28)
          > (1,28)-(1,29)
      close_tag: jsx_closing_element (1,29)-(2,6)
        </ (1,29)-(2,2)
        name: identifier (2,2)-(2,5)
        > (2,5)-(2,6)
```

I believe this is a tree-sitter parser issue

**Comment by HerringtonDarkholme** [comment]
See https://github.com/tree-sitter/tree-sitter-typescript/issues/306
