### ISSUE TITLE
[feature] YAML support

### ISSUE THREAD

**Issue by azu** [ast-grep/ast-grep#1436]
# ⭐ Suggestion

YAML language support.

- [List of Languages with Built-in Support | ast-grep](https://ast-grep.github.io/reference/languages.html)

# 💻 Use Cases

Yaml files are used as various configuration files.
e.g. ast-grep, Circle CI, GitHub Actions, k8s etc...

My main use case is to define custom Lint rules for a GitHub Actions workflow file.
My team has the following custom rules for GitHub Actions's workflow.

- Use `runs-on: {{ vars.RUNNER_DEFAULT }}` instead of `runs-on: ubuntu-latest`
- Set `concurrency:`
- Set `timeout-minutes:`
- Always pin the version of `use:`.

The main use case is to check this with CI and make sure it is followed as a rule.
[actionlint](https://github.com/rhysd/actionlint) and [ghalint](https://github.com/suzuki-shunsuke/ghalint) are linter for GitHub Actions, but these tools are not extensible.

Perhaps what I want to check can be done with existing `grep`, shellscript., but I think it would be appropriate to implement it with a tool like ast-grep for rule management and testing.

Also, I wanted YAML support, as it would probably also make it possible to test the ast-grep configuration file with ast-grep.

📝 [Semgrep](https://semgrep.dev/) support YAML.

- https://semgrep.dev/docs/writing-rules/rule-syntax#language-extensions-and-languages-key-values
- https://github.com/semgrep/semgrep?tab=readme-ov-file#language-support

**Comment by HerringtonDarkholme** [comment]
Thanks for the suggestion. Previously YAML is not included by default due to the lack of official parsers.

YAML parsers now have official support from tree-sitter. It is time to have it
 
https://github.com/tree-sitter-grammars/tree-sitter-yaml

**Comment by HerringtonDarkholme** [comment]
Looks like YAML parser is not well crafted :/ 
String content is lost in the parsed AST

<img width="957" alt="image" src="https://github.com/user-attachments/assets/cf84b80b-b22a-4006-a1d1-aa5371022fe2">

**Comment by anoblet** [comment]
I'm trying to use the YAML support, though the `@ast-grep/lang-yml` package cannot be found. Am I doing something wrong?

**Comment by HerringtonDarkholme** [comment]
@anoblet if you are using cli, just install `@ast-grep/cli`. YAML is bundled in the CLI.

`@ast-grep/langs` is for napi.rs extension if you want to use ast-grep in JavaScript programmatically. Currently it does not have a yaml package. https://github.com/ast-grep/langs/tree/main/packages

**Comment by anoblet** [comment]
I'm trying to parse YAML files with GenAIScript(https://github.com/microsoft/genaiscript). It looks like it's not supported currently. I was wondering if there was support in this package that didn't make it's way over to GenAIScript: https://github.com/microsoft/genaiscript/blob/43a53efb952c6afeb59f9ed9c2a04a7bd8ff6d17/packages/core/src/astgrep.ts#L264

Are you saying YAML is not supported currently with the NAPI extension? (Sorry if these are novice questions) :)

**Comment by HerringtonDarkholme** [comment]
YAML is not supported yet but it is not hard. You can submit a PR in the langs repo if you have time! https://github.com/ast-grep/langs?tab=readme-ov-file#scriptscreate-lang

Otherwise I will need weekend time for it.
