### ISSUE TITLE
[feature] match/exclude filenames for rules

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [ast-grep/ast-grep#1511]
# ⭐ Suggestion

with rules there currently seems to be no way to seelct/deselect 

rules were they apply, so rules are always for all matching files

# 💻 Use Cases

i want to create a python rule that forbids the use of `pytest.fixture(autouse=True)` outside of a `conftest.py` file
in order to prevent general pytest plugins shipped in codebases from accidentally adding global autouse fixtures

in order to do that i need a rule that matches on all python files that are not named  `conftest.py`

**Comment by HerringtonDarkholme** [comment]
I am not 100% sure if I understand your question but ast-grep rule has globbing options. https://ast-grep.github.io/guide/project/lint-rule.html#files-ignores

https://ast-grep.github.io/reference/yaml.html#globbing
