### ISSUE TITLE
Add bindings to make reports

### ISSUE THREAD

**Issue by RoketFlame** [ast-grep/ast-grep#1521]
# ⭐ Suggestion

Add bindings in python (and js) to output reports

# 💻 Use Cases

If someone uses python (or js) bindings, they don't have the option to make a report. You have to write your own solutions

**Comment by HerringtonDarkholme** [comment]
Hi thanks for the suggestion.

However, report is only for CLI and does not come well with API bindings. Reporting is mainly UI/UX and should not be included in a programmatic call. 
Your use case is probably to support writing rules in Py/JS or other programmatic stuff. 

ast-grep has the plan to support WASM based rule but it has no timeline for now.
