### ISSUE TITLE
[bug] Empty matches with Dart language

### ISSUE THREAD

**Issue by MicheleQuasar** [ast-grep/ast-grep#1523]
# ⏯ Playground Link
 
1. [playground link1]( https://ast-grep.github.io/playground.html#eyJtb2RlIjoiQ29uZmlnIiwibGFuZyI6ImRhcnQiLCJxdWVyeSI6IiRBKCQkJEIpIiwicmV3cml0ZSI6IkRlYnVnLmFzc2VydCIsInN0cmljdG5lc3MiOiJzbWFydCIsInNlbGVjdG9yIjoiIiwiY29uZmlnIjoiaWQ6IHN0cmluZ19saXRlcmFsX25vZGVzXG5sYW5ndWFnZTogZGFydFxucnVsZTpcbiAgcGF0dGVybjogXCIkQSgkQilcIlxuICAiLCJzb3VyY2UiOiJmaW5hbCBzID0gXCJUaGlzIGlzIGEgc3RyaW5nXCI7XG5cbnZvaWQgbWFpbigpIHtcbiAgLy8vIEEgbWFpbiBmdW5jdGlvbiB0aGF0IGRvZXMgc29tZSBraW5kIG9mIGNvbXB1dGF0aW9uXG4gIGZpbmFsIGkgPSAxICsgMjtcbiAgcHJpbnQoaSk7XG4gIHByaW50KFwiVGhpcyBpcyBhbm90aGVyIHN0cmluZyB1c2luZyBpbnRlcnBvbGF0aW9uICRpXCIpO1xuICBwcmludChmKFwibXkgc3RyaW5nIGluIGEgZnVuY3Rpb25cIikpO1xufVxuXG5TdHJpbmcgZihTdHJpbmcgYSkge1xuICBmaW5hbCBzID0gXCJcIlwiXG4gIFRoaXMgaXMgYSBtdWx0aS1saW5lIHN0cmluZ1wiXCJcIjtcbiAgZmluYWwgciA9IFwiXCJcIlxuICBBIG11bHRpLWxpbmUgc3RyaW5nIHdpdGggaW50ZXJwb2xhdGlvbiAkYVwiXCJcIjtcbiAgcmV0dXJuIFwiJHNcXG4kclwiO1xufVxuIn0=)
2. [playground link2](https://ast-grep.github.io/playground.html#eyJtb2RlIjoiQ29uZmlnIiwibGFuZyI6ImRhcnQiLCJxdWVyeSI6IiRBKCQkJEIpIiwicmV3cml0ZSI6IkRlYnVnLmFzc2VydCIsInN0cmljdG5lc3MiOiJzbWFydCIsInNlbGVjdG9yIjoiIiwiY29uZmlnIjoiaWQ6IHN0cmluZ19saXRlcmFsX25vZGVzXG5sYW5ndWFnZTogZGFydFxucnVsZTpcbiAgcGF0dGVybjogXCIkQVwiXG4gIGtpbmQ6IHN0cmluZ19saXRlcmFsXG4gICIsInNvdXJjZSI6ImZpbmFsIHMgPSBcIlRoaXMgaXMgYSBzdHJpbmdcIjtcblxudm9pZCBtYWluKCkge1xuICAvLy8gQSBtYWluIGZ1bmN0aW9uIHRoYXQgZG9lcyBzb21lIGtpbmQgb2YgY29tcHV0YXRpb25cbiAgZmluYWwgaSA9IDEgKyAyO1xuICBwcmludChpKTtcbiAgcHJpbnQoXCJUaGlzIGlzIGFub3RoZXIgc3RyaW5nIHVzaW5nIGludGVycG9sYXRpb24gJGlcIik7XG4gIHByaW50KGYoXCJteSBzdHJpbmcgaW4gYSBmdW5jdGlvblwiKSk7XG59XG5cblN0cmluZyBmKFN0cmluZyBhKSB7XG4gIGZpbmFsIHMgPSBcIlwiXCJcbiAgVGhpcyBpcyBhIG11bHRpLWxpbmUgc3RyaW5nXCJcIlwiO1xuICBmaW5hbCByID0gXCJcIlwiXG4gIEEgbXVsdGktbGluZSBzdHJpbmcgd2l0aCBpbnRlcnBvbGF0aW9uICRhXCJcIlwiO1xuICByZXR1cm4gXCIkc1xcbiRyXCI7XG59XG4ifQ==)

# 💻 Code

```dart
final s = "This is a string";

void main() {
  /// A main function that does some kind of computation
  final i = 1 + 2;
  print(i);
  print("This is another string using interpolation $i");
  print(f("my string in a function"));
}

String f(String a) {
  final s = """
  This is a multi-line string""";
  final r = """
  A multi-line string with interpolation $a""";
  return "$s\n$r";
}
```

Pattern:
Pattern 1
```yml
id: string_literal_nodes
language: dart
rule:
  pattern: "$A($B)"
```
Pattern 2
```yml
id: string_literal_nodes
language: dart
rule:
  pattern: "$A"
  kind: string_literal
```

# Additional environment info

Since dart is not one of the officially supported languages I am using the following config file to enable it:
```yaml
ruleDirs:
- ./rules
customLanguages:
  dart:
    libraryPath: dart.so
    extensions: [dart]
```

I have tried using the `dart.so` library downloaded by nvim-treesitter and also compiling the library from source. Both give the same results.

# 🙁 Actual behavior

In the playground everything works as expected, the first pattern matches function applications, while the second matches all string literals in the provided example.

Using the cli with the following command:
```bash
sg scan -r <path_to_rule>.yml --json=pretty <path_to_file>.dart
```
in both cases returns an empty list `[]`

Have also tried with
```bash
sg -p "$A($B)" <path_to_file>.dart
```
```bash
sg -p "$A" --selector=string_literal <path_to_file>.dart
```
which should be equivalent to the two `yml` provided, with the same results.

For reference, using the `sg run` command I can only match the pattern `$A`, which matches the whole file, as soon as I add any other element to the pattern the returned matches are empty.

Tested both on windows and WSL Ubuntu 22.04LTS

# 🙂 Expected behavior

Return lists with 3 matches in the first case and 6 in the second, matching the behavior of the playground.

**Note**: The issue seems to be with the dart language, when translating the above examples to javascript the behavior is as intended and matches between playground and local install. This makes me think it is an issue with my setup for dart.

# Dump of `tree-sitter parse <path_to_file>.dart`

For reference here is a dump of the tree-sitter tree, run using the same version of `dart.so` used by sg for the tests.
Not sure if this is relevant but this does NOT match perfectly with the tree shown in the playground for the same code. I can find the same nodes at the same positions in the file but the tree shown in the playground seems to have more nodes. (Not sure if this is due to the difference AST vs CST and what `tree-sitter parse` gives out is an AST).

```
(program [0, 0] - [17, 0]
  (final_builtin [0, 0] - [0, 5])
  (static_final_declaration_list [0, 6] - [0, 28]
    (static_final_declaration [0, 6] - [0, 28]
      (identifier [0, 6] - [0, 7])
      (string_literal [0, 10] - [0, 28])))
  (function_signature [2, 0] - [2, 11]
    (void_type [2, 0] - [2, 4])
    name: (identifier [2, 5] - [2, 9])
    (formal_parameter_list [2, 9] - [2, 11]))
  (function_body [2, 12] - [8, 1]
    (block [2, 12] - [8, 1]
      (documentation_comment [3, 2] - [3, 57])
      (local_variable_declaration [4, 2] - [4, 18]
        (initialized_variable_definition [4, 2] - [4, 17]
          (final_builtin [4, 2] - [4, 7])
          name: (identifier [4, 8] - [4, 9])
          value: (additive_expression [4, 12] - [4, 17]
            (decimal_integer_literal [4, 12] - [4, 13])
            (additive_operator [4, 14] - [4, 15])
            (decimal_integer_literal [4, 16] - [4, 17]))))
      (expression_statement [5, 2] - [5, 11]
        (identifier [5, 2] - [5, 7])
        (selector [5, 7] - [5, 10]
          (argument_part [5, 7] - [5, 10]
            (arguments [5, 7] - [5, 10]
              (argument [5, 8] - [5, 9]
                (identifier [5, 8] - [5, 9]))))))
      (expression_statement [6, 2] - [6, 57]
        (identifier [6, 2] - [6, 7])
        (selector [6, 7] - [6, 56]
          (argument_part [6, 7] - [6, 56]
            (arguments [6, 7] - [6, 56]
              (argument [6, 8] - [6, 55]
                (string_literal [6, 8] - [6, 55]
                  (template_substitution [6, 52] - [6, 54]
                    (identifier_dollar_escaped [6, 53] - [6, 54]))))))))
      (expression_statement [7, 2] - [7, 38]
        (identifier [7, 2] - [7, 7])
        (selector [7, 7] - [7, 37]
          (argument_part [7, 7] - [7, 37]
            (arguments [7, 7] - [7, 37]
              (argument [7, 8] - [7, 36]
                (identifier [7, 8] - [7, 9])
                (selector [7, 9] - [7, 36]
                  (argument_part [7, 9] - [7, 36]
                    (arguments [7, 9] - [7, 36]
                      (argument [7, 10] - [7, 35]
                        (string_literal [7, 10] - [7, 35]))))))))))))
  (function_signature [10, 0] - [10, 18]
    (type_identifier [10, 0] - [10, 6])
    name: (identifier [10, 7] - [10, 8])
    (formal_parameter_list [10, 8] - [10, 18]
      (formal_parameter [10, 9] - [10, 17]
        (type_identifier [10, 9] - [10, 15])
        name: (identifier [10, 16] - [10, 17]))))
  (function_body [10, 19] - [16, 1]
    (block [10, 19] - [16, 1]
      (local_variable_declaration [11, 2] - [12, 33]
        (initialized_variable_definition [11, 2] - [12, 32]
          (final_builtin [11, 2] - [11, 7])
          name: (identifier [11, 8] - [11, 9])
          value: (string_literal [11, 12] - [12, 32])))
      (local_variable_declaration [13, 2] - [14, 47]
        (initialized_variable_definition [13, 2] - [14, 46]
          (final_builtin [13, 2] - [13, 7])
          name: (identifier [13, 8] - [13, 9])
          value: (string_literal [13, 12] - [14, 46]
            (template_substitution [14, 41] - [14, 43]
              (identifier_dollar_escaped [14, 42] - [14, 43])))))
      (return_statement [15, 2] - [15, 18]
        (string_literal [15, 9] - [15, 17]
          (template_substitution [15, 10] - [15, 12]
            (identifier_dollar_escaped [15, 11] - [15, 12]))
          (escape_sequence [15, 12] - [15, 14])
          (template_substitution [15, 14] - [15, 16]
            (identifier_dollar_escaped [15, 15] - [15, 16])))))))
```

**Comment by HerringtonDarkholme** [comment]
Hi! Thanks for the detailed report. Note the dart tree-sitter on playground can be VERY different from CLI. 

Would you like to follow this instruction to debug CLI parsing? https://ast-grep.github.io/advanced/faq.html#cli-and-playground-produce-different-results-why

**Comment by HerringtonDarkholme** [comment]
I can find the pattern with builtin dart language, not the tree-sitter one
<img width="740" alt="image" src="https://github.com/user-attachments/assets/869b5eb1-201d-46c6-a142-9bdb663b5014">

**Comment by MicheleQuasar** [comment]
Can confirm on my part that the builtin support works (tried on my personal linux machine, can't confirm on windows over the weekend).
I completely missed the fact that dart is included as a supported language out of the box, I stopped at the table in the docs home page, completely missed the link to the page with the languages with builtin support via tree-sitter and went straight for the custom language support option.
Honestly this solves my issue, I don't think I need to be on the latest version of the parser. Sorry for wasting your time.
In any case, if you are interested in understanding why the results are different between the built-in parser and the custom language option I can try and do some more troubleshooting.

**Comment by HerringtonDarkholme** [comment]
@MicheleQuasar would you like to help debugging the output of this one using custom language?

```bash
sg run -p '$A($$$B)' -l dart --debug-query=pattern
```

>  completely missed the link to the page with the languages with builtin support 

Sadly, the tree-sitter-dart used in ast-grep is not maintained by official community and is actually a fork of mine. https://github.com/ast-grep/tree-sitter-dart

> I don't think I need to be on the latest version of the parser. 
 
The issue of my fork is that it changed a lot from the original tree-sitter-dart. 

Also, since my fork is poorly maintained, I am considering removing builtin dart support for the following releases. So I appreciate if you can help debugging the output of tree-sitter.

**Comment by MicheleQuasar** [comment]
I've done some more digging and I'm a bit confused.
Since none of the patterns I have tried with the external language support for dart has worked, I started with something simple: I'm trying the pattern `$A+$B`.
I've downloaded and built tree-sitter parsers both for the official version of `tree-sitter-dart` as well as your fork so that I can compare the parsed pattern with the parsed syntax tree with the same version of the parsing library.
Also I've built the latest version of `tree-sitter-cli` which includes an option for `tree-sitter parse` to output a CST.
The results of this investigation don't make much sense to me.

# Builtin parser

Config used
![image](https://github.com/user-attachments/assets/cd236991-7d13-441a-b8db-8d1db824284c)
The parsed pattern looks like this
![image](https://github.com/user-attachments/assets/744181a2-cd07-43c8-8470-f54f1376952c)
and the corresponding section of the CST is
![image](https://github.com/user-attachments/assets/39376494-bc72-40ba-885f-529f7710d6c5)

All good on in this case

# External language support

Config used
![image](https://github.com/user-attachments/assets/f5378546-aa79-41e6-bb12-da6d3ce1b299)
The parsed pattern looks identical to the builtin one
![image](https://github.com/user-attachments/assets/a60c42ac-210b-4164-8955-ea6d4cf5dbd7)
same for the CST
![image](https://github.com/user-attachments/assets/6dc448a8-1970-49aa-a052-9754bd7fb3cf)

However in this case the search results are empty.

I'm attaching the two CST in case there is something elsewhere that might be preventing the match that I'm missing. But reading through the docs, it looks like matches for a pattern this simple should be local and the global structure of the code should not prevent a match.

# Builtin CST
```
0:0   - 17:0    program
0:0   - 0:29      local_variable_declaration
0:0   - 0:28        initialized_variable_definition
0:0   - 0:5           final_builtin
0:0   - 0:5             `final`
0:6   - 0:7           name: identifier
0:6   - 0:1             `s`
0:8   - 0:9           "="
0:10  - 0:28          value: string_literal
0:10  - 0:11            """
0:27  - 0:28            """
0:28  - 0:29        ";"
2:0   - 8:1       lambda_expression
2:0   - 2:11        parameters: function_signature
2:0   - 2:4           void_type
2:0   - 2:4             `void`
2:5   - 2:9           name: identifier
2:5   - 2:4             `main`
2:9   - 2:11          formal_parameter_list
2:9   - 2:10            "("
2:10  - 2:11            ")"
2:12  - 8:1         body: function_body
2:12  - 8:1           block
2:12  - 2:13            "{"
3:2   - 3:56            documentation_comment
3:2   - 3:5               "///"
4:2   - 4:18            local_variable_declaration
4:2   - 4:17              initialized_variable_definition
4:2   - 4:7                 final_builtin
4:2   - 4:5                   `final`
4:8   - 4:9                 name: identifier
4:8   - 4:1                   `i`
4:10  - 4:11                "="
4:12  - 4:17                value: additive_expression
4:12  - 4:13                  decimal_integer_literal
4:12  - 4:1                     `1`
4:14  - 4:15                  additive_operator
4:14  - 4:1                     `+`
4:16  - 4:17                  decimal_integer_literal
4:16  - 4:1                     `2`
4:17  - 4:18              ";"
5:2   - 5:11            expression_statement
5:2   - 5:10              member_access
5:2   - 5:7                 identifier
5:2   - 5:5                   `print`
5:7   - 5:10                selector
5:7   - 5:10                  argument_part
5:7   - 5:10                    arguments
5:7   - 5:8                       "("
5:8   - 5:9                       argument
5:8   - 5:9                         identifier
5:8   - 5:1                           `i`
5:9   - 5:10                      ")"
5:10  - 5:11              ";"
6:2   - 6:57            expression_statement
6:2   - 6:56              member_access
6:2   - 6:7                 identifier
6:2   - 6:5                   `print`
6:7   - 6:56                selector
6:7   - 6:56                  argument_part
6:7   - 6:56                    arguments
6:7   - 6:8                       "("
6:8   - 6:55                      argument
6:8   - 6:55                        string_literal
6:8   - 6:9                           """
6:52  - 6:54                          template_substitution
6:52  - 6:53                            "$"
6:53  - 6:54                            identifier_dollar_escaped
6:53  - 6:1                               `i`
6:54  - 6:55                          """
6:55  - 6:56                      ")"
6:56  - 6:57              ";"
7:2   - 7:38            expression_statement
7:2   - 7:37              member_access
7:2   - 7:7                 identifier
7:2   - 7:5                   `print`
7:7   - 7:37                selector
7:7   - 7:37                  argument_part
7:7   - 7:37                    arguments
7:7   - 7:8                       "("
7:8   - 7:36                      argument
7:8   - 7:36                        member_access
7:8   - 7:9                           identifier
7:8   - 7:1                             `f`
7:9   - 7:36                          selector
7:9   - 7:36                            argument_part
7:9   - 7:36                              arguments
7:9   - 7:10                                "("
7:10  - 7:35                                argument
7:10  - 7:35                                  string_literal
7:10  - 7:11                                    """
7:34  - 7:35                                    """
7:35  - 7:36                                ")"
7:36  - 7:37                      ")"
7:37  - 7:38              ";"
8:0   - 8:1             "}"
10:0  - 16:1      lambda_expression
10:0  - 10:18       parameters: function_signature
10:0  - 10:6          type_identifier
10:0  - 10:6            `String`
10:7  - 10:8          name: identifier
10:7  - 10:1            `f`
10:8  - 10:18         formal_parameter_list
10:8  - 10:9            "("
10:9  - 10:17           formal_parameter
10:9  - 10:15             type_identifier
10:9  - 10:6                `String`
10:16 - 10:17             name: identifier
10:16 - 10:1                `a`
10:17 - 10:18           ")"
10:19 - 16:1        body: function_body
10:19 - 16:1          block
10:19 - 10:20           "{"
11:2  - 12:33           local_variable_declaration
11:2  - 12:32             initialized_variable_definition
11:2  - 11:7                final_builtin
11:2  - 11:5                  `final`
11:8  - 11:9                name: identifier
11:8  - 11:1                  `s`
11:10 - 11:11               "="
11:12 - 12:32               value: string_literal
11:12 - 11:15                 """""
12:29 - 12:32                 """""
12:32 - 12:33             ";"
13:2  - 14:47           local_variable_declaration
13:2  - 14:46             initialized_variable_definition
13:2  - 13:7                final_builtin
13:2  - 13:5                  `final`
13:8  - 13:9                name: identifier
13:8  - 13:1                  `r`
13:10 - 13:11               "="
13:12 - 14:46               value: string_literal
13:12 - 13:15                 """""
14:41 - 14:43                 template_substitution
14:41 - 14:42                   "$"
14:42 - 14:43                   identifier_dollar_escaped
14:42 - 14:1                      `a`
14:43 - 14:46                 """""
14:46 - 14:47             ";"
15:2  - 15:18           return_statement
15:2  - 15:8              "return"
15:9  - 15:17             string_literal
15:9  - 15:10               """
15:10 - 15:12               template_substitution
15:10 - 15:11                 "$"
15:11 - 15:12                 identifier_dollar_escaped
15:11 - 15:1                    `s`
15:12 - 15:14               escape_sequence
15:12 - 15:2                  `\\n`
15:14 - 15:16               template_substitution
15:14 - 15:15                 "$"
15:15 - 15:16                 identifier_dollar_escaped
15:15 - 15:1                    `r`
15:16 - 15:17               """
15:17 - 15:18             ";"
16:0  - 16:1            "}"
```

# External language support CST
```
0:0   - 17:0    program
0:0   - 0:5       final_builtin
0:0   - 0:5         "final"
0:6   - 0:28      static_final_declaration_list
0:6   - 0:28        static_final_declaration
0:6   - 0:7           identifier
0:6   - 0:1             `s`
0:8   - 0:9           "="
0:10  - 0:28          string_literal
0:10  - 0:11            """
0:27  - 0:28            """
0:28  - 0:29      ";"
2:0   - 2:11      function_signature
2:0   - 2:4         void_type
2:0   - 2:4           `void`
2:5   - 2:9         name: identifier
2:5   - 2:4           `main`
2:9   - 2:11        formal_parameter_list
2:9   - 2:10          "("
2:10  - 2:11          ")"
2:12  - 8:1       function_body
2:12  - 8:1         block
2:12  - 2:13          "{"
3:2   - 3:56          documentation_comment
3:2   - 3:5             "///"
4:2   - 4:18          local_variable_declaration
4:2   - 4:17            initialized_variable_definition
4:2   - 4:7               final_builtin
4:2   - 4:7                 "final"
4:8   - 4:9               name: identifier
4:8   - 4:1                 `i`
4:10  - 4:11              "="
4:12  - 4:17              value: additive_expression
4:12  - 4:13                decimal_integer_literal
4:12  - 4:1                   `1`
4:14  - 4:15                additive_operator
4:14  - 4:1                   `+`
4:16  - 4:17                decimal_integer_literal
4:16  - 4:1                   `2`
4:17  - 4:18            ";"
5:2   - 5:11          expression_statement
5:2   - 5:7             identifier
5:2   - 5:5               `print`
5:7   - 5:10            selector
5:7   - 5:10              argument_part
5:7   - 5:10                arguments
5:7   - 5:8                   "("
5:8   - 5:9                   argument
5:8   - 5:9                     identifier
5:8   - 5:1                       `i`
5:9   - 5:10                  ")"
5:10  - 5:11            ";"
6:2   - 6:57          expression_statement
6:2   - 6:7             identifier
6:2   - 6:5               `print`
6:7   - 6:56            selector
6:7   - 6:56              argument_part
6:7   - 6:56                arguments
6:7   - 6:8                   "("
6:8   - 6:55                  argument
6:8   - 6:55                    string_literal
6:8   - 6:9                       """
6:52  - 6:54                      template_substitution
6:52  - 6:53                        "$"
6:53  - 6:54                        identifier_dollar_escaped
6:53  - 6:1                           `i`
6:54  - 6:55                      """
6:55  - 6:56                  ")"
6:56  - 6:57            ";"
7:2   - 7:38          expression_statement
7:2   - 7:7             identifier
7:2   - 7:5               `print`
7:7   - 7:37            selector
7:7   - 7:37              argument_part
7:7   - 7:37                arguments
7:7   - 7:8                   "("
7:8   - 7:36                  argument
7:8   - 7:9                     identifier
7:8   - 7:1                       `f`
7:9   - 7:36                    selector
7:9   - 7:36                      argument_part
7:9   - 7:36                        arguments
7:9   - 7:10                          "("
7:10  - 7:35                          argument
7:10  - 7:35                            string_literal
7:10  - 7:11                              """
7:34  - 7:35                              """
7:35  - 7:36                          ")"
7:36  - 7:37                  ")"
7:37  - 7:38            ";"
8:0   - 8:1           "}"
10:0  - 10:18     function_signature
10:0  - 10:6        type_identifier
10:0  - 10:6          `String`
10:7  - 10:8        name: identifier
10:7  - 10:1          `f`
10:8  - 10:18       formal_parameter_list
10:8  - 10:9          "("
10:9  - 10:17         formal_parameter
10:9  - 10:15           type_identifier
10:9  - 10:6              `String`
10:16 - 10:17           name: identifier
10:16 - 10:1              `a`
10:17 - 10:18         ")"
10:19 - 16:1      function_body
10:19 - 16:1        block
10:19 - 10:20         "{"
11:2  - 12:33         local_variable_declaration
11:2  - 12:32           initialized_variable_definition
11:2  - 11:7              final_builtin
11:2  - 11:7                "final"
11:8  - 11:9              name: identifier
11:8  - 11:1                `s`
11:10 - 11:11             "="
11:12 - 12:32             value: string_literal
11:12 - 11:15               """""
12:29 - 12:32               """""
12:32 - 12:33           ";"
13:2  - 14:47         local_variable_declaration
13:2  - 14:46           initialized_variable_definition
13:2  - 13:7              final_builtin
13:2  - 13:7                "final"
13:8  - 13:9              name: identifier
13:8  - 13:1                `r`
13:10 - 13:11             "="
13:12 - 14:46             value: string_literal
13:12 - 13:15               """""
14:41 - 14:43               template_substitution
14:41 - 14:42                 "$"
14:42 - 14:43                 identifier_dollar_escaped
14:42 - 14:1                    `a`
14:43 - 14:46               """""
14:46 - 14:47           ";"
15:2  - 15:18         return_statement
15:2  - 15:8            "return"
15:9  - 15:17           string_literal
15:9  - 15:10             """
15:10 - 15:12             template_substitution
15:10 - 15:11               "$"
15:11 - 15:12               identifier_dollar_escaped
15:11 - 15:1                  `s`
15:12 - 15:14             escape_sequence
15:12 - 15:2                `\\n`
15:14 - 15:16             template_substitution
15:14 - 15:15               "$"
15:15 - 15:16               identifier_dollar_escaped
15:15 - 15:1                  `r`
15:16 - 15:17             """
15:17 - 15:18           ";"
16:0  - 16:1          "}"
```

**Comment by HerringtonDarkholme** [comment]
@MicheleQuasar I am suspecting if it is caused by the conflicting name of "dart". Can you rename the language name to something else? Also the file extension name should be changed

**Comment by MicheleQuasar** [comment]
That's at least part of the problem, I changed the language name from dart to drt and now I'm seeing different results with the two different parsers.
Another part of the problems seems to be that the official tree-sitter-dart parser is quite bad at parsing incomplete code snippets like the ones used in an ast-grep pattern.
I tried with addition and function application and it seems that if I don't supply a complete dart expression the parser just returns garbage output.

# Addition
## Incomplete expression
Parsed file:
```
a + b
```
parse result
![image](https://github.com/user-attachments/assets/0fc226e6-931f-4af2-b2c5-3190537df5bd)
## Complete expression
Parsed file:
```
final c = a + b;
```
parse result
![image](https://github.com/user-attachments/assets/f4250148-a059-49da-a4c9-e58c4892ea11)
 
# Function application
## Incomplete expression
Parsed file
```
f(a)
```
parse result
![image](https://github.com/user-attachments/assets/2999e347-b855-4954-b4d2-085a67de63fa)
## Complete expression
Parsed file
```
final b = f(a);
```
parse result
![image](https://github.com/user-attachments/assets/f73d7632-52ef-45c2-9d99-5687d3e45b55)

# Pattern debug
In addition to the problems above with parsing incomplete expression, it appears also that ast-grep fails to correctly build the pattern from the parsed expression
## Addition
![image](https://github.com/user-attachments/assets/0793395f-906f-49b9-b410-926b8b14eb20)
## Function application
![image](https://github.com/user-attachments/assets/6c1d301c-1fa4-4efe-b38d-6db48e22e4fc)

# Built-in parser

None of these problems appear with the builtin parser.
## Partial expression parsing
### Addition
Parsed file
```
a + b
```
parse result
![image](https://github.com/user-attachments/assets/31a576ff-48db-4a80-94d8-181fe0c0713b)
### Function application
Parsed file
```
f(a)
```
parse result
![image](https://github.com/user-attachments/assets/afebf0b9-7bc8-417a-abca-6ff2ab631958)
## Patterns
See any of the examples in my previous comments.

# Next steps
Not completely sure where to go from here.
It seems clear to me that at least part of the problem is due to tree-sitter-dart being unable to parse partial code fragments.
On the other hand, even when using patterns that can be correctly parsed these are not converted correctly to a pattern by ast-grep. So it seems there could be some issue there as well?
I'm afraid my lack of experience with both tree-sitter and rust  prevents me from having any more meaningful insight.
