### ISSUE TITLE
[feature] Warn or error out when a file inclusion or exclusion search glob does not match anything

### ISSUE THREAD

**Issue by PaulDance** [ast-grep/ast-grep#1531]
# ⭐ Suggestion

Whenever a file path search glob included in either the `files` or `ignores` objects does not match any file, at least a warning should be emitted in the output. Having a way to configure the severity of the trigger from the CLI would also be nice.

# 💻 Use Cases

This would be as a complement to #1530. When writing a rule or updating Ast-Grep that changes how such globs are treated, a small mistake can happen and currently would render some file discovery ineffective in a completely silent way. Having the tool warn us about it would improve the user experience quite a bit I think, as I remember struggling a lot with how the rule file discovery works. The CLI part would be to be able to either turn it off entirely or make it a hard error so it could be enforced in CI more easily than checking the output length.

**Comment by PaulDance** [comment]
Just tested it and it works great! In particular, the formatting used should make it easy to consume in automated tasks, for example during CI. Thanks a bunch!

**Comment by HerringtonDarkholme** [comment]
Thank for your kind word! If you are interested, you can also see the EBNF format for the tracing output https://github.com/ast-grep/ast-grep/issues/1574
