### ISSUE TITLE
[bug] Inconsistent behavior with CLI and playground

### ISSUE THREAD

**Issue by Goose97** [ast-grep/ast-grep#1534]
### Please read the FAQ for the bug you encountered.

- [X] I have read the existing FAQ

### ⏯ Playground Link

https://ast-grep.github.io/playground.html#eyJtb2RlIjoiUGF0Y2giLCJsYW5nIjoidHN4IiwicXVlcnkiOiI8QnV0dG9uICQkJCB2YXJpYW50PVwicHJpbWFyeVwiICQkJD5NZW51PC9CdXR0b24+IiwicmV3cml0ZSI6IiIsInN0cmljdG5lc3MiOiJzbWFydCIsInNlbGVjdG9yIjoiIiwiY29uZmlnIjoiIyBZQU1MIFJ1bGUgaXMgbW9yZSBwb3dlcmZ1bCFcbiMgaHR0cHM6Ly9hc3QtZ3JlcC5naXRodWIuaW8vZ3VpZGUvcnVsZS1jb25maWcuaHRtbCNydWxlXG5ydWxlOlxuICBhbnk6XG4gICAgLSBwYXR0ZXJuOiBjb25zb2xlLmxvZygkQSlcbiAgICAtIHBhdHRlcm46IGNvbnNvbGUuZGVidWcoJEEpXG5maXg6XG4gIGxvZ2dlci5sb2coJEEpIiwic291cmNlIjoiPEJ1dHRvbiB2YXJpYW50PVwicHJpbWFyeVwiPlxuICBNZW51XG48L0J1dHRvbj4ifQ==

### 💻 Code

Run this command in shell:
```sh
cat <<EOF | sg run --pattern '<Button $$$ variant="primary" $$$>Menu</Button>' --lang tsx --stdin
  <Button variant="primary">
    Menu
  </Button>
EOF
```

If squash the input into a single line, it works tho:

```sh
cat <<EOF | sg run --pattern '<Button $$$ variant="primary" $$$>Menu</Button>' --lang tsx --stdin
  <Button variant="primary">Menu</Button>
EOF
```

### 🙁 Actual behavior

No match found

### 🙂 Expected behavior

It should find 1 match

### Additional information about the issue

Version: ast-grep 0.28.0

**Comment by HerringtonDarkholme** [comment]
> Please read the FAQ for the bug you encountered.

https://ast-grep.github.io/advanced/faq.html#cli-and-playground-produce-different-results-why

<img width="754" alt="image" src="https://github.com/user-attachments/assets/00e19455-ce10-45ef-8482-9a4274583b86">
