### ISSUE TITLE
[bug] Very counter intuitive behavior with `all`

### ISSUE THREAD

**Issue by RoketFlame** [ast-grep/ast-grep#1580]
### Please read the FAQ for the bug you encountered.

- [X] I have read the existing FAQ

### ⏯ Playground Link

https://ast-grep.github.io/playground.html#eyJtb2RlIjoiQ29uZmlnIiwibGFuZyI6InB5dGhvbiIsInF1ZXJ5IjoiY29uc29sZS5sb2coJE1BVENIKSIsInJld3JpdGUiOiJsb2dnZXIubG9nKCRNQVRDSCkiLCJzdHJpY3RuZXNzIjoic21hcnQiLCJzZWxlY3RvciI6IiIsImNvbmZpZyI6ImlkOiBmdW5jLXBhcmFtXG5sYW5ndWFnZTogcHl0aG9uXG5ydWxlOlxuICBraW5kOiBmdW5jdGlvbl9kZWZpbml0aW9uXG4gIGFsbDpcbiAgICAtIGhhczpcbiAgICAgICAga2luZDogcGFyYW1ldGVyc1xuICAgICAgICBoYXM6XG4gICAgICAgICAga2luZDogdHlwZWRfcGFyYW1ldGVyXG4gICAgICAgICAgaGFzOlxuICAgICAgICAgICAga2luZDogaWRlbnRpZmllclxuICAgICAgICAgICAgcGF0dGVybjogJFBBUkFNXG4gICAgLSBoYXM6XG4gICAgICAgIGZpZWxkOiBib2R5XG4gICAgICAgIGhhczpcbiAgICAgICAgICBraW5kOiBleHByZXNzaW9uX3N0YXRlbWVudFxuICAgICAgICAgIGhhczpcbiAgICAgICAgICAgIGtpbmQ6IGFzc2lnbm1lbnRcbiAgICAgICAgICAgIGhhczpcbiAgICAgICAgICAgICAgZmllbGQ6IHJpZ2h0XG4gICAgICAgICAgICAgIGhhczpcbiAgICAgICAgICAgICAgICBmaWVsZDogb2JqZWN0XG4gICAgICAgICAgICAgICAgcGF0dGVybjogJFBBUkFNXG4tLS1cbmlkOiBmdW5jLXBhcmFtLW5vLWFsbFxubGFuZ3VhZ2U6IHB5dGhvblxudXRpbHM6XG4gIGNvbnN0cmFpbnM6XG4gICAga2luZDogZnVuY3Rpb25fZGVmaW5pdGlvblxuICAgIGhhczpcbiAgICAgIGZpZWxkOiBib2R5XG4gICAgICBoYXM6XG4gICAgICAgIGtpbmQ6IGV4cHJlc3Npb25fc3RhdGVtZW50XG4gICAgICAgIGhhczpcbiAgICAgICAgICBraW5kOiBhc3NpZ25tZW50XG4gICAgICAgICAgaGFzOlxuICAgICAgICAgICAgZmllbGQ6IHJpZ2h0XG4gICAgICAgICAgICBoYXM6XG4gICAgICAgICAgICAgIGZpZWxkOiBvYmplY3RcbiAgICAgICAgICAgICAgcGF0dGVybjogJFBBUkFNXG5cbnJ1bGU6XG4gIGtpbmQ6IGZ1bmN0aW9uX2RlZmluaXRpb25cbiAgaGFzOlxuICAgIGtpbmQ6IHBhcmFtZXRlcnNcbiAgICBoYXM6XG4gICAgICBraW5kOiB0eXBlZF9wYXJhbWV0ZXJcbiAgICAgIGhhczpcbiAgICAgICAga2luZDogaWRlbnRpZmllclxuICAgICAgICBwYXR0ZXJuOiAkUEFSQU1cbiAgICBpbnNpZGU6XG4gICAgICBtYXRjaGVzOiBjb25zdHJhaW5zXG4gICAgICAgICAgICBcbiIsInNvdXJjZSI6ImRlZiBmb28oYmFyOiBCYXIsIGJhejogQmF6LCBmYWE6IEZhYSk6XG4gICAgcHJpbnQoNDIpXG4gICAgXyA9IGJhei5uYW1lIn0=

### 💻 Code

```python
def foo(bar: Bar, baz: Baz, faa: Faa):
    print(42)
    _ = baz.name
```

### 🙁 Actual behavior

Function definition matches only with second rule, without `all`

### 🙂 Expected behavior

Function definition should match with both rules

### Additional information about the issue

This is very strange behavior. The documentation says that using `all` to capture metavariables can fix some bugs. However, in practice it doesn't work quite as expected. My understanding is that if `all` is used, the `$PARAM` metavariable will only capture `bar` since it is the first node in `parameters`. Apparently this is because `all` guarantees the order of execution. The first example of the rule (without `all`) looks much more concise and readable, although it is impossible to rewrite it so that it works. I would like to get some comments on this example, and perhaps a solution

**Comment by HerringtonDarkholme** [comment]
This is expected. 

https://ast-grep.github.io/guide/rule-config/composite-rule.html#all-and-any-refers-to-rules-not-nodes

> An ast-grep rule tests one node at a time, independently.

First, the `func-param` rule will match `function_definition`. Then it tries to match the two `all` clauses.

When the first $PARAM matches, it will match `bar` and assign it to the metavar `$PARAM`.

<img width="269" alt="image" src="https://github.com/user-attachments/assets/28b14c3f-fd39-4ac1-be09-8f63c269c821">

This is why the later body call is not matching. 

<img width="295" alt="image" src="https://github.com/user-attachments/assets/8bf07f23-8f39-4fb1-8f72-f61785fd167b">


Again,every ast-grep rule runs independently and does not back-track. For the behavior you want, it requires the first all rule matches multiple instances like `bar`, `baz`, `faa`. And then matching all possible instances with the `body` call. This will be an exponential behavior that is too slow. 


The second rule you write is perfect and manually opts-in the more complicated searching behavior.

**Comment by RoketFlame** [comment]
Thank you for your reply
