### ISSUE TITLE
[bug] Error installing ast-grep-py in python version 3.13

### ISSUE THREAD

**Issue by AraCoders** [ast-grep/ast-grep#1586]
### Please read the FAQ for the bug you encountered.

- [X] I have read the existing FAQ

### ⏯ Playground Link

https://ast-grep.github.io/playground/?

### 💻 Code

I was using ast-grep-py with python3.12 flawlessly, once i updated to 3.13 and tried to install ast-grep-py, the following error happens during compilation:
my device in Mac OS M1 (apple silicon) 

Building wheels for collected packages: ast-grep-py
  Building wheel for ast-grep-py (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for ast-grep-py (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [135 lines of output]
      Running `maturin pep517 build-wheel -i /Users/REDACTED/dawn/.venv/bin/python --compatibility off`
      🍹 Building a mixed python/rust project
      🔗 Found pyo3 bindings
      🐍 Found CPython 3.13 at /Users/REDACTED/dawn/.venv/bin/python
      📡 Using build options features from pyproject.toml
      💻 Using `MACOSX_DEPLOYMENT_TARGET=11.0` for aarch64-apple-darwin by default
         Compiling cc v1.0.104
         Compiling memchr v2.7.2
         Compiling regex-syntax v0.8.5
         Compiling proc-macro2 v1.0.82
         Compiling unicode-ident v1.0.12
         Compiling once_cell v1.19.0
         Compiling target-lexicon v0.12.14
         Compiling wasm-bindgen-shared v0.2.92
         Compiling cfg-if v1.0.0
         Compiling serde v1.0.210
         Compiling log v0.4.21
         Compiling bumpalo v3.15.0
         Compiling aho-corasick v1.1.3
         Compiling wasm-bindgen v0.2.92
         Compiling crossbeam-utils v0.8.19
         Compiling quote v1.0.36
         Compiling tree-sitter v0.22.6
         Compiling pyo3-build-config v0.22.5
         Compiling syn v2.0.61
         Compiling thiserror v1.0.64
         Compiling bstr v1.9.1
         Compiling regex-automata v0.4.8
         Compiling autocfg v1.3.0
         Compiling bit-vec v0.8.0
         Compiling libc v0.2.159
         Compiling anyhow v1.0.90
         Compiling pyo3-ffi v0.22.5
         Compiling pyo3-macros-backend v0.22.5
         Compiling regex v1.11.0
         Compiling globset v0.4.15
         Compiling bit-set v0.8.0
         Compiling wasm-bindgen-backend v0.2.92
         Compiling memoffset v0.9.1
         Compiling crossbeam-epoch v0.9.18
         Compiling serde_json v1.0.132
         Compiling same-file v1.0.6
         Compiling ryu v1.0.18
         Compiling itoa v1.0.11
         Compiling heck v0.5.0
         Compiling walkdir v2.5.0
         Compiling wasm-bindgen-macro-support v0.2.92
         Compiling crossbeam-deque v0.8.5
         Compiling serde_derive_internals v0.29.0
         Compiling pyo3 v0.22.5
         Compiling serde_derive v1.0.210
         Compiling wasm-bindgen-macro v0.2.92
         Compiling thiserror-impl v1.0.64
         Compiling tree-sitter-ruby v0.21.0
         Compiling tree-sitter-rust v0.21.2
         Compiling tree-sitter-go v0.21.2
         Compiling tree-sitter-json v0.21.0
         Compiling tree-sitter-c-sharp v0.21.3
         Compiling tree-sitter-sequel v0.3.5
         Compiling tree-sitter-yaml v0.6.1
         Compiling tree-sitter-c v0.21.4
         Compiling tree-sitter-css v0.21.1
         Compiling tree-sitter-bash v0.21.0
         Compiling tree-sitter-cpp v0.22.3
         Compiling tree-sitter-facade-sg v0.22.2
         Compiling tree-sitter-swift v0.5.0
         Compiling tree-sitter-javascript v0.21.4
         Compiling tree-sitter-python v0.21.0
         Compiling tree-sitter-scala v0.22.1
         Compiling tree-sitter-php v0.23.0
         Compiling ast-grep-core v0.29.0 (/private/var/folders/zq/hm1jcvxn2xz_npdtk0qsbqdm0000gn/T/pip-install-qpgu_clu/ast-grep-py_d1bfbb9e4b464d22a4dc7314881529e8/crates/core)
         Compiling tree-sitter-dart v0.0.4
         Compiling tree-sitter-typescript v0.21.2
         Compiling tree-sitter-elixir v0.2.0
         Compiling tree-sitter-lua v0.1.0
         Compiling tree-sitter-java v0.21.0
         Compiling tree-sitter-haskell v0.21.0
         Compiling tree-sitter-html v0.20.4
         Compiling tree-sitter-kotlin v0.3.8
         Compiling equivalent v1.0.1
         Compiling hashbrown v0.14.5
         Compiling schemars v0.8.21
         Compiling indexmap v2.5.0
         Compiling pyo3-macros v0.22.5
         Compiling schemars_derive v0.8.21
         Compiling ignore v0.4.23
         Compiling unindent v0.2.3
      error[E0658]: use of unstable library feature 'once_cell'
         --> /Users/REDACTED/.cargo/registry/src/github.com-1ecc6299db9ec823/ignore-0.4.23/src/gitignore.rs:597:9
          |
      597 |     use std::sync::OnceLock;
          |         ^^^^^^^^^^^^^^^^^^^
          |
          = note: see issue #74465 <https://github.com/rust-lang/rust/issues/74465> for more information
      
      error[E0658]: use of unstable library feature 'once_cell'
         --> /Users/REDACTED/.cargo/registry/src/github.com-1ecc6299db9ec823/ignore-0.4.23/src/gitignore.rs:604:16
          |
      604 |     static RE: OnceLock<Regex> = OnceLock::new();
          |                ^^^^^^^^^^^^^^^
          |
          = note: see issue #74465 <https://github.com/rust-lang/rust/issues/74465> for more information
      
      error[E0658]: use of unstable library feature 'once_cell'
         --> /Users/REDACTED/.cargo/registry/src/github.com-1ecc6299db9ec823/ignore-0.4.23/src/gitignore.rs:604:34
          |
      604 |     static RE: OnceLock<Regex> = OnceLock::new();
          |                                  ^^^^^^^^
          |
          = note: see issue #74465 <https://github.com/rust-lang/rust/issues/74465> for more information
      
      error[E0658]: use of unstable library feature 'once_cell'
         --> /Users/REDACTED/.cargo/registry/src/github.com-1ecc6299db9ec823/ignore-0.4.23/src/gitignore.rs:604:34
          |
      604 |     static RE: OnceLock<Regex> = OnceLock::new();
          |                                  ^^^^^^^^^^^^^
          |
          = note: see issue #74465 <https://github.com/rust-lang/rust/issues/74465> for more information
      
      error[E0658]: use of unstable library feature 'once_cell'
         --> /Users/REDACTED/.cargo/registry/src/github.com-1ecc6299db9ec823/ignore-0.4.23/src/gitignore.rs:605:17
          |
      605 |     let re = RE.get_or_init(|| {
          |                 ^^^^^^^^^^^
          |
          = note: see issue #74465 <https://github.com/rust-lang/rust/issues/74465> for more information
      
         Compiling dyn-clone v1.0.17
      For more information about this error, try `rustc --explain E0658`.
      error: could not compile `ignore` due to 5 previous errors
      warning: build failed, waiting for other jobs to finish...
      💥 maturin failed
        Caused by: Failed to build a native library through cargo
        Caused by: Cargo build finished with "exit status: 101": `env -u CARGO MACOSX_DEPLOYMENT_TARGET="11.0" PYO3_ENVIRONMENT_SIGNATURE="cpython-3.13-64bit" PYO3_PYTHON="/Users/REDACTED/dawn/.venv/bin/python" PYTHON_SYS_EXECUTABLE="/Users/REDACTED/dawn/.venv/bin/python" "cargo" "rustc" "--features" "python" "--message-format" "json-render-diagnostics" "--manifest-path" "/private/var/folders/zq/hm1jcvxn2xz_npdtk0qsbqdm0000gn/T/pip-install-qpgu_clu/ast-grep-py_d1bfbb9e4b464d22a4dc7314881529e8/crates/pyo3/Cargo.toml" "--release" "--lib" "--" "-C" "link-arg=-undefined" "-C" "link-arg=dynamic_lookup" "-C" "link-args=-Wl,-install_name,@rpath/ast_grep_py.cpython-313-darwin.so"`
      Error: command ['maturin', 'pep517', 'build-wheel', '-i', '/Users/REDACTED/dawn/.venv/bin/python', '--compatibility', 'off'] returned non-zero exit status 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for ast-grep-py
Failed to build ast-grep-py
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (ast-grep-py)

### 🙁 Actual behavior

..

### 🙂 Expected behavior

..

**Comment by HerringtonDarkholme** [comment]
How are you installing ast-grep-py? It looks like you are building from source. If so, please upgrade your local rust to latest version.

**Comment by AraCoders** [comment]
It Worked! I updated the rustc and rebuilt the source again, Thanks for your help :)
