### ISSUE TITLE
[bug] NAPI incorrect node range for nested JSX element

### ISSUE THREAD

**Issue by arybitskiy** [ast-grep/ast-grep#1593]
### Please read the FAQ for the bug you encountered.

- [X] I have read the existing FAQ

### ⏯ Playground Link

https://ast-grep.github.io/playground.html#eyJtb2RlIjoiUGF0Y2giLCJsYW5nIjoidHN4IiwicXVlcnkiOiJleHBvcnQgZnVuY3Rpb24gYXNkKCkge1xuICAgICQkJFxufSIsInJld3JpdGUiOiIiLCJzdHJpY3RuZXNzIjoic2lnbmF0dXJlIiwic2VsZWN0b3IiOiIiLCJjb25maWciOiJydWxlOlxuICBraW5kOiBzdHJ1Y3RfaXRlbVxuIiwic291cmNlIjoiaW1wb3J0IHsgQnV0dG9uLCBGb3JtIH0gZnJvbSAnQGNvbXBhbnkvb2xkLXVpJztcblxuZnVuY3Rpb24gQ29tcG9uZW50KCkge1xuICByZXR1cm4gKFxuICAgIDxGb3JtPlxuICAgICAgPEJ1dHRvbiBvbkNsaWNrPXtjYWxsYmFja30gdmFyaWFudD1cInByaW1hcnlcIj5TdWJtaXQ8L0J1dHRvbj5cbiAgICA8L0Zvcm0+XG4gICk7XG59In0=

### 💻 Code

In playground Button has range 5,6 - 5,66.

### 🙁 Actual behavior

With @ast-grep/napi Button has range 4,10 - 5,66.

### 🙂 Expected behavior

With @ast-grep/napi Button should have range 5,6 - 5,66.

### Additional information about the issue

For some reason it takes into account leading spaces and newline.

**Comment by HerringtonDarkholme** [comment]
Tracked by 
https://github.com/tree-sitter/tree-sitter-typescript/issues/306
