### ISSUE TITLE
[feature] Language request: clojure

### ISSUE THREAD

**Issue by cosineblast** [ast-grep/ast-grep#1596]
# ⭐ Suggestion

It would be nice if ast-grep had support for a lisp language such as clojure.
I assume it wouldn't be too hard to implement support for a lisp-like language in ast-grep, as those languages usually don't have an overly complex syntax. This could possibly use [existing clojure tree-sitter grammars](https://github.com/sogaiu/tree-sitter-clojure)

# 💻 Use Cases

I would use this to perform general purpose refactoring in my projects.

**Comment by HerringtonDarkholme** [comment]
Hi thanks for using ast-grep and the suggestion to the tool. 

Howver, tree-sitter-clojure is not meeting ast-grep's criteria of built-in language. https://ast-grep.github.io/contributing/add-lang.html#requirements-and-constraints

* It is not maintained on crates.io https://crates.io/search?q=tree-sitter-clojure
* It is not officially maintained by tree-sitter team
* The last commit was created 6 months ago and the repo has not been updated to use the new `tree-sitter-language` crate.

That said, you can still use ast-grep by custom language registration.  https://ast-grep.github.io/advanced/custom-language.html

Thanks!

**Comment by Ramblurr** [comment]
@HerringtonDarkholme In the intervening year clojure's tree-sitter grammar is available as a crate and is up to date (clojure's syntax does not change often) https://crates.io/crates/tree-sitter-clojure

Could this be reopened?
