### ISSUE TITLE
[bug] ast-grep-py wheels for Python 3.13

### ISSUE THREAD

**Issue by vrslev** [ast-grep/ast-grep#1614]
### Please read the FAQ for the bug you encountered.

- [X] I have read the existing FAQ

### ⏯ Playground Link

.

### 💻 Code

```
// Your code here
```

### 🙁 Actual behavior

No wheels are provided for Python 3.13, which is now a stable Python version.

### 🙂 Expected behavior

Wheels on PyPI :)

**Comment by HerringtonDarkholme** [comment]
ast-grep will wait for the default action runner to support 3.13 
https://github.com/PyO3/maturin-action/issues/292#issuecomment-2401724215

**Comment by HerringtonDarkholme** [comment]
shipped with 0.30.1
