### ISSUE TITLE
[bug] Config path override is broken (0.30.0)

### ISSUE THREAD

**Issue by harjotgill** [ast-grep/ast-grep#1617]
### Please read the FAQ for the bug you encountered.

- [X] I have read the existing FAQ

### ⏯ Playground Link

N/A

### 💻 Code

Config path override seems to be broken in the latest release.

### 🙁 Actual behavior

```
$ ast-grep scan --config=config.yml
Error: No ast-grep project configuration is found.
Help: You need to create an ast-grep project for this command. Try `sg new` to create one.

$ cat config.yml
ruleDirs:
  - rules
```

### 🙂 Expected behavior

The config file override used to work in 0.28.1 release.

**Comment by HerringtonDarkholme** [comment]
Hi @harjotgill 

I tested the command above

```shell
$ ast-grep scan --config=config.yml # this does not work
$ ast-grep scan --config config.yml # this works
```

ast-grep introduced a change to unify the config argument. However, it looks like the `--config=xxx` syntax is no longer supported.

**Comment by HerringtonDarkholme** [comment]
Thanks for the report. Fixed
