### ISSUE TITLE
[feature] Combining `--error=unused-suppression` and `--update-all` should remove unused suppressions

### ISSUE THREAD

**Issue by seamuswn** [ast-grep/ast-grep#1624]
# ⭐ Suggestion

When running `ast-grep scan --update-all --error=unused-suppression`, unused suppressions should be automatically removed.

# 💻 Use Cases

This makes it easier to enable `--error=unused-suppression` or to automate linting fixes for cases where `--update-all` is used.

**Comment by HerringtonDarkholme** [comment]
Fixed in https://github.com/ast-grep/ast-grep/commit/0363ab118f162f6d48d64334a21feb22c4149e95

**Comment by HerringtonDarkholme** [comment]
suppression behavior is now documented in 

https://ast-grep.github.io/guide/project/severity.html
