### ISSUE TITLE
[feature] Accept multiple languages in a rule definition

### ISSUE THREAD

**Issue by MariaSolOs** [ast-grep/ast-grep#1628]
# ⭐ Suggestion

It would be very convenient for the `language` field in a rule definition to accept an array of language identifiers.

# 💻 Use Cases

It is a common scenario to apply a rule for both TypeScript and TSX files, and duplicating the rule feels clunky.

**Comment by HerringtonDarkholme** [comment]
Hi, thanks for the suggestion. This has been raised before https://github.com/ast-grep/ast-grep/issues/525.

The conclusion is that TypeScript and TSX just happened to share similar syntax.

**Comment by MariaSolOs** [comment]
Thank you! I apologize for the duplicate issue.
