### ISSUE TITLE
[feature] Support sorting AST nodes in rule

### ISSUE THREAD

**Issue by 0xC0D3D00D** [ast-grep/ast-grep#1638]
Hello!

Thank you for creating such an amazing tool! ❤️

# ⭐ Suggestion
Would it be possible to introduce a way to define scriptable or executable rules? I’ve encountered a use case that I couldn’t fully implement using the YAML rules. While I don’t have a concrete vision for how this feature might be integrated into ast-grep, I’d like to share an example from a similar tool (albeit one specifically for Java). You can see an implementation [here](https://github.com/PicnicSupermarket/error-prone-support/blob/master/error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/LexicographicalAnnotationListing.java).

# 💻 Use Cases
This feature could unlock significant flexibility for a variety of scenarios. For instance, consider a use case where there is a list of variables. I’d like these lists to be ordered lexicographically. This approach makes PR reviews more efficient because the sorting is consistent, and changes are easier to identify and understand through a clean, predictable diff.

## Example 1: Variable list
```go
var (
   ErrInvalidUserID = errors.New("invalid user id")
   ErrBadUUID = errors.New("bad uuid")
   ErrInternalServerErr = errors.New("internal server error")
)
```
Would become:
```go
var (
   ErrBadUUID = errors.New("bad uuid")
   ErrInternalServerErr = errors.New("internal server error")
   ErrInvalidUserID = errors.New("invalid user id")
)
```

## Example 2: Map definition
```go
  person := map[string]any{
     "last_name": "Smith",
     "first_name": "John",
     "age": 30,
  }
```
Would become:
```go
  person := map[string]any{
     "age": 30,
     "first_name": "John",
     "last_name": "Smith",
  }
```

These are not the only examples as it can be used in other contexts like sorting imports, annotations, etc.

Looking forward to your thoughts, and thanks again for your excellent work! 💪🏻

**Comment by HerringtonDarkholme** [comment]
Hi! It is possible to use ast-grep programmatically. See https://ast-grep.github.io/guide/api-usage.html and https://ast-grep.github.io/guide/api-usage/py-api.html. You can also use [`--inline-rules`](https://ast-grep.github.io/reference/cli/scan.html#inline-rules-rule-text) and [`--stdin`](https://ast-grep.github.io/reference/cli/scan.html#stdin) to programmatically use ast-grep without API integration. 

Meanwhile, it is very interesting that AST nodes can be sorted. I believe it can be integrated into the [`rewrite`](https://ast-grep.github.io/reference/yaml/transformation.html#rewrite) transformation by adding a field like `sortBy`.

**Comment by HerringtonDarkholme** [comment]
After careful consideration, we have decided that `sortBy` will likely not be a feature supported by ast-grep. The main reason for this is that ast-grep is not designed to handle formatting and stylistic changes. While the ordering of AST nodes can affect semantics, it is not feasible to design a `sortBy` algorithm that can interpret the meaning of the code to determine the correct sorting order. Instead, we could offer options to sort alphabetically or numerically, but these are typically only concerned with style. Therefore, ast-grep will delegate formatting tasks to language-specific tools, and `sortBy` will not be included as a feature.

Thanks for your suggestion.
