### ISSUE TITLE
[bug] rule works in playground but do not work in terminal

### ISSUE THREAD

**Issue by blurhead** [ast-grep/ast-grep#1647]
### Please read the FAQ for the bug you encountered.

- [X] I have read the existing FAQ

### ⏯ Playground Link

https://ast-grep.github.io/playground.html#eyJtb2RlIjoiQ29uZmlnIiwibGFuZyI6InB5dGhvbiIsInF1ZXJ5IjoiIiwicmV3cml0ZSI6IiIsInN0cmljdG5lc3MiOiJzbWFydCIsInNlbGVjdG9yIjoiIiwiY29uZmlnIjoiXG5pZDogcmV3cml0ZS1zdHJpbmdcbmxhbmd1YWdlOiBweXRob25cbnJ1bGU6XG4gIHBhdHRlcm46IHNhLkNvbHVtbigkTkFNRSwgc2EuU3RyaW5nICQkJEFSR1MpXG5maXg6ICdzYS5Db2x1bW4oJE5BTUUsIHNhLlN0cmluZygyNTUpJCQkQVJHUyknIiwic291cmNlIjoiXCJcIlwiYWRkIGFkbWluX3VzZXIuZXh0X2lkXG5cblJldmlzaW9uIElEOiBhYTRjYWFkMDA5NjdcblJldmlzZXM6IGI5YjI0NjQ1N2JlYlxuQ3JlYXRlIERhdGU6IDIwMjEtMDctMjIgMTQ6MzE6NTMuMjIyOTA3XG5cblwiXCJcIlxuXG5pbXBvcnQgc3FsYWxjaGVteSBhcyBzYVxuZnJvbSBhbGVtYmljIGltcG9ydCBvcFxuXG4jIHJldmlzaW9uIGlkZW50aWZpZXJzLCB1c2VkIGJ5IEFsZW1iaWMuXG5yZXZpc2lvbiA9IFwiYWE0Y2FhZDAwOTY3XCJcbmRvd25fcmV2aXNpb24gPSBcImI5YjI0NjQ1N2JlYlwiXG5icmFuY2hfbGFiZWxzID0gTm9uZVxuZGVwZW5kc19vbiA9IE5vbmVcblxuXG5kZWYgdXBncmFkZSgpOlxuICAgIG9wLmFkZF9jb2x1bW4oXCJhZG1pbl91c2VyXCIsIFxuICAgIHNhLkNvbHVtbihcImV4dF9pZFwiLCBzYS5TdHJpbmcpLFxuICAgIHNhLkNvbHVtbihcImV4dF91dGNcIiwgc2EuSW50ZWdlciwgc2VydmVyX2RlZmF1bHQ9c2EudGV4dChcIjFcIikpXG4gICAgKVxuICAgIG9wLmV4ZWN1dGUoXCJ1cGRhdGUgYWRtaW5fdXNlciBzZXQgZXh0X2lkPW5hbWUgd2hlcmUgbGVuZ3RoKHBhc3N3b3JkKSA9IDBcIilcblxuXG5kZWYgZG93bmdyYWRlKCk6XG4gICAgb3AuZHJvcF9jb2x1bW4oXCJhZG1pbl91c2VyXCIsIFwiZXh0X2lkXCIpXG4ifQ==

### 💻 Code

this is my rule
```yaml
id: rewrite-string
language: python
rule:
  pattern: sa.Column($NAME, sa.String $$$ARGS)
fix: 'sa.Column($NAME, sa.String(255) $$$ARGS)'
```

this is my code
```python
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "8dbdb1f4ad3c"
down_revision = "aa280dfe08e0"
branch_labels = None
depends_on = None


def upgrade():
    op.add_column("file", sa.Column("task_type", sa.String, server_default="extract"))


def downgrade():
    op.drop_column("file", "task_type")

```

why sa.String won't be replaced with sa.String(255), while it works in the playground

```bash
ast-grep scan -r ast-grep.yml misc/alembic/versions/20211101132312_add_field_task_type.py
```
i run the code in terminal with this command

### 🙁 Actual behavior

sa.String left unchanged

### 🙂 Expected behavior

sa.String should be replaced with sa.String(255)

**Comment by HerringtonDarkholme** [comment]
Please read the FAQ.

https://ast-grep.github.io/advanced/faq.html#cli-and-playground-produce-different-results-why

<img width="798" alt="image" src="https://github.com/user-attachments/assets/5ecebda8-ea57-4152-8bbe-14b347db1b41">

Also https://ast-grep.github.io/advanced/faq.html#my-pattern-does-not-work-why

**Comment by blurhead** [comment]
```
❯ ast-grep run -p "sa.Column($NAME, sa.String $$$ARGS)" --debug-query --lang=py debug_ast.py
Debug Pattern:
call
  attribute
    identifier sa
    .
    identifier Column
  argument_list
    (
    ERROR
      ,
      attribute
        identifier sa
        .
        identifier String
    integer 1060994
    )
```
this is the debug output, apparently, $NAME was not parsed correctly.

**Comment by HerringtonDarkholme** [comment]
![image](https://github.com/user-attachments/assets/1b2d0f9e-40c1-4d15-a456-32581a44aa58)

https://github.com/sponsors/HerringtonDarkholme
<img width="351" alt="image" src="https://github.com/user-attachments/assets/1f8b8488-5a09-4332-b67a-342bbc83be55">

**Comment by blurhead** [comment]
```yaml
rule:
  kind: attribute
  pattern: $TYPE
  regex: "sa.String[,)]"
fix: '$TYPE(255)'
```

thank you for your answer, i got another solution by using regexp and shrink the scope.
