### ISSUE TITLE
[bug] Java rule contains invalid kind matcher despite working on playground

### ISSUE THREAD

**Issue by jbarr21** [ast-grep/ast-grep#1648]
### Please read the FAQ for the bug you encountered.

- [X] I have read the existing FAQ

### ⏯ Playground Link

https://ast-grep.github.io/playground.html#eyJtb2RlIjoiQ29uZmlnIiwibGFuZyI6ImphdmEiLCJxdWVyeSI6IiIsInJld3JpdGUiOiIiLCJzdHJpY3RuZXNzIjoic2lnbmF0dXJlIiwic2VsZWN0b3IiOiIiLCJjb25maWciOiJpZDogc3VwZXJ0eXBlcy1qYXZhXG5sYW5ndWFnZTogamF2YVxucnVsZTpcbiAgYW55OlxuICAgIC0ga2luZDogdHlwZV9pZGVudGlmaWVyXG4gICAgLSBraW5kOiBzY29wZWRfdHlwZV9pZGVudGlmaWVyXG4gICAgLSBraW5kOiBnZW5lcmljX3R5cGVcbiAgaW5zaWRlOlxuICAgIGFueTpcbiAgICAgIC0ga2luZDogaW50ZXJmYWNlX3R5cGVfbGlzdFxuICBwYXR0ZXJuOiAkTkFNRSIsInNvdXJjZSI6ImNsYXNzIE15Q2xhc3MxXG4gICAgXG5jbGFzcyBNeUNsYXNzMiB7IH1cblxuY2xhc3MgTXlDbGFzczMgZXh0ZW5kcyBQYXJlbnRDbGFzcyB7IH1cblxuY2xhc3MgTXlDbGFzczM1IGV4dGVuZHMgUGFyZW50Q2xhc3MuSW1wbCB7IH1cblxuY2xhc3MgTXlDbGFzczM1MiBleHRlbmRzIFBhcmVudENsYXNzLkltcGw8VHlwZT4geyB9XG5cbmNsYXNzIE15Q2xhc3M0IGltcGxlbWVudHMgTXlJbnRlcmZhY2UgeyB9XG5cbmNsYXNzIE15Q2xhc3M0NSBpbXBsZW1lbnRzIE15SW50ZXJmYWNlLkltcGwgeyB9XG5cbmNsYXNzIE15Q2xhc3M0NTIgaW1wbGVtZW50cyBNeUludGVyZmFjZS5JbXBsPFR5cGU+IHsgfVxuXG5jbGFzcyBNeUNsYXNzNSBleHRlbmRzIFBhcmVudENsYXNzIGltcGxlbWVudHMgTXlJbnRlcmZhY2UgeyB9XG5cbmNsYXNzIE15Q2xhc3M2IGV4dGVuZHMgUGFyZW50Q2xhc3MgaW1wbGVtZW50cyBNeUludGVyZmFjZTEsIE15SW50ZXJmYWNlMiB7IH1cblxuY2xhc3MgTXlDbGFzczdcbiAgICBleHRlbmRzIFBhcmVudENsYXNzXG4gICAgaW1wbGVtZW50cyBNeUludGVyZmFjZTEsXG4gICAgTXlJbnRlcmZhY2UyIHsgfVxuIn0=

### 💻 Code

Rule: `~/supertypes-java.yaml` to match every java interface a class implements
```yaml
id: supertypes-java
language: java
rule:
  any:
    - kind: type_identifier
    - kind: scoped_type_identifier
    - kind: generic_type
  inside:
    any:
      - kind: interface_type_list
  pattern: $NAME
```

### 🙁 Actual behavior

```sh
 % ast-grep scan -r ~/supertypes-java.yaml --json=pretty
Error: Cannot parse rule /home/user/supertypes-java.yaml
Help: The file is not a valid ast-grep rule. Please refer to doc and fix the error.
See also: https://ast-grep.github.io/guide/rule-config.html

✖ Caused by
╰▻ Fail to parse yaml as Rule.
╰▻ `rule` is not configured correctly.
╰▻ Rule contains invalid kind matcher.
╰▻ Kind `interface_type_list` is invalid.
```

### 🙂 Expected behavior

Expected to match java interfaces on class declarations as in the [Playground link](https://ast-grep.github.io/playground.html#eyJtb2RlIjoiQ29uZmlnIiwibGFuZyI6ImphdmEiLCJxdWVyeSI6IiIsInJld3JpdGUiOiIiLCJzdHJpY3RuZXNzIjoic2lnbmF0dXJlIiwic2VsZWN0b3IiOiIiLCJjb25maWciOiJpZDogc3VwZXJ0eXBlcy1qYXZhXG5sYW5ndWFnZTogamF2YVxucnVsZTpcbiAgYW55OlxuICAgIC0ga2luZDogdHlwZV9pZGVudGlmaWVyXG4gICAgLSBraW5kOiBzY29wZWRfdHlwZV9pZGVudGlmaWVyXG4gICAgLSBraW5kOiBnZW5lcmljX3R5cGVcbiAgaW5zaWRlOlxuICAgIGFueTpcbiAgICAgIC0ga2luZDogaW50ZXJmYWNlX3R5cGVfbGlzdFxuICBwYXR0ZXJuOiAkTkFNRSIsInNvdXJjZSI6ImNsYXNzIE15Q2xhc3MxXG4gICAgXG5jbGFzcyBNeUNsYXNzMiB7IH1cblxuY2xhc3MgTXlDbGFzczMgZXh0ZW5kcyBQYXJlbnRDbGFzcyB7IH1cblxuY2xhc3MgTXlDbGFzczM1IGV4dGVuZHMgUGFyZW50Q2xhc3MuSW1wbCB7IH1cblxuY2xhc3MgTXlDbGFzczM1MiBleHRlbmRzIFBhcmVudENsYXNzLkltcGw8VHlwZT4geyB9XG5cbmNsYXNzIE15Q2xhc3M0IGltcGxlbWVudHMgTXlJbnRlcmZhY2UgeyB9XG5cbmNsYXNzIE15Q2xhc3M0NSBpbXBsZW1lbnRzIE15SW50ZXJmYWNlLkltcGwgeyB9XG5cbmNsYXNzIE15Q2xhc3M0NTIgaW1wbGVtZW50cyBNeUludGVyZmFjZS5JbXBsPFR5cGU+IHsgfVxuXG5jbGFzcyBNeUNsYXNzNSBleHRlbmRzIFBhcmVudENsYXNzIGltcGxlbWVudHMgTXlJbnRlcmZhY2UgeyB9XG5cbmNsYXNzIE15Q2xhc3M2IGV4dGVuZHMgUGFyZW50Q2xhc3MgaW1wbGVtZW50cyBNeUludGVyZmFjZTEsIE15SW50ZXJmYWNlMiB7IH1cblxuY2xhc3MgTXlDbGFzczdcbiAgICBleHRlbmRzIFBhcmVudENsYXNzXG4gICAgaW1wbGVtZW50cyBNeUludGVyZmFjZTEsXG4gICAgTXlJbnRlcmZhY2UyIHsgfVxuIn0=) which shows proper matches

<img width="1928" alt="Screenshot 2024-12-04 at 10 33 27 AM" src="https://github.com/user-attachments/assets/e8570413-7af0-4c7d-8c78-420f173ccc2b">

### Additional information about the issue

Tried using ast-grep v0.30.0 and v0.31.0

**Comment by HerringtonDarkholme** [comment]
https://ast-grep.github.io/advanced/faq.html#cli-and-playground-produce-different-results-why

**Comment by HerringtonDarkholme** [comment]
BTW the tree-sitter parser version has been updated in the playground

<img width="391" alt="image" src="https://github.com/user-attachments/assets/f4e2f803-5c37-4798-b84f-61ea203bd04a">

**Comment by jbarr21** [comment]
> faq link

@HerringtonDarkholme I saw the FAQ, but based on the ast-grep help, it seems `--debug-query` is only applicable to patterns & I am using a rule. is there any further way to debug the rule since using it on rules provides no additional info?

> utf-8 vs utf-16

would it be possible to have a flag for the CLI to run in either mode or is that too involved of a change?

> parser versions

thank you for the parser update. would it be possible to list the parser version on the playground (even if need to hover over an info icon) so that the same environment could be used?

**Comment by HerringtonDarkholme** [comment]
I found an amazing thing that unpkg serves tree-sitter's wasm file. So it is possible to have the language version!

<img width="1682" alt="image" src="https://github.com/user-attachments/assets/f33f9a8c-1e5b-4844-bce0-0a0aa2cbe0b7" />

**Comment by HerringtonDarkholme** [comment]
Added now!

<img width="279" alt="Image" src="https://github.com/user-attachments/assets/18ae0265-e71b-4977-a022-ef73d5227453" />
