### ISSUE TITLE
[bug] ast-grep panics on ast-grep\crates\core\src\match_tree\match_node.rs:98:40:

### ISSUE THREAD

**Issue by klensy** [ast-grep/ast-grep#1688]
### Please read the FAQ for the bug you encountered.

- [X] I have read the existing FAQ

### ⏯ Playground Link

https://github.com/llvm/llvm-project/tree/217e0f39710dec3348c996ecf98a76fd08b69853

### 💻 Code

checkout https://github.com/llvm/llvm-project at 217e0f39710dec3348c996ecf98a76fd08b69853 (you can try to checkout master, maybe it will work too) and get llvm-project/llvm/lib/Target/Mips/MipsAnalyzeImmediate.cpp,
then execute
```bash
$ sg run -p 'if ($A | $B)' MipsAnalyzeImmediate.cpp
```

### 🙁 Actual behavior

panics with:
```
thread '<unnamed>' panicked at D:\a\ast-grep\ast-grep\crates\core\src\match_tree\match_node.rs:98:40:
called `Option::unwrap()` on a `None` value
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### 🙂 Expected behavior

no panic

### Additional information about the issue

$ sg --version
ast-grep 0.32.1

**Comment by klensy** [comment]
reduced to 
```
void foo() {
  if (a | b)
}

```

**Comment by HerringtonDarkholme** [comment]
Thanks for the report and minimal reproduction. I will look at it later.
