### ISSUE TITLE
Unordered collection/destructuring patterns

### ISSUE THREAD

**Issue by JasonKleban** [ast-grep/ast-grep#1689]
# ⭐ Suggestion

To match this destructuring of `y` in the following, it would take multiple patterns, I think, because order and non-empty AST Nodes are required for multi-meta.

```
const { x, y, z } = foo;
const { x, y } = foo;
const { y, z } = foo;
const { y } = foo;
```

And what if we wanted to match destructuring of `x, y` from `foo`?  Order would matter here:

```
const { z, y, x } = foo;
```

This capability would also be useful for `import { z, y, x } from "foo";` or `React.useMemo(..., [ x, y, z ])`

**Comment by JasonKleban** [comment]
I filed this as a feature suggestion for a built-in syntax.

**Comment by HerringtonDarkholme** [comment]
Sorry I cannot understand what you are requesting for. 

This is what gpt explained:

> The user is suggesting a feature enhancement for ast-grep to support unordered collection and destructuring patterns. Currently, matching destructuring assignments like `const { x, y, z } = foo;` requires multiple patterns because the order of elements matters. The user wants ast-grep to handle cases where the order of elements is not important, such as `const { z, y, x } = foo;`. This feature would also be useful for import statements and array destructuring in functions, like `import { z, y, x } from "foo";` or `React.useMemo(..., [x, y, z])`.

So I guess the feature request is to have a syntax (what kind of?) to support unordered collection (how? what the meaning of handle?).

**Comment by HerringtonDarkholme** [comment]
There are multiple ways to match in 

* [using](https://ast-grep.github.io/playground.html#eyJtb2RlIjoiUGF0Y2giLCJsYW5nIjoiamF2YXNjcmlwdCIsInF1ZXJ5IjoibGV0IHsgJCQkLCB5LCAkJCQgfSA9ICQkJCIsInJld3JpdGUiOiIiLCJzdHJpY3RuZXNzIjoicmVsYXhlZCIsInNlbGVjdG9yIjoiIiwiY29uZmlnIjoiaWQ6IHJlbmFtZV9pbWctcmVzcG9uc2l2ZV9jbGFzc1xubGFuZ3VhZ2U6IGh0bWxcbnJ1bGU6XG4gIGtpbmQ6IGF0dHJpYnV0ZV92YWx1ZVxuICByZWdleDogJyhefCApaW1nLXJlc3BvbnNpdmUoIHwkKSdcbiAgcGF0dGVybjogJEFUVFJTXG4gIGluc2lkZTpcbiAgICBwYXR0ZXJuOiBcbiAgICAgIGNvbnRleHQ6IDxiIGNsYXNzPSRBPlxuICAgICAgc2VsZWN0b3I6IGF0dHJpYnV0ZSBcbiAgICBzdG9wQnk6IGVuZFxudHJhbnNmb3JtOlxuICBNSURETEVfT1JfRU5EOlxuICAgIHJlcGxhY2U6XG4gICAgICBzb3VyY2U6ICRBVFRSU1xuICAgICAgcmVwbGFjZTogJyBpbWctcmVzcG9uc2l2ZSg/PFJFU1Q+IHwkKSdcbiAgICAgIGJ5OiAnIGltZy1mbHVpZCRSRVNUJ1xuICBCRUdJTl9PUl9XSE9MRTpcbiAgICByZXBsYWNlOlxuICAgICAgc291cmNlOiAkTUlERExFX09SX0VORFxuICAgICAgcmVwbGFjZTogJ15pbWctcmVzcG9uc2l2ZSg/PFJFU1Q+IHwkKSdcbiAgICAgIGJ5OiAnaW1nLWZsdWlkJFJFU1QnXG5maXg6ICRCRUdJTl9PUl9XSE9MRSIsInNvdXJjZSI6ImNvbnN0IHsgeCwgeSwgeiB9ID0gZm9vO1xuY29uc3QgeyB4LCB5IH0gPSBmb287XG5jb25zdCB7IHksIHogfSA9IGZvbztcbmNvbnN0IHsgeSB9ID0gZm9vO1xuY29uc3QgeyAgYiB9ID0gYmJiIn0=) pattern + relaxed strictness
* using yaml [rule](https://ast-grep.github.io/playground.html#eyJtb2RlIjoiQ29uZmlnIiwibGFuZyI6ImphdmFzY3JpcHQiLCJxdWVyeSI6ImxldCB7ICQkJCwgeSwgJCQkIH0gPSAkJCQiLCJyZXdyaXRlIjoiIiwic3RyaWN0bmVzcyI6InJlbGF4ZWQiLCJzZWxlY3RvciI6IiIsImNvbmZpZyI6InJ1bGU6XG4gIGtpbmQ6IG9iamVjdF9wYXR0ZXJuXG4gIGFsbDpcbiAgLSBoYXM6XG4gICAgICByZWdleDogXnkkXG4gICAgICBraW5kOiBzaG9ydGhhbmRfcHJvcGVydHlfaWRlbnRpZmllcl9wYXR0ZXJuXG4gICAgICBwYXR0ZXJuOiAkWSBcbiAgLSBoYXM6XG4gICAgICByZWdleDogXngkXG4gICAgICBraW5kOiBzaG9ydGhhbmRfcHJvcGVydHlfaWRlbnRpZmllcl9wYXR0ZXJuXG4gICAgICBwYXR0ZXJuOiAkWCIsInNvdXJjZSI6ImNvbnN0IHsgeCwgeSwgeiB9ID0gZm9vO1xuY29uc3QgeyB4LCB5IH0gPSBmb287XG5jb25zdCB7IHksIHogfSA9IGZvbztcbmNvbnN0IHsgeSB9ID0gZm9vO1xuY29uc3QgeyAgYiB9ID0gYmJiIn0=)

Until we have more concrete feedback and proposal with 

* Concrete examples. including source code and target matching 
* Explanation of usage
* Proposed new syntax and their behavior

I will close this first
