### ISSUE TITLE
[feature] Add support for vue files

### ISSUE THREAD

**Issue by insidewhy** [ast-grep/ast-grep#1716]
# ⭐ Suggestion

Vue is support by the language server `volar`, I'm not sure how hard it would be to add support for `vue` to `ast-grep` but I can try if there's interest. It's basically a way to write css, html and typescript/javascript in a single file.

# 💻 Use Cases

Lots of people use vue I guess.

**Comment by HerringtonDarkholme** [comment]
Please see https://ast-grep.github.io/advanced/language-injection.html#more-possibility-to-be-unlocked

**Comment by insidewhy** [comment]
> Please see https://ast-grep.github.io/advanced/language-injection.html#more-possibility-to-be-unlocked

Thanks for the info and sorry for creating noise in this repo.

I created the following instructions for using `ast-grep` in `vue` project based on your documentation, I'll leave the link here for anyone who finds this issue:

https://dev.to/insidewhy/using-ast-grep-with-a-vue-project-2np2

**Comment by HerringtonDarkholme** [comment]
Wow! the blog is cool! Thanks for sharing!

**Comment by insidewhy** [comment]
> Wow! the blog is cool! Thanks for sharing!

Thanks for the compliment, and thanks for creating `ast-grep` it's *amazing*.

**Comment by jods4** [comment]
@HerringtonDarkholme Given that ast-grep already supports multi-languages for HTML files out of the box, it would be nice if `.vue` files where parsed as HTML by default. This very small change is already enough to pattern match inside `<script>`, `<style>` and `<template>` blocks.

The only limitation I can see is that expressions inside the template wouldn't be matched, but there's already huge value in matching the main script block.
I understand you may not want to embed and maintain a Vue Treesitter grammar, so people interested in matching the full code in details can follow insidewhy great post if they want that.

PSA: if you arrive here googling for Vue pattern matching, and if you're ok with just matching the main blocks, not the template expressions, then adding this to your `sgconfig.yml` is all it takes:
```yml
languageGlobs:
  html:
    - "*.vue"
```

**Comment by HerringtonDarkholme** [comment]
@jods4  

> The only limitation I can see is that expressions inside the template wouldn't be matched,

This is the reason why vue is not treated as HTML by default. Supporting it as built-in gives a false feeling that ast-grep supports all features of Vue.  Failing to capture expressions inside templates feels like a bug in such setup, since users without implementation knowledge would expect the behavior should stick to Vue's standard.

The configuration of `languageGlobs` is designed to let users explicitly agree to use `vue` file as `html`, thus accepting the limitation of ast-grep.

**Comment by jods4** [comment]
@HerringtonDarkholme I see.

Do you think you could add more preferences for the extension, so that this `*.vue: html` mapping could be registered once globally per user?

There's a trade-off in safe-guarding users from partial results and having to create a `sgconfig.yml` in every folder where I want to use it.

**Comment by adamsol** [comment]
> The only limitation I can see is that expressions inside the template wouldn't be matched,

In case anyone is looking for a simple way to make it work - following https://ast-grep.github.io/advanced/language-injection.html#injection-configuration, it's possible to enable JS parsing also in Vue attribute values using the built-in HTML parser:

```
languageGlobs:
  html: ['*.vue']
languageInjections:
  - hostLanguage: html
    rule:
      kind: attribute_value
      pattern: $CONTENT
    injected: js
```

This snippet could be extended to ignore attributes that don't start with `:` or `v-`, but it doesn't seem to be necessary.

However, this doesn't handle template interpolation (`{{ }}`). For this we would actually need a dedicated parser, as described in https://ast-grep.github.io/advanced/custom-language.html (see https://github.com/tree-sitter-grammars/tree-sitter-vue/blob/main/queries/vue/injections.scm).

**Comment by daflyinbed** [comment]
> Thanks for the info and sorry for creating noise in this repo.
> 
> I created the following instructions for using `ast-grep` in `vue` project based on your documentation, I'll leave the link here for anyone who finds this issue:
> 
> https://dev.to/insidewhy/using-ast-grep-with-a-vue-project-2np2

I created a [fork](https://github.com/daflyinbed/tree-sitter-vue) to build  tree-sitter-vue's dynamic library in github action.
