### ISSUE TITLE
[ Feature Request ] support multiple files findAll

### ISSUE THREAD

**Issue by ShenQingchuan** [ast-grep/ast-grep#195]
Since reading and handling files in Node.js is **SLOW**, I could only parse and find patterns one by one ... 

Is it possible to give a new kind of napi :

```ts
const sg = parser.parseAllFiles(
  filesPathList,
  /* optional */(path) => {
    /* decide which parser to be used */
  }
);
sg. /* whatever needed here ... maybe something like .root() */ .findAll({
  rule: { /* ... my rules */ }
})
```

@HerringtonDarkholme Anyway, thanks for your great work on ast-grep !!! ❤️ 
I've been using this awesome tool to imporve DX for my daily work, and if there is anything that I can help, please tell me.

**Comment by ShenQingchuan** [comment]
By the way, it seems that ast-grep Playground's editor has some bugs, it reports TypeScript errors while I'm writing some code snippets which contains `import from` or `import()` to test ....

I feel like that we should not provide such a language server behind and just as an plain editor to write some source code and do parsing...

**Comment by HerringtonDarkholme** [comment]
I have supported this in https://github.com/ast-grep/ast-grep/commit/9d22822b74adc850d2b5e1eb041a5f564eb7a50b!
