### ISSUE TITLE
Having trouble with `all` `not` rule.

### ISSUE THREAD

**Issue by jsimpson-gro** [ast-grep/ast-grep#240]
I'm having some trouble understanding how this rule is working:

```
rule:
  any:
    - pattern: use std::env::$_A;
  precedes:
    all:
      - not:
        pattern: use std::env::$_A;
```

The general idea is to make a linter that `std::env` imports occur before all other imports.

This rule without the `all` matches:

```
rule:
  any:
    - pattern: use std::env::$_A;
  precedes:
    not:
      pattern: use std::env::$_A;
```

```
$ sg scan
error[use-ordering]: Imports should be ordered.
  ┌─ ./src/main.rs:1:1
  │
1 │ use std::env::args;
  │ ^^^^^^^^^^^^^^^^^^^
2 │
3 │ use std::collections::HashMap;
  │ ------------------------------
  │
  = `use` statements should be ordered.
```

And this rule without the `not` matches:

```
rule:
  any:
    - pattern: use std::env::$_A;
  precedes:
    all:
      - pattern: use std::collections::$_A;
```

```
$ sg scan
error[use-ordering]: Imports should be ordered.
  ┌─ ./src/main.rs:1:1
  │
1 │ use std::env::args;
  │ ^^^^^^^^^^^^^^^^^^^
2 │
3 │ use std::collections::HashMap;
  │ ------------------------------
  │
  = `use` statements should be ordered.
```

This is the sample project I'm experimenting with: [ast-grep-example.tar.gz](https://github.com/ast-grep/ast-grep/files/10664355/ast-grep-example.tar.gz)

**Comment by HerringtonDarkholme** [comment]
Hi, you can use the https://ast-grep.github.io/playground.html as a reproduction.

**Comment by jsimpson-gro** [comment]
The playground is pretty sweet. Here [it is](https://ast-grep.github.io/playground.html#eyJtb2RlIjoiQ29uZmlnIiwibGFuZyI6InJ1c3QiLCJxdWVyeSI6ImNvbnNvbGUubG9nKCRNQVRDSCkiLCJjb25maWciOiJydWxlOlxuICBwYXR0ZXJuOiB1c2Ugc3RkOjplbnY6OiRBO1xuICBwcmVjZWRlczpcbiAgICBraW5kOiB1c2VfZGVjbGFyYXRpb25cbiIsInNvdXJjZSI6InVzZSBzdGQ6OmVudjo6YXJncztcbnVzZSBzdGQ6OmNvbGxlY3Rpb25zOjpIYXNoTWFwOyJ9) on the playground.

I'm still having trouble reasoning about why that doesn't work.

Also, the example I've provided is an extremely limited portion of a larger problem. In case it was your intention, the larger problem can not be solved using the method you've indicated. I'll need to identify order based on partial package names.
