### ISSUE TITLE
[feature] add test case filter for `sg test`

### ISSUE THREAD

**Issue by HerringtonDarkholme** [ast-grep/ast-grep#248]
Relevant code is here https://github.com/ast-grep/ast-grep/blob/main/crates/cli/src/verify.rs#L114-L134

The idea is to support `sg test -f test_case_glob` to run only test that matches the name. 

`-f` or `--filter` is used in mocha/ava to filter test cases using unix glob.

**Comment by gautamprikshit1** [comment]
Any help or description?

**Comment by HerringtonDarkholme** [comment]
Relevant code is here https://github.com/ast-grep/ast-grep/blob/main/crates/cli/src/verify.rs#L114-L134

The idea is to support `sg test -f test_case_regex` to run only test that matches the name. 

`-f` or `--filter` is used in mocha/ava to filter test cases.

**Comment by luismeyer95** [comment]
Hello! Just FYI, I saw this was not taken yet so I started working on implementing the feature, I will be pushing a draft PR soon. I hope that's OK with you!

**Comment by gautamprikshit1** [comment]
Fine by me, have been a little busy somehow skipped this one completely
