### ISSUE TITLE
String in pattern matches any string

### ISSUE THREAD

**Issue by strokirk** [ast-grep/ast-grep#276]
When searching for a pattern including a string, it seems that `ast-grep` generalizes it to "any string" rather than the specific string provided.

For example, if we are searching in https://github.com/django/django:

```
sg run -l py -p 'getattr($O, "__spec__", None)'
# Returns 153 results, including
getattr(response, "render", None)
getattr(options, "exclude", None)
...
```

compared to `semgrep`, which returns 3 results, all matching the exact string.

**Comment by HerringtonDarkholme** [comment]
Thanks for reporting! 
Looks like Python string is not an atomic but instead a composite, with left and right quotation marks as its children.
Curiously, the string content is not a child so this bug happens.

**Comment by HerringtonDarkholme** [comment]
fixed in https://github.com/ast-grep/ast-grep/commit/4986a676470ab7337648b806467fa436e0e8c2c5

**Comment by strokirk** [comment]
@HerringtonDarkholme Quick work! 👏
