### ISSUE TITLE
[feat] add lsp commands for search and replace in editor

### ISSUE THREAD

**Issue by HerringtonDarkholme** [ast-grep/ast-grep#283]
For example, ssr.nvim is a famous plugin that does structural search/replace in neovim.

https://github.com/cshuaimin/ssr.nvim

**Comment by IWANABETHATGUY** [comment]
Would you mind assigning this issue to me?

**Comment by HerringtonDarkholme** [comment]
No problem 👍 I would love to see more contributors!

**Comment by IWANABETHATGUY** [comment]
Here is the none trivial data structure: 
## request 
```rs
#[derive(Serialize, Deserialize)]
pub struct MatchRequest {
  pattern: String,
}
```
## response
```rs

#[derive(Serialize, Deserialize)]
pub struct MatchResult {
  uri: String,
  position: Range,
  content: String,
}

```

**Comment by IWANABETHATGUY** [comment]
Maybe we could only send the range of content, but I found that there is no easy way to get documents at the client side.

**Comment by IWANABETHATGUY** [comment]
[录屏 2023年03月28日 00时12分10秒.webm](https://user-images.githubusercontent.com/17974631/228004402-14487a9f-e9ff-4fb9-8f36-4f0ef5d860a2.webm)

**Comment by HerringtonDarkholme** [comment]
OMG this demo is amazing! I'm thinking if the request should be more refined. Also, adding a "replace" field will be useful.

**Comment by NicholasLYang** [comment]
Adding on, it'd be really cool to save & label patterns, then have the ability to search for them. Basically the ability to make ad-hoc code actions on the fly

**Comment by HerringtonDarkholme** [comment]
@IWANABETHATGUY would you like to create a pull request for your prototype? It is fine to merge it first and we can refine it later.

**Comment by IWANABETHATGUY** [comment]
yes
