### ISSUE TITLE
[feature] manipulate the captured variables in fix mode?

### ISSUE THREAD

**Issue by magic-akari** [ast-grep/ast-grep#315]
<img width="1268" alt="image" src="https://user-images.githubusercontent.com/7829098/228051413-9b455d1b-6d8b-4a08-adad-b1a07e884822.png">

[playground](https://ast-grep.github.io/playground.html#eyJtb2RlIjoiQ29uZmlnIiwibGFuZyI6ImphdmFzY3JpcHQiLCJxdWVyeSI6ImNvbnNvbGUubG9nKCRNQVRDSCkiLCJjb25maWciOiJpZDogcmV3cml0ZS1leHBvcnQtZnVuY3Rpb25cbm1lc3NhZ2U6IHJld3JpdGUgZXhwb3J0IGZ1bmN0aW9uXG5sYW5ndWFnZTogSmF2YVNjcmlwdFxuc2V2ZXJpdHk6IGVycm9yXG5ydWxlOlxuICBhbGw6XG4gICAgLSBwYXR0ZXJuOiBpbXBvcnQgeyAkQklORElORyB9IGZyb20gXCIkUEFUSFwiXG4gICAgLSBoYXM6XG4gICAgICAgIGtpbmQ6IHN0cmluZ1xuICAgICAgICBoYXM6XG4gICAgICAgICAga2luZDogc3RyaW5nX2ZyYWdtZW50XG4gICAgICAgICAgcmVnZXg6IFxcLmpzJFxuXG5maXg6IHZhciAkQklORElORyA9IHJlcXVpcmUoXCIkUEFUSFwiKS4kQklORElORztcblxuIyB0cmFuc2Zvcm06IFxuIyAgICRORVdQQVRIOiBDT05DQVQhKFNMSUNFISgkUEFUSCwgMCwgLTMpLCBcIi5janNcIilcbiMgZml4OiB2YXIgJEJJTkRJTkcgPSByZXF1aXJlKFwiJE5FV1BBVEhcIikuJEJJTkRJTkc7XG5cbiMgcmVnZXg6ICg/UDxCQVNFTkFNRT5cXHcrKVxcLmpzJCIsInNvdXJjZSI6ImltcG9ydCB7IGZvbyB9IGZyb20gXCIuL2Jhci5qc1wiOyJ9)

I am attempting to change the file extension from `.js` to `.cjs` .

**Comment by HerringtonDarkholme** [comment]
Sadly no. I didn't have a concrete plan to support manipulating meta variables in fix mode.

It is quite hard to support a solution flexible enough to support even 80% scenarios, without bringing a lot of ast-grep specific shenanigans. I really want users can learn the tool in minutes. 

That said, I'm still open to have a manipulation for meta variables. Let me know if you have any idea!

Meanwhile, you can use napi interface to write a small program.

**Comment by HerringtonDarkholme** [comment]
The `transform` looks like an interesting and viable solution to this problem. However the operators used here `CONCAT`, `SLICE` may introduce extra learning overhead for end users.

**Comment by magic-akari** [comment]
> Meanwhile, you can use napi interface to write a small program.

Yes, I thisnk I should use ast-grep in node side with magic-string.

**Comment by HerringtonDarkholme** [comment]
I think it is necessary to support string manipulation in fix mode. Reference https://github.com/ast-grep/ast-grep/discussions/430

It is impossible to match some patterns in some languages. String manipulation is a must to support example like `get the inner content of a generator expression in Python`. 

# String Manipulation

## Replace
```
$VAR/regex/replace/
```

## Deletion
Similar to replace but leave `replace` as empty.

```
$VAR/regex//
```

## Concat
```
$VAR1$VAR2
```

## Transform
Similar to 
https://www.typescriptlang.org/docs/handbook/2/template-literal-types.html#intrinsic-string-manipulation-types
```
$VAR.upperCase
$VAR.lowerCase.capitalize // multiple transformation can be chained
```

## Substring
Negative index is supported.
```
$VAR[1..-1]
```

**Comment by HerringtonDarkholme** [comment]
Thanks for suggestion! I have come up a more thorough proposal so let discuss in #436!
