### ISSUE TITLE
[perf] use &'static Node to improve pattern performance

### ISSUE THREAD

**Issue by HerringtonDarkholme** [ast-grep/ast-grep#345]
![image](https://user-images.githubusercontent.com/2883231/235770362-8ff1ee09-f2e5-4193-80a8-6a7bae75c772.png)

Testing single pattern now uses about 16.6% of time

**Comment by HerringtonDarkholme** [comment]
Pattern performance has been improved! with new pattern implementation!

https://github.com/ast-grep/ast-grep/blob/main/crates/core/src/matcher/pattern.rs#L16-L33

**Comment by 0xdevalias** [comment]
@HerringtonDarkholme Curious, if you have the stats on hand, what was the performance increase from this?

**Comment by HerringtonDarkholme** [comment]
@0xdevalias IIRC about 5% perf gain in the pattern find benchmark.

**Comment by 0xdevalias** [comment]
@HerringtonDarkholme Nice!
