### ISSUE TITLE
[Question] Capture multi meta variable

### ISSUE THREAD

**Issue by fvictorio** [ast-grep/ast-grep#372]
Is there a way to capture an usage of `$$$`?

To be honest, I don't have a realistic example where this is needed, but let's say I want to replace certain function calls with a bound call in javascript:

```js
// before
f()
f(1)
f(1, 2)

// after
f.call(null)
f.call(null, 1)
f.call(null, 1, 2)
```

The reasonable way to do that would be something like:

```bash
sg -p 'f($$$)' -r 'f.call(null, $$$)'
```

**Comment by HerringtonDarkholme** [comment]
Sure! You can use `$$$CAPTURE` to capture multiple nodes.

Example

https://ast-grep.github.io/playground.html#eyJtb2RlIjoiQ29uZmlnIiwibGFuZyI6ImphdmFzY3JpcHQiLCJxdWVyeSI6ImNvbnNvbGUubG9nKCRNQVRDSCkiLCJjb25maWciOiJydWxlOlxuICBwYXR0ZXJuOiBmKCQkJEEpXG5maXg6XG4gIGYuY2FsbChudWxsLCAkJCRBKSIsInNvdXJjZSI6ImYoKVxuZigxKVxuZigxLCAyKSJ9

**Comment by fvictorio** [comment]
Agh, I thought I had tried this, clearly I didn't. That makes sense, thanks! I'll send a PR adding this to the docs, if that's fine.

**Comment by HerringtonDarkholme** [comment]
Thank you so much for your support ❤️ !
