### ISSUE TITLE
[Rust] Doesn't match expressions inside vec![] macro

### ISSUE THREAD

**Issue by untitaker** [ast-grep/ast-grep#375]
source file:

```
fn main() {
    let hello = vec![
        x.to_string()
    ];
}
```

pattern:

```
sg --pattern '$PATTERN.to_string()' --rewrite 'String::from($PATTERN)'
```

will not work until I remove `vec!` from code.

**Comment by HerringtonDarkholme** [comment]
Indeed, text inside macro is parsed as `token_tree`.

See the playground output.
![image](https://github.com/ast-grep/ast-grep/assets/2883231/80a89dc7-81f8-43f9-b81b-d3143a19cc15)

https://ast-grep.github.io/playground.html#eyJtb2RlIjoiUGF0Y2giLCJsYW5nIjoicnVzdCIsInF1ZXJ5IjoiJFBBVC50b19zdHJpbmcoKSIsImNvbmZpZyI6IiMgQ29uZmlndXJlIFJ1bGUgaW4gWUFNTFxucnVsZTpcbiAgYW55OlxuICAgIC0gcGF0dGVybjogaWYgKGZhbHNlKSB7ICQkJCB9XG4gICAgLSBwYXR0ZXJuOiBpZiAodHJ1ZSkgeyAkJCQgfVxuY29uc3RyYWludHM6XG4gICMgTUVUQV9WQVI6IHBhdHRlcm4iLCJzb3VyY2UiOiJmbiBtYWluKCkge1xuICAgIGxldCBoZWxsbyA9IHZlYyFbXG4gICAgICAgIHgudG9fc3RyaW5nKClcbiAgICBdO1xufVxuIn0=

**Comment by HerringtonDarkholme** [comment]
As a work around, you can use the `contextual` pattern.

![image](https://github.com/ast-grep/ast-grep/assets/2883231/09ad7dae-d9d1-4a6c-80f7-78f142fab5c1)


https://ast-grep.github.io/playground.html#eyJtb2RlIjoiQ29uZmlnIiwibGFuZyI6InJ1c3QiLCJxdWVyeSI6IiRQQVQudG9fc3RyaW5nKCkiLCJjb25maWciOiIjIENvbmZpZ3VyZSBSdWxlIGluIFlBTUxcbnJ1bGU6XG4gIHBhdHRlcm46XG4gICAgY29udGV4dDogbWFjcm8hWyAkQS50b19zdHJpbmcoKSBdXG4gICAgc2VsZWN0b3I6IHRva2VuX3RyZWUiLCJzb3VyY2UiOiJmbiBtYWluKCkge1xuICAgIGxldCBoZWxsbyA9IHZlYyFbXG4gICAgICAgIHgudG9fc3RyaW5nKClcbiAgICBdO1xufVxuIn0=

**Comment by untitaker** [comment]
Thanks. Is there some way I can force the pattern to be parsed as token tree on the CLI?

**Comment by HerringtonDarkholme** [comment]
Yeah, you can save the rule in a local YAML (note you also need other related fields like id or language).

Then `sg scan -r your-local-rule.yml`.

https://ast-grep.github.io/guide/tooling-overview.html#run-one-single-query-or-one-single-rule
