### ISSUE TITLE
[Question] How to build a rule pattern to select tagged template literal

### ISSUE THREAD

**Issue by ShenQingchuan** [ast-grep/ast-grep#376]
Source code example:

```ts
function footerTemplate() {
    return html`<footer>Your footer here.</footer>`;
}
```

**Comment by HerringtonDarkholme** [comment]
Hi @ShenQingchuan, my dearest sponsor! Thanks for this issue.

I think it can be solved using yaml.

```yml
rule:
  kind: call_expression
  has:
    kind: template_string
    field: arguments
```

https://ast-grep.github.io/playground.html#eyJtb2RlIjoiQ29uZmlnIiwibGFuZyI6ImphdmFzY3JpcHQiLCJxdWVyeSI6IiIsImNvbmZpZyI6IiMgQ29uZmlndXJlIFJ1bGUgaW4gWUFNTFxucnVsZTpcbiAga2luZDogY2FsbF9leHByZXNzaW9uXG4gIGhhczpcbiAgICBraW5kOiB0ZW1wbGF0ZV9zdHJpbmdcbiAgICBmaWVsZDogYXJndW1lbnRzXG4iLCJzb3VyY2UiOiJmdW5jdGlvbiBmb290ZXJUZW1wbGF0ZSgpIHtcbiAgICByZXR1cm4gaHRtbGA8Zm9vdGVyPllvdXIgZm9vdGVyIGhlcmUuPC9mb290ZXI+YDtcbn1cblxuY29uc3QgYiA9IGh0bWxgPGRpdj4gaW50ZXJwb2xhdGlvbiB0ZXN0ICR7Zm9vdGVyVGVtcGxhdGV9YCJ9

**Comment by ShenQingchuan** [comment]
Thanks!

But I saw you build this rule as `kind: call_expression` with `field: arguments`. I got confused by the following two situations:

<img width="579" alt="image" src="https://github.com/ast-grep/ast-grep/assets/46062972/582f079a-23c0-4309-b921-49346e6b845f">

in this example, I intended to make another call expression with a template string argument, and I saw `arguments` AST node in the tree view.
But I didn't found `arguments` in that tagged template string AST nodes

How can the rule you showed above work to distinguish a "tagged template string" and a typical "call expression" with the "arguments" **field** ?

**Comment by HerringtonDarkholme** [comment]
>  I saw arguments AST node in the tree view.
> But I didn't found arguments in that tagged template string AST nodes

Thanks for clarifying your confusion.
In ast-grep (as well as tree-sitter), an AST node has two attributes: a kind and an optional field.

The `kind` corresponds to the node's inherent type, say it is a template string then its `kind` is `template_string`.
The `field` is an optional attribute and is only present when the node is in a special position relative to its parent node.
In this case, `arguments` means the child node is inside the call expression's argument position.

That's the background knowledge of ast-grep. Now let's see your question.

`field: arguments` means the target node is inside its parent node's `arguments` position. For example,

```
html`<div/>`
```

The example above `<div/>` has the kind `template_string` with field `arguments`, which matches both our `kind` and `field` matcher.

The confusing part is that `call(xxx)`'s parenthesis part has the `kind` as `arguments` as well. However, its kind does not match our query `kind: template_string`. So it fails to match.

**Comment by HerringtonDarkholme** [comment]
I think this is worth documenting! Thanks for the feedback!
