### ISSUE TITLE
Make ast-grep's cli binary the latest release

### ISSUE THREAD

**Issue by jankatins** [ast-grep/ast-grep#385]
It's convenient to download rust (or go) binaries from github release to be able to directly run the app (I want to use it on python code, so both cargo and npm are not so convenient). Currently the releases contain *.node files which file identifies as shared library. It would be nice if ast-grep could also add prebuilt binaries to the github releases, e.g. via the already existing github action workflow.

I tried to understand the release workflow and it sems to already upload zipped assets for each platform, but somehow only the *.node files end up in the release. Maybe this is only missing a [release asset upload](https://github.com/actions/upload-release-asset) somewhere?

If this is wanted (better to ask than to spend the time to fight with CI for nothing :-)), I can prepare a PR which would change/extend the release workflow to create a draft release and then upload the binaries to the release, add the changelog to the release and publish the release (adding the changelog before publishing means the release email contains the changelog and is not empty :-)). 

Would such a PR be wanted?

**Comment by HerringtonDarkholme** [comment]
Hi @jankatins ! Thanks for the issue! 

Binary is already there. Due to technical issue (a.k.a too lazy to change napi's workflow), we have two pipelines in the CI.
The binary is in the other release tag. For example.

https://github.com/ast-grep/ast-grep/releases/tag/0.5.2

**Comment by HerringtonDarkholme** [comment]
You can also install it via brew now! https://formulae.brew.sh/formula/ast-grep

```shell
brew install ast-grep
```

**Comment by jankatins** [comment]
Usecases: on case I thought about in the last week is linting pyproject.toml for some internal rule (all packages have a source defined, some specific packages are at a specific version,... I remember I had over the years some usecases of rewrigin spython source code, but never a nice tool to do it. So learning ast-grep to have it in my toolbox would be nice :-)

I wanted to install it through zinit, which has a  method to install binaries from github releases and put them into PATH. But that won't work correctly because the latest release doesn't contain the right binaries. Would you take a PR which basically copies the the two workflows together so you end up with a single release?

**Comment by HerringtonDarkholme** [comment]
Thanks for the reporting! 

>  I still don't understand why there are two releases/tags for the same thing

Tweaking napi's build is quite hard. Maybe only Brooooooklyn can do that. 

> I wanted to install it through zinit, which has a method to install binaries from github releases and put them into PATH.

Do you have a link to the method? Currently the zinit fails to install ast-grep because the latest release is napi instead of CLI? Is this correct?

**Comment by jankatins** [comment]
zinit is here: https://github.com/zdharma-continuum/zinit. I would use `zinit as'null' from"gh-r" lbin'!sg' lucid nocompile completions for @ast-grep/ast-grep` which basically would go to github API for ast-grep/ast-grep, grab the latest release and then try to figure out which asset to download and then try to decompress it somewhere and add a symlink to the 'sg' binary into a place which is in PATH (and it would add zsh completions if there are files in the form `_*` in the release archive). Right now it results in this:

```
Downloading ast-grep/ast-grep…
(Requesting `ast-grep-napi.darwin-x64.node'…)
################################################################### 100.0%
[ziextract] Error: didn't recognize archive type of ast-grep-napi.darwin-x64.node  } (no extraction has been done).
Error:  linkbin annex: The automatic-empty lbin ice didn't find any executable files
```

**Comment by jankatins** [comment]
I found this: https://napi.rs/docs/cli/pre-publish which describes a `--skip-gh-release` which sounds like it would skip creating a tag and a github release, e.g. when added here: 

https://github.com/ast-grep/ast-grep/blob/8aaa09c0567aa741e8f6a9a5c38e75e363239cdb/crates/napi/package.json#L41

But I have no clue if that should happen or not and if that script is actually called (the log makes it look like it does: https://github.com/ast-grep/ast-grep/actions/runs/4970061077/jobs/8893760623#step:9:23). And if you want the `*.node` files in a github release or not :-)

**Comment by HerringtonDarkholme** [comment]
Nice finding! It is probably what we need! I'm trying to release a 0.5.3 to see if this can be fixed!

> And if you want the *.node files in a github release or not :-)

TBH, I have deleted them several times because it breaks my other CI pipeline.

**Comment by HerringtonDarkholme** [comment]
Thank @jankatins so much for reporting this! Now the GitHub release is much cleaner!! 

Both release and napi action passed.
* https://github.com/ast-grep/ast-grep/actions/runs/5018582627
* https://github.com/ast-grep/ast-grep/actions/runs/5018582629

 Also the napi package got a bug fix hidden months long! (Note old version is released under next tag instead of latest).

![image](https://github.com/ast-grep/ast-grep/assets/2883231/16bcf854-100a-4781-855d-3364e6cabfce)

https://www.npmjs.com/package/@ast-grep/napi?activeTab=versions

**Comment by jankatins** [comment]
Nice, that worked :-)

```
Downloading ast-grep/ast-grep…
(Requesting `sg-x86_64-apple-darwin.zip'…)
################################################################### 100.0%
[ziextract] Unpacking the files from: `sg-x86_64-apple-darwin.zip'…
Archive:  sg-x86_64-apple-darwin.zip
  inflating: sg
[ziextract] Successfully extracted and assigned +x chmod to the file: sg.
==> linkbin annex: Created sg soft link & set +x on the sg binary

(venv:mds-data-core-py3.11) took 7s
[00:17:48] λ  sg --help
Search and Rewrite code at large scale using AST pattern.
                    __
        ____ ______/ /_      ____ _________  ____
       / __ `/ ___/ __/_____/ __ `/ ___/ _ \/ __ \
      / /_/ (__  ) /_/_____/ /_/ / /  /  __/ /_/ /
      \__,_/____/\__/      \__, /_/   \___/ .___/
                          /____/         /_/
...
```
