### ISSUE TITLE
Add `-A` alias to `sg run --accept all`

### ISSUE THREAD

**Issue by mkatychev** [ast-grep/ast-grep#386]
> Hi @mkatychev ! Thanks for your contribution! 
> 
> Would you like to first open a GitHub issue to discuss this change? I would want to collect more user feedback.
> 
> My personal feeling is `--aceept-all` is a somewhat dangerous operation and asking users to confirm before committing is a must when use this tool. 
> 
> Adding a shortcut command might encourage users to skip the inspection. 
> 
> But thanks for the pull request and I learnt clap can have custom short option!

_Originally posted by @HerringtonDarkholme in https://github.com/ast-grep/ast-grep/issues/384#issuecomment-1550024205_

**Comment by HerringtonDarkholme** [comment]
Indeed most people should be using version control system.
Also `git diff` is a valid argument and sg probably won't have an advanced diff viewer built-in.
This makes sense when users prefer to use sg + diff viewer as their workflow.

Plus, `-A` sounds like a good choice since it is capitalized, denoting it as a "destructive" operation.


Let me do some more research on other CLI tools...

**Comment by mkatychev** [comment]
My rationale/inspiration for `-A` came from `git add -A`/`git add --all`. It's a pretty destructive operation given that it adds any and all changes to the state of your staged state (sometimes needing a lot of `git restore --stage` to undo 😢).

**Comment by HerringtonDarkholme** [comment]
Most command line apps give simple access to in place change.
Some examples:

* sd in place change does not any flag `sd 'window.fetch' 'fetch' http.js`
* `sed -i 's/foo/bar/g' test.txt` -i means in place change
* `semgrep -a` means `--autofix`
* perl -i -pe 's/foo/bar/g;' test.txt
* ruby -i -pe 'gsub(/foo/, "bar")' test.txt
* facebook's fastmod does not have a short form `--accept-all` https://github.com/facebookincubator/fastmod/blob/main/src/main.rs#L828 (neither codemod https://github.com/facebookarchive/codemod)

I think it is quite Okay to add this flag! But I would also prefer admonish in the command line help text that this flag should be used with caution.
