### ISSUE TITLE
[Question] Any rule to match a tree-sitter node that does not have children?

### ISSUE THREAD

**Issue by ShenQingchuan** [ast-grep/ast-grep#390]
As the title said.

If there isn't, maybe we can plan for this as a new feature.

If there is already one rule pattern there, it's worth a documentation.

**Comment by HerringtonDarkholme** [comment]
Sure there is a way to match such node!
The trick here is to use wildcard meta variable with `not` operator.

```yaml
rule:
  pattern: $A
  not:
    has:
      pattern: $B
```

Note `$B` will match anything, so the `not` rule will effectively match only node without any child.

[playground](https://ast-grep.github.io/playground.html#eyJtb2RlIjoiQ29uZmlnIiwibGFuZyI6ImphdmFzY3JpcHQiLCJxdWVyeSI6ImNvbnNvbGUubG9nKCRNQVRDSCkiLCJjb25maWciOiJydWxlOlxuICBwYXR0ZXJuOiAkQVxuICBub3Q6XG4gICAgaGFzOlxuICAgICAgcGF0dGVybjogJCRCIiwic291cmNlIjoiZnVuY3Rpb24gdHJ5QXN0R3JlcCgpIHtcbiAgY29uc29sZS5sb2coJ0hlbGxvIFdvcmxkJylcbn1cblxuY29uc3QgbXVsdGlMaW5lRXhwcmVzc2lvbiA9XG4gIGNvbnNvbGVcbiAgIC5sb2coJ0Fsc28gbWF0Y2hlZCEnKSJ9)
