### ISSUE TITLE
[Question] support TypeScript 4.9 `satisfies` operator

### ISSUE THREAD

**Issue by ShenQingchuan** [ast-grep/ast-grep#393]
As the title said, I found a Pull Request in "tree-sitter-typescript"

https://github.com/tree-sitter/tree-sitter-typescript/pull/228

it seems that tree-sitter has already fixed this? Maybe not support in ast-grep is due to version behind official?

<img width="361" alt="image" src="https://github.com/ast-grep/ast-grep/assets/46062972/33d01145-cb28-4417-b85a-d0ca054c4c07">

[Playground](https://ast-grep.github.io/playground.html#eyJtb2RlIjoiQ29uZmlnIiwibGFuZyI6InR5cGVzY3JpcHQiLCJxdWVyeSI6IiIsImNvbmZpZyI6InJ1bGU6XG4gICIsInNvdXJjZSI6ImNvbnN0IGluc3RhbnRpYXRpb24gPSBmb28gc2F0aXNmaWVzIFQifQ==)

**Comment by ShenQingchuan** [comment]
Oh... I saw `tree-sitter-typescript` hasn't release a new version for a long time, maybe couple of months...
the latest 0.20.2 is still not available

**Comment by HerringtonDarkholme** [comment]
Looks like tree-sitter crate is already updated in command line apps. 

```shell
sg -p 'let c = a satisfies b' -l ts --debug-query
```

But wasm is not updated yet. So the playground is not updated.

**Comment by ShenQingchuan** [comment]
> Looks like tree-sitter crate is already updated in command line apps.
> 
> ```shell
> sg -p 'let c = a satisfies b' -l ts --debug-query
> # output
> # Pattern TreeSitter (lexical_declaration (variable_declarator name: (identifier) value: (satisfies_expression (identifier) (type_identifier))))
> ```
> 
> But wasm is not updated yet. So the playground is not updated.

Yeah, what a pitty, my project relys heavily on the WASM API

**Comment by HerringtonDarkholme** [comment]
Do you mean wasm or napi? napi is backed by native tree-sitter so it would not be impacted.

**Comment by ShenQingchuan** [comment]
I'm relying on napi, so is there any solution for napi ?

**Comment by HerringtonDarkholme** [comment]
Write Rule/Query as is. It should work. But you don't have access to a visual debugger like the playground. :(

**Comment by ShenQingchuan** [comment]
> Write Rule/Query as is. It should work. But you don't have access to a visual debugger like the playground. :(

Got it !

**Comment by ShenQingchuan** [comment]
> ```shell
> identifier
> ```

<img width="736" alt="image" src="https://github.com/ast-grep/ast-grep/assets/46062972/539dfc2b-059d-4a8a-8e6d-71ad6b5da23e">

it did work!, so I'm gonna close this issue.

**Comment by HerringtonDarkholme** [comment]
Supported in the new playground!

https://ast-grep.github.io/playground.html#eyJtb2RlIjoiUGF0Y2giLCJsYW5nIjoidHlwZXNjcmlwdCIsInF1ZXJ5IjoiIiwiY29uZmlnIjoiIyBDb25maWd1cmUgUnVsZSBpbiBZQU1MXG5ydWxlOlxuICBhbnk6XG4gICAgLSBwYXR0ZXJuOiBpZiAoZmFsc2UpIHsgJCQkIH1cbiAgICAtIHBhdHRlcm46IGlmICh0cnVlKSB7ICQkJCB9XG5jb25zdHJhaW50czpcbiAgIyBNRVRBX1ZBUjogcGF0dGVybiIsInNvdXJjZSI6InR5cGUgQ29sb3JzID0gXCJyZWRcIiB8IFwiZ3JlZW5cIiB8IFwiYmx1ZVwiO1xuLy8gRW5zdXJlIHRoYXQgd2UgaGF2ZSBleGFjdGx5IHRoZSBrZXlzIGZyb20gJ0NvbG9ycycuXG5jb25zdCBmYXZvcml0ZUNvbG9ycyA9IHtcbiAgICBcInJlZFwiOiBcInllc1wiLFxuICAgIFwiZ3JlZW5cIjogZmFsc2UsXG4gICAgXCJibHVlXCI6IFwia2luZGFcIixcbiAgICBcInBsYXR5cHVzXCI6IGZhbHNlXG4gICAgLy8gIH5+fn5+fn5+fn4gZXJyb3IgLSBcInBsYXR5cHVzXCIgd2FzIG5ldmVyIGxpc3RlZCBpbiAnQ29sb3JzJy5cbn0gc2F0aXNmaWVzIFJlY29yZDxDb2xvcnMsIHVua25vd24+OyJ9

https://twitter.com/hd_nvim/status/1661404425716654082
