### ISSUE TITLE
[feature] support `--inline-rules` option for sg scan

### ISSUE THREAD

**Issue by HerringtonDarkholme** [ast-grep/ast-grep#396]
Currently, there is no way to use a rule without a YAML file on the disk.

We can add a `--inline-rules` option to scan files without a physical rule.

This is especially useful for scripting/languages without native bindings. 

Basically, we can achieve a programmatic usage of ast-grep by combining `inline-rules` and `json`

```
sg scan --inline-rules --json <<EOF
rule:
  pattern: XXX
EOF
```

It can simulate napi's behavior. `inline-rules` is the input and `json` will be the output.

**Comment by HerringtonDarkholme** [comment]
fixed by https://github.com/ast-grep/ast-grep/pull/789

**Comment by surma** [comment]
Omg you legend <3
