### ISSUE TITLE
[refactor] move tree-sitter-wasm related crates into one monorepo

### ISSUE THREAD

**Issue by HerringtonDarkholme** [ast-grep/ast-grep#414]
1. https://github.com/ast-grep/tree-sitter-facade for unifying both web and native API
2. https://github.com/ast-grep/web-tree-sitter-sg for bridging tree-sitter wasm to Rust wasm
https://github.com/ast-grep/web-tree-sitter-wasm-bindgen for wasm-pack to integrate tree-sitter-wasm

It is not urgent. in backlog.

**Comment by 0xdevalias** [comment]
Out of curiosity, would you move these to a new monorepo, or into this main `ast-grep` repo?

**Comment by HerringtonDarkholme** [comment]
Hi @0xdevalias. Thanks for your interest in ast-grep :)

These crates are solely for wasm based usage which, at the moment, is solely for the ast-grep playground.

So I would prefer to move them to another new monorepo.

**Comment by 0xdevalias** [comment]
> So I would prefer to move them to another new monorepo.

@HerringtonDarkholme _nods_, that makes sense :)

**Comment by HerringtonDarkholme** [comment]
Fixed  in https://github.com/ast-grep/tree-sitter-wasm
