### ISSUE TITLE
[bug] unable to use on ubuntu 20.04 (version `GLIBC_2.32' not found (required by ast-grep))

### ISSUE THREAD

**Issue by szamanr** [ast-grep/ast-grep#416]
i installed using npm `npm i @ast-grep/cli -g` but when i try to run it i get:

```
> ast-grep --help
ast-grep: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by ast-grep)
ast-grep: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by ast-grep)
ast-grep: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by ast-grep)
```

i'm on ubuntu 20.04 which has glibc 2.31:

```
> ldd --version
ldd (Ubuntu GLIBC 2.31-0ubuntu9.9) 2.31
```

my kernel is:

```
> uname -r
5.15.0-72-generic
```

seems like my system repo does not provide a newer version and i don't have enough knowledge to try and install another version manually, as i'm worried it will mess up with existing tools. upgrading my OS is currently not an option either.

---

i would be satisfied with either solution / reply:

- make the tool compatible with glibc2.1
- provide a different / older version that works with glibc2.1
- give instructions for a painless, risk-free way of getting a compatible glibc version

thanks :)

**Comment by HerringtonDarkholme** [comment]
Hi, thank you for your interest in ast-grep and for reporting this issue. We appreciate your feedback and suggestions. Unfortunately, due to limited bandwidth and other issues outstanding, supporting old glibc will not be prioritized at this time. 

A possible work around is to use `cargo install` to build the binary. 

This is also a good first issue for the community if anyone wants to contribute a patch. 

We apologize for any inconvenience and hope you enjoy using ast-grep.

**Comment by HerringtonDarkholme** [comment]
I have released v0.6.0 and it should work on ubuntu 20.04!

**Comment by pd4d10** [comment]
Also encountered this issue at Debian 10:

```
/home/code/node_modules/.bin/../@ast-grep/cli/sg: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.29' not found (required by /home/code/node_modules/.bin/../@ast-grep/cli/sg)
```

Is there any documentation for supported glibc version? Thanks!

**Comment by HerringtonDarkholme** [comment]
@pd4d10 I'm sorry that probably ast-grep cannot provide official support for Debian 10.

The program is built on Ubuntu-20 with GitHub Actions.

To support Debian 10, you may need to compile ast-grep from the source.

**Comment by songyazhao** [comment]
I also encountered this problem：

internal/rsbuild-config build:   Rslib v0.9.2
internal/rsbuild-config build: error   Failed to build.
internal/rsbuild-config build: error   /lib64/libc.so.6: version `GLIBC_2.25' not found (required by /home/gitlab-runner/builds/LxNcSsgs/0/lucky/skin/sdk/sports/sport-core/node_modules/.pnpm/@ast-grep+napi-linux-x64-gnu@0.37.0/node_modules/@ast-grep/napi-linux-x64-gnu/ast-grep-napi.linux-x64-gnu.node)

**Comment by HerringtonDarkholme** [comment]
@songyazhao ast-grep doesn't support older linux. please consider using other container or use other libraries
