### ISSUE TITLE
Support for C++?

### ISSUE THREAD

**Issue by torshepherd** [ast-grep/ast-grep#417]
What would it take to add support for C++? Seems like there is a tree-sitter grammar for it: https://github.com/tree-sitter/tree-sitter-cpp

If it's not too much work I could make a PR for it

**Comment by HerringtonDarkholme** [comment]
I believe I have tried that before. But tree-sitter-cpp's rust binding is still in 0.19 version. It is not updated to the latest v0.20. 

https://github.com/tree-sitter/tree-sitter-cpp/tree/master/bindings/rust

So it probably will not work if we just add tree-sitter-cpp as a dependency. Sadly. We need to first bump the version and release it in crates.io.
