### ISSUE TITLE
Match function with and without modifiers

### ISSUE THREAD

**Issue by raffomania** [ast-grep/ast-grep#434]
Thanks for making ast-grep, it's an awesome tool!

I'd like to write a pattern to match both of these functions in rust:

```rust
fn lel() {
    println!("hi")
}

pub fn wat() {
    println!("hello")
}
```

I've tried the following patterns, but none of them match:
```
$$$ fn $FN() {$$$}
$PUB fn $FN() {$$$}
$PUB fn $FN()
fn $FN() {$$$}
fn $FN()
fn
```

I want to refactor a parameter in functions that have a mixture of different modifiers like `pub`, `async`, etc. and can't find a pattern to match all of them.

**Comment by raffomania** [comment]
Also see this [playground link](https://ast-grep.github.io/playground.html#eyJtb2RlIjoiUGF0Y2giLCJsYW5nIjoidHlwZXNjcmlwdCIsInF1ZXJ5IjoidXNlU3RhdGU8c3RyaW5nIHwgdW5kZWZpbmVkPiIsImNvbmZpZyI6IiMgQ29uZmlndXJlIFJ1bGUgaW4gWUFNTFxucnVsZTpcbiAga2luZDogY2FsbF9leHByZXNzaW9uXG4gIGhhczpcbiAgICBraW5kOiB0ZW1wbGF0ZV9zdHJpbmdcbiAgICBmaWVsZDogYXJndW1lbnRzXG4iLCJzb3VyY2UiOiJpbXBvcnQgeyB1c2VTdGF0ZSB9IGZyb20gJ3JlYWN0J1xuXG5mdW5jdGlvbiBmb290ZXJUZW1wbGF0ZSgpIHtcbiAgICBjb25zdCBbc3RhdGUsIHNldFN0YXRlXSA9IHVzZVN0YXRlPHN0cmluZyB8IHVuZGVmaW5lZD4oKVxuICAgIHJldHVybiA8cD57c3RhdGV9PC9wPlxufVxuIn0=) with the example code from the description.

**Comment by HerringtonDarkholme** [comment]
Thanks for your kind word! 
Surely it is hard to write a pattern for such use case. We will need to enumerate all the combinations of modifiers if we stick to pattern alone. But ast-grep has another rule called `kind` in YAML mode that can help you.

```yaml
rule:
  kind: function_item
```
Doc:
https://ast-grep.github.io/guide/rule-config/atomic-rule.html

Example:
https://ast-grep.github.io/playground.html#eyJtb2RlIjoiQ29uZmlnIiwibGFuZyI6InJ1c3QiLCJxdWVyeSI6InVzZVN0YXRlPHN0cmluZyB8IHVuZGVmaW5lZD4iLCJjb25maWciOiJydWxlOlxuICBraW5kOiBmdW5jdGlvbl9pdGVtIiwic291cmNlIjoiZm4gbGVsKCkge1xuICAgIHByaW50bG4hKFwiaGlcIilcbn1cblxucHViIGZuIHdhdCgpIHtcbiAgICBwcmludGxuIShcImhlbGxvXCIpXG59XG5hc3luYyBmbiB0ZXN0KCkge1xuICAgIHByaW50bG4hKFwiYXN5bmNcIilcbn0ifQ==

**Comment by raffomania** [comment]
Thanks! I had no idea yaml rules were so much more powerful than the CLI, will give this a try!
