### ISSUE TITLE
[feature] manipulate captured variable in fix mode

### ISSUE THREAD

**Issue by HerringtonDarkholme** [ast-grep/ast-grep#436]
# Suggestion

## ⭐ Suggestion

I think it is necessary to support string manipulation in fix mode. Reference https://github.com/ast-grep/ast-grep/discussions/430

It is impossible to match some patterns in some languages. String manipulation is a must to support example like `get the inner content of a generator expression in Python`.

# 📃 Motivating Example  
## New Field in YAML Rule

We will add a new field `transform` in YAML rule. Example

```
rule: 
  pattern: import {$BINDING} from "$PATH"
transform:
   NEW_PATH: PATH[..-3]
fix: var $BINDING = require("$PATH").binding
```
`transform` is a dictionary of key-value pairs. Key is the new meta variable name. 
Value is the transformation written in string manipulation syntax.

### Replace
```
$VAR/regex/replace/
```

### Deletion
Similar to replace but leave `replace` as empty.

```
$VAR/regex//
```

### Concat
```
$VAR1$VAR2
```

### Transform
Similar to 
https://www.typescriptlang.org/docs/handbook/2/template-literal-types.html#intrinsic-string-manipulation-types
```shell
$VAR.upperCase
$VAR.lowerCase.capitalize # multiple transformation can be chained
```

### Substring
Negative index is supported.
```
$VAR[1..-1]
```

## 💻 Use Cases

change file extension from `.js` to `.cjs` / `.mjs`. See #315 
support rewrite python generator syntax. See #430

**Comment by HerringtonDarkholme** [comment]
I will only support string slicing in my first implementation.

**Comment by suyanhanx** [comment]
> $VAR/regex/replace/

Is this `replace` a keyword or we will replace the matched part with this content?

**Comment by suyanhanx** [comment]
The regex and replace parts may be difficult to distinguish.

**Comment by HerringtonDarkholme** [comment]
@suyanhanx  Any suggestion to make them clear?

**Comment by suyanhanx** [comment]
It's actually difficult to decide which character to choose as the separator. Can we provide an additional configuration option to allow users to choose their own separator?

**Comment by HerringtonDarkholme** [comment]
> Can we provide an additional configuration option to allow users to choose their own separator?
It will introduce community splitting and additional implementation complexity.
I remember Vim has it and it is probably too nerdy to most modern devs.

**Comment by suyanhanx** [comment]
Alternatively, we could change the format by making it like a function call or dividing it into different configuration options.

**Comment by HerringtonDarkholme** [comment]
Added in 0.6.3
