### ISSUE TITLE
[bug] npm can't run success in linux

### ISSUE THREAD

**Issue by StarFishing** [ast-grep/ast-grep#440]
[Playground link with relevant code](https://ast-grep.github.io/playground.html

Pattern:

```yml
sg run --pattern '$PROP && $PROP'
```

# 🙁 Actual behavior
`sg: /lib/x86_64-linux-gnu/libc.so.6: version "GLIBC_2.34" not found (required by sg)`

# 🙂 Expected behavior
npm install can be use normally

// sg version:0.5.7

**Comment by HerringtonDarkholme** [comment]
Hi, thanks for trying ast-grep. As a work around, you can use it with `cargo install ast-grep`.

This is a duplicate of https://github.com/ast-grep/ast-grep/issues/416

**Comment by HerringtonDarkholme** [comment]
I have released v0.6.0 and it should work on ubuntu 20.04
