### ISSUE TITLE
Skip matches in interactive mode

### ISSUE THREAD

**Issue by thedenisnikulin** [ast-grep/ast-grep#444]
# ⭐ Suggestion

I would like to have an ability to skip matches in interactive mode. Now, all the matches are suggested to be applied at once (maybe you can only skip a file? not sure), but sometimes it's very useful to skip some matches.

# 💻 Use Cases

**What do you want to use this for?** To apply matches selectively
**What shortcomings exist with current approaches?** None I believe
**What workarounds are you using in the meantime?** I tried to use structured search and replace plugin in neovim which allows skipping, but it segfaults for some reason, so I just edit files manually.

**Comment by HerringtonDarkholme** [comment]
Hi, thanks for trying out ast-grep.

I have not quite sure of the desired UX of skipping matches.
Currently, all matches for one rule are reported at once for one file. 
We can present matches one by one but it will be too inefficient.

**Comment by thedenisnikulin** [comment]
Hello @HerringtonDarkholme, here's the plugin: https://github.com/cshuaimin/ssr.nvim.
Regarding the UX, maybe the matches can still be all reported at once for a file visually, but the currently focused match will be highlighted somehow, and default options to choose will be "to replace all matches in this block (file)", "to skip all matches in this block", "to mark current match for replacement", "to skip current match", though there can be problems with this approach and I am not sure either. I agree that it's not quite trivial to design.

**Comment by HerringtonDarkholme** [comment]
I have changed the behavior to print only one match at a time.
