### ISSUE TITLE
[feature] Parse multiple pieces of code (same language) one time

### ISSUE THREAD

**Issue by ShenQingchuan** [ast-grep/ast-grep#448]
As the title said, I have a use scene like this:

- I have some TypeScript code (not from files, just as string)
- I want to put them into ast-grep to compile and get AST

But I don't know how I can do it and what's the best practice to leverage ast-grep(or Rust)'s powerful parallel mechanism.

**Comment by HerringtonDarkholme** [comment]
Sadly it is not possible now...

**Comment by HerringtonDarkholme** [comment]
Hey @ShenQingchuan , this feature has been supported by `parseAsync`!

https://dev.to/herrington_darkholme/benchmark-typescript-parsers-demystify-rust-tooling-performance-2go8
Here is the blog benchmarking parallel parsing of different parsers!
