### ISSUE TITLE
TypeScript Support for Generic `SgNode`

### ISSUE THREAD

**Issue by sxzz** [ast-grep/ast-grep#48]
We could add more variants of `SgNode`, like `SgNode<CallExpression>`, `SgNode<StringLiterial>`

`@babel/types` is a good example for reference.

**Comment by HerringtonDarkholme** [comment]
I found tree-sitter supports a node-types json metadata from which we can produce TypeScript definition.

**Comment by 0xdevalias** [comment]
See also:

- https://github.com/tree-sitter/tree-sitter-typescript
  - > TypeScript grammar for tree-sitter

**Comment by HerringtonDarkholme** [comment]
Fixed by #1661
