### ISSUE TITLE
[feature] print all available languages and their alias in long help

### ISSUE THREAD

**Issue by HerringtonDarkholme** [ast-grep/ast-grep#483]
# ⭐ Suggestion

Currently, our help message only prints our supported language. But not their short alias. For example , 

`sg -l JavaScript` is okay and `sg -l js` is also okay.

We already add a list of supported languages in short help message. We can put full language lists and aliases in the long help.

# 💻 Use Cases

Help users know what languages can be used. Reduce user frictions.

**Comment by HerringtonDarkholme** [comment]
This can be a good issue if you want to contribute!
It will a medium sized pull request. Comment below if you want to grab this and we can discuss how to implement it.

Some code points:
1. how builtin languages are parsed 
https://github.com/ast-grep/ast-grep/blob/main/crates/language/src/lib.rs#L133-L160
2. how builtin language is merged with custom language
https://github.com/ast-grep/ast-grep/blob/main/crates/cli/src/lang.rs
4. how language help is printed.
https://github.com/ast-grep/ast-grep/blob/main/crates/cli/src/run.rs#L31-L37

**Comment by HerringtonDarkholme** [comment]
This has been partially supported via doc page. https://ast-grep.github.io/reference/languages.html

But in CLI it is still desirable.

**Comment by pd4d10** [comment]
What is the desired result you are expecting? 

The current behavior is:

```
> sg run -h
...
  -l, --lang <LANG>            The language of the pattern. Supported languages are:
                               [C, Cpp, CSharp, Css, Dart, Go, Html, Java, JavaScript, Kotlin, Lua, Python, Ruby, Rust, Scala, Swift, Thrift, Tsx, TypeScript]
...
```

If all aliases are listed here, would it be too verbose?

**Comment by HerringtonDarkholme** [comment]
@pd4d10 indeed, listing all languages in CLI may be too long. The webpage should be enough https://ast-grep.github.io/reference/languages.html
