### ISSUE TITLE
[feature] Option to disable a rule

### ISSUE THREAD

**Issue by makotot** [ast-grep/ast-grep#489]
# ⭐ Suggestion

It would be helpful if it has possibility to specify an option to temporarily disable a rule. For example, just as ESLint has an off level for severity, it would be nice to be able to disable severity for each rule in ast-grep.

```yaml
severity: off
```

# 💻 Use Cases
I suppose there could be a situation where we want to temporarily disable a particular rule to reduce noise, and then treat it as an error again  later.

**Comment by HerringtonDarkholme** [comment]
Thanks for the suggestion! I need some time to understand its usage and think about the potential conflict of this option.

Meanwhile, you can use `ignores` option to disable a rule at the moment. https://ast-grep.github.io/guide/rule-config.html#files-ignores

```
ignores:
  - ./**/*
``

**Comment by HerringtonDarkholme** [comment]
Supported in 31b3cab440c1f2b0d2cb5a3762ce0987dae9c047!

**Comment by makotot** [comment]
Awesome! Thanks so much!
