### ISSUE TITLE
[feature] Returns the target file path in the callback function of findInFiles

### ISSUE THREAD

**Issue by makotot** [ast-grep/ast-grep#497]
# ⭐ Suggestion

In `@ast-grep/napi`, as something like below, it would be nice to be able to refer to the callback function parameter of `findInFiles` when we want to know which file was matched.
```diff
-  export function findInFiles(config: FindConfig, callback: (err: null | Error, result: SgNode[]) => void): Promise<number>
+  export function findInFiles(config: FindConfig, callback: (err: null | Error, result: SgNode[], filePath: string) => void): Promise<number>
```
If there is already a way to accomplish something similar, I would like to know about it.

# 💻 Use Cases

I want to count the match results by file path.

**Comment by HerringtonDarkholme** [comment]
Good point! I will add it in next version!

**Comment by HerringtonDarkholme** [comment]
Now you can access it via `nodes[0].getRoot().filename()` 
https://github.com/ast-grep/ast-grep/blob/main/crates/napi/__test__/index.spec.ts#L146-L158

```ts
  let findInFiles = countedPromise(ts.findInFiles)
  await findInFiles({
    paths: ['./'],
    matcher: {
      rule: {kind: 'member_expression'}
    },
  }, (err, n) => {
    t.is(err, null)
    const root = n[0].getRoot();
    t.deepEqual(root.filename(), './__test__/index.spec.ts')
  })
```

**Comment by makotot** [comment]
Thanks so much!
