### ISSUE TITLE
[feature] Add changelog during github release creation

### ISSUE THREAD

**Issue by jankatins** [ast-grep/ast-grep#498]
# ⭐ Suggestion

I monitor the project using the release emails sent by github upon publishing a release (Watch -> Custom -> Releases). Unfortunately, the sent email does not contain the changelog, as at the time the release is created/published it does not contain a changelog entry, but this is added later (manually?)

It would be nice if either:
- the changelog could be generated before the creation of the release and the output added to the create release github action call OR
- The release could be created in draft mode so that the publish happens when the changelog was added.

(I tried to figure out when the changelog is added: to my eyes it gets added manually or by some undocumented magic in the last step in the release workflow (heinrichreimer/action-github-changelog-generator only documents that it sets the changelog as an output which could be consumed by the create release action)

I can send a PR for both versions, if any of the solutions would be acceptable to you.

**Comment by jankatins** [comment]
Thank you, worked like a charm!

![image](https://github.com/ast-grep/ast-grep/assets/890156/7dd2d2e8-0e9f-4873-9630-a4987b275db6)

**Comment by jankatins** [comment]
Strangely, I would have expected that https://github.com/ast-grep/ast-grep/blob/d81cf31a1092334a82101f727a1c44f80f47a412/.github/workflows/release.yml#L116-L122 would be moved above the release creation action. Right now it seems to do nothing?

**Comment by HerringtonDarkholme** [comment]
I don't quite understand the `heinrichreimer/action-github-changelog-generator@v2.3` action since the README from that project said it will change release note upon release is created.
Maybe my configuration is wrong but it seems that we don't need the action at the moment.

**Comment by jankatins** [comment]
I think the main result of that action is the changelog in an output (more or less a "variable" which contains the changelog so it can get passed from one action as an input to another) which can be used in the next step to create the release. 

So you wouldn't need to maintain the changelog anymore, but let the action create it on the fly and use that output to create the release.
