### ISSUE TITLE
[bug] tsx.findInFiles may include ts in the target files

### ISSUE THREAD

**Issue by makotot** [ast-grep/ast-grep#502]
# ⏯ Playground Link
N/A

# 💻 Code

Code:

Repository to be reproduced is available here.
https://github.com/makotot/ast-grep-napi-find-in-files-tsx-issue

`$ npm run exec`

```ts
import { tsx } from '@ast-grep/napi'
;(() => {
  tsx.findInFiles(
    {
      paths: ['./example'],
      matcher: {
        rule: {
          any: [
            {
              kind: 'import_statement',
            },
            {
              kind: 'export_statement',
            },
          ],
        },
      },
    },
    (err, resultNodes) => {
      if (err) {
        console.log(err)
      }

      const results = resultNodes.map((node) => {
        return {
          statement: node.text(),
          path: node.getRoot().filename(),
        }
      })

      console.log(results)
      // [ { statement: '{}', path: './example/foo.ts' } ]
      // Is it expected that files with the extension ts?
    }
  )
})()

```

# 🙁 Actual behavior

My assumption is that `tsx.findInFiles` in `@ast-grep/napi` works only for tsx files, but as far as I can figure out, it only seems to include ts files if they contain `export` clause.

# 🙂 Expected behavior

I'm thinking that files with the extension ts should be exempt with `tsx.findInFiles` 🤔.

**Comment by HerringtonDarkholme** [comment]
Thanks for the report!

I need to thinking about the behavior. Most users will use `ts` along with `tsx` in their setup, is it desirable to parse `tsx` only?

The desired behavior may be discovering all TS + TSX files and parsing them based on extension. 

What's your opinion?

**Comment by makotot** [comment]
> The desired behavior may be discovering all TS + TSX files and parsing them based on extension.

If the behavior consistently included ts files, I would think it would be as described above, but it did not appear to be the case.
The breaking point appears to be whether or not the export clause is included.
For example, I added [this file](https://github.com/makotot/ast-grep-napi-find-in-files-tsx-issue/blob/main/example/baz.ts) to the repository I reported, but it is not recognized as a target. Maybe I am not understanding something 🤔 .

Here are the execution results.
```bash
$ npm run exec

 ast-grep-napi-find-in-files-tsx-issue@1.0.0 exec
 ts-node ./src/index.ts

[
  {
    statement: "import { FindConfig } from '@ast-grep/napi'",
    kind: 'import_statement',
    path: './example/bar.tsx'
  },
  {
    statement: 'export { Bar }',
    kind: 'export_statement',
    path: './example/bar.tsx'
  },
  {
    statement: 'export default Bar',
    kind: 'export_statement',
    path: './example/bar.tsx'
  }
]
[
  {
    statement: '{ Foo }',
    kind: 'export_clause',
    path: './example/foo.ts'
  }
]
```
</details> 

I too think the use case would be to treat both ts and tsx as targets.

**Comment by HerringtonDarkholme** [comment]
I see.

If you question is "why `.ts` file is matched if they contain export clause."

This is because findInFiles accepts "FindConfig" where you can specify the `matcher`.
Only file with nodes matching with `matcher`  will be reported in the callback.

In this case, the findInFile with called with `matcher` like below

```
        rule: {
          any: [
            {
              kind: 'import_statement',
            },
            {
              kind: 'export_statement',
            },
          ],
        },
```

So only import/export file is reported by ast-grep

**Comment by HerringtonDarkholme** [comment]
At least `findInFiles`' doc is not clear to you. Thanks for reporting the confusion! I will update the doc.

https://github.com/ast-grep/ast-grep.github.io/issues/188

**Comment by makotot** [comment]
Thank you for your detailed explanation and thanks again for the documentation improvements. 

> So only import/export file is reported by ast-grep. It is not because they are tsx or ts.

I am sorry, but I have one more question.
I thought it would match if it was [a ts file that had an import statement](https://github.com/makotot/ast-grep-napi-find-in-files-tsx-issue/blob/main/example/baz.ts), but am I understanding that incorrectly as well?

**Comment by HerringtonDarkholme** [comment]
This is indeed a valid bug!

```ts
console.log(ts.kind('import_statement'), tsx.kind('import_statement'))
// 168, 170
```

Gave me two different kind.

The problem is that though  both ts and TSX are discovered by ast-grep. The kind `import_statement` is different in two languages. 

Our config is specified as `tsx` so the `import_statement` kind is not equal to `ts`

**Comment by HerringtonDarkholme** [comment]
napi 0.9.0 now strictly uses file extension to discover files!
So that `tsx.findInFiles` will always report `*.tsx` file.

![image](https://github.com/ast-grep/ast-grep/assets/2883231/10656b26-37d9-43ac-b90a-30691dbcb5fc)

My change 
![image](https://github.com/ast-grep/ast-grep/assets/2883231/f92e42e4-eddc-4527-9d48-7f5f0c16f3f9)
