### ISSUE TITLE
[bug][docs] Shared library compilation directions are wrong

### ISSUE THREAD

**Issue by dcsommer** [ast-grep/ast-grep#503]
On https://ast-grep.github.io/advanced/custom-language.html, there is a recommendation to run the following command to produce a shared library:
```
gcc -shared -fPIC -fno-exceptions -g -I src/tree_sitter/parser.h -o mojo.so -O2
```

This fails as there is no source file specified. Instead it should be changed to
```
gcc -shared -fPIC -fno-exceptions -g -I src src/parser.c -o mojo.so -O2
```

This also applies to the more generic version of the `gcc` example further up.

**Comment by HerringtonDarkholme** [comment]
Thanks for the report.

**Comment by HerringtonDarkholme** [comment]
The recommended way is to use tree-sitter CLI to build the so file.

**Comment by dcsommer** [comment]
For what it's worth, I couldn't build it via the tree-sitter CLI, but
manually building with gcc worked.
