### ISSUE TITLE
[CLI] normalize search result file path in command line output 

### ISSUE THREAD

**Issue by SSShuai1999** [ast-grep/ast-grep#52]
When i type a command like this:

```shell
sg --pattern '$A || $B' --lang ts .////////
```

The found file output like this: 
```shell
.////////compiler\factory\utilitiesPublic.ts
```

**Comment by HerringtonDarkholme** [comment]
Sorry, I don't understand the issue. 
What's your expected output?

**Comment by SSShuai1999** [comment]
So fast, I just feel that `/` and `\` are inconsistent together, I didn't expect anything, I just wanted them to be consistent.

Like this: 

```shell
./compiler/factory/utilitiesPublic.ts
```
