### ISSUE TITLE
[feature] Support for OCaml

### ISSUE THREAD

**Issue by tysg** [ast-grep/ast-grep#521]
# ⭐ Suggestion

We use OCaml extensively so I'm wondering if `ast-grep` can add support for it. `tree-sitter` supports OCaml: https://github.com/tree-sitter/tree-sitter-ocaml . I did a quick look around the code and it seems like more of the language-specific work is handled by tree-sitter, so adding a new language would be just to add some configuration. 

If it's as easy as this, I can spend some time on it, but I want to see if there's anything I should look out for. Is it as simple as changing the files below (taken from #435)?
```
https://github.com/ast-grep/ast-grep/blob/main/crates/language/src/lib.rs
https://github.com/ast-grep/ast-grep.github.io/blob/main/src/wasm_lang.rs#L27
```

**Comment by HerringtonDarkholme** [comment]
Hello tysg. Thanks for giving ast-grep a try.
While supporting new language is easy, it does impose some installation overhead for our end users.

Please pardon me. My concern would be the popularity of OCaml. TIOBE's top 50 programming language does not include OCaml yet. I understand that popularity itself does not stand for the quality and beauty of a beloved programming language. But as a maintainer, I have to consider about the runtime size of the program.

That said, ast-grep supports registering custom language via dynamic library. You can still try OCaml with this tool!
 https://ast-grep.github.io/advanced/custom-language.html

**Comment by tysg** [comment]
Thanks for the swift response! I didn't consider the overhead for including the grammar but it makes total sense to me. 

I'll try out the link that you mentioned - it looks reasonably straightforward. 

Meanwhile, I'll close this issue for the moment :)
