### ISSUE TITLE
[feature]make --json output one line ouput

### ISSUE THREAD

**Issue by Marskey** [ast-grep/ast-grep#561]
# ⭐ Suggestion
this is ripgrep add args `--json` ouput:
```
{"type":"match","data":{"path":{"text":"./LICENSE"},"lines":{"text":"you grant is automatically extended to all recipients of the covered\n"},"line_number":518,"absolute_offset":27034,"submatches":[{"match":{"text":"call"},"start":21,"end":25}]}}

{"type":"match","data":{"path":{"text":"./LICENSE"},"lines":{"text":"specifically granted under this License.  You may not convey a covered\n"},"line_number":524,"absolute_offset":27331,"submatches":[{"match":{"text":"call"},"start":7,"end":11}]}}
```

# 💻 Use Cases
I am currently working on a telescope picker that exposes some ast-grep functionalities. What ast-grep --json give to me is a big json data that maybe cause json decode failed if its too big. I hope it would be one line json data.  My English is not good, and I hope my expression is clearer.

**Comment by HerringtonDarkholme** [comment]
Hi. Thanks for writing ast-grep telescope plugin!

I really appreciate it.

Let me think about a way to roll this out with compatibility. Keep tuned.

**Comment by HerringtonDarkholme** [comment]
I can extend `--json` flag to several different flags

* --json human prints the matches as a pretty-printed JSON array, with indentation and line breaks. This is useful for human readability, but not for parsing by other programs.
* --json stream prints each match as a separate JSON object, followed by a newline character. This is useful for streaming the output to other programs that can read one object per line.
* --json compact prints the matches as a single-line JSON array, without any whitespace. This is useful for saving space and minimizing the output size.

**Comment by HerringtonDarkholme** [comment]
Hi @Marskey , I have supported the feature by `--json=stream`. The output style is similar to ripgrep.

I have also seen your great plugin. https://github.com/Marskey/telescope-sg 

Would you like kindly provide a screenshot in the README so I can tweet about it with an image? Thanks!

**Comment by Marskey** [comment]
@HerringtonDarkholme with pleasure and thank you for your work and the amazing ast-grep

**Comment by Marskey** [comment]
Hi@HerringtonDarkholme , I found  that the text of json data is not at least one line text, is just gave me the search text. could you change this
![image](https://github.com/ast-grep/ast-grep/assets/13499986/8eb0c8ab-8bd6-418b-b294-85257ae133ce)
above screenshot shows only text 'handle_entry_index' were gaven
to like this
![image](https://github.com/ast-grep/ast-grep/assets/13499986/9fe3c7b7-d49e-479f-a0ed-f1cec8030088)
above screenshot shows that whole 'line local handle_entry_index = function(opts, t, k)' were gaven.
Anyway, its not urgent request.

**Comment by HerringtonDarkholme** [comment]
Hi @Marskey , ast-grep's JSON provides line/col and byte offset. Is it possible to use vim's buffer to get the line content?

**Comment by Marskey** [comment]
@HerringtonDarkholme , telescope can show the detail of result that user selected by its' previewer.
![image](https://github.com/ast-grep/ast-grep/assets/13499986/7e1c8421-7ea5-4e7c-b6df-8448eddfc372)

 but not the text of result list, i cant open file again to get the whole line text while i get results from ast-grep because the perfermance

**Comment by HerringtonDarkholme** [comment]
Thanks, I will consider supporting it.

**Comment by HerringtonDarkholme** [comment]
Hi @Marskey , it is supported in ast-grep 0.11.1
