### ISSUE TITLE
scan command panics

### ISSUE THREAD

**Issue by bodograumann** [ast-grep/ast-grep#57]
When I run `sg scan` anywhere, it imediately fails with the following error:

> thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', crates/cli/src/config.rs:8:48

The rust backtrace does not produce anything useful.

**Comment by HerringtonDarkholme** [comment]
Hi! the `sg scan` command's documentation and error reporting is still under working. 

For early bird trial, you can look need a sgconfig.yml like [this](https://github.com/ast-grep/ast-grep/blob/main/sgconfig.yml)
to specify the rule dirs. Rule's definition can be found [here](https://github.com/ast-grep/ast-grep/blob/main/rules/no-const-condition.yml)

**Comment by bodograumann** [comment]
Ah yes that works :-)

**Comment by HerringtonDarkholme** [comment]
Added a help message for the cli!

![image](https://user-images.githubusercontent.com/2883231/192354599-8881a61f-731f-4b58-9a9d-c5454687edb7.png)
