### ISSUE TITLE
[feature] Add cmake language support

### ISSUE THREAD

**Issue by alcroito** [ast-grep/ast-grep#570]
# ⭐ Suggestion

It would be nice if ast-grep had support for the cmake language.

# 💻 Use Cases

Things like searching for function calls with specific parameters would be useful for projects with big cmake build systems.

Tree-sitter already has a parser for cmake at https://github.com/uyha/tree-sitter-cmake

To add support for cmake, is it just about adding some standard language boiler-plate in ast-grep, or are there more pieces missing?

**Comment by HerringtonDarkholme** [comment]
Hi! Thanks for the suggestion.
The reference to add a new language in ast-grep is documented here:
https://ast-grep.github.io/contributing/add-lang.html

You can also try using dynamic library to support non-builtin languages:

 https://ast-grep.github.io/advanced/custom-language.html

**Comment by alcroito** [comment]
Hi.

Is there any chance your stance has shifted around adding cmake language support to the core of ast-grep, since you commented on https://github.com/ast-grep/ast-grep/pull/983#issuecomment-2004985102 ?

ast-grep already supports bash, which is not really a build language, but is build-adjacent, and it is 47 on TIOBE. 

I've seen that the Solidity language support has been added recently, which scores 42 on TIOBE index.

TIOBE doesn't list a position for cmake, but i'd guess it's somewhere around bash popularity, perhaps slightly lower, and in my opinion is more useful for open-source development than Solidity is.

**Comment by HerringtonDarkholme** [comment]
While languages like Bash, Solidity, SQL, and HCL may be considered niche, they are undeniably dominant within their respective domains—scripting, EVM contract development, database manipulation, and configuration. Although they are not general-purpose programming languages, supporting them unlocks new use cases and attracts distinct user communities.

CMake, by contrast, is one of several build systems used in the C/C++ ecosystem, https://www.jetbrains.com/help/clion/project-models.html. Alternatives such as Make, Gradle, Ninja, Buck, and Starklang are also widely adopted. This diversity means CMake is not the sole standard, and its inclusion should be weighed accordingly.


 Other tools like [Semgrep](https://semgrep.dev/docs/supported-languages) do not currently support CMake. 

From a tooling perspective, or maybe making you feel better, languages like Nix, Solidity, SQL, and HCL are also not included in the playground.

**Comment by alcroito** [comment]
Thanks for the confirmation!

I can't say that it makes me feel better. :) 
I'm left wondering why a great tool needs to be limited to a specific subset of developers and languages, instead of making it available to everyone when the opportunity is there. 
I'd be happy if all other build languages were also supported, I need to deal with many of them as well.
I realise there's a potential maintenance cost though.

So I guess i'm left hoping for a brighter future.
