### ISSUE TITLE
[feature] Support global utility rules when executing single rule yaml file via `scan --rule`

### ISSUE THREAD

**Issue by obreitwi** [ast-grep/ast-grep#588]
# ⭐ Suggestion

Right now, when executing a single rule file, `ast-grep` [does not load](https://github.com/ast-grep/ast-grep/blob/86afc5865b42285106f232f01c0eb45708d134c3/crates/cli/src/scan.rs#L91) globally defined utility rules.

All utility rules used must be defined in the executed rule file. 
However, there is no warning printed that the corresponding matches 

# 💻 Use Cases

I'm currently getting my feet wet with `ast-grep` (very cool project, btw :+1:) by creating a collection of utility rewrite rules in a large convoluted code-base. I typically want to execute them one at a time to rewrite specific config values in a deeply nested terraform config (using the default parser installed by [nvim-treesitter](https://github.com/nvim-treesitter/nvim-treesitter) which worked like a charm :+1:).

Since identifying these config values is a bit involved I split them out into utility rules that I want to re-use even when executing single yaml files.

# :question: What is the desired behavior?

Currently `scan --config` and `scan --rule` are mutually exclusive.

Would it be permissible to load utility functions when executing single rule files? Or is there a constraint I am overlooking?

If it's fine I would also look into contributing this

Thanks!

**Comment by HerringtonDarkholme** [comment]
Hi, thanks for trying ast-grep! I'm glad to see you are taking advantage of nvim-treesitter to use custom language. Neat.

Regarding to `scan --rule`, this is a command for trying out ast-grep without setting up a project, so it will not discover global rules. 

There are two ways I can think of:
1. make `scan --rule` project aware when there is a `config`
2. make a new command argument for `scan --config --rule-id` to run only specific rule
