### ISSUE TITLE
Playground: Add rewriting suppot to playground

### ISSUE THREAD

**Issue by jd-solanki** [ast-grep/ast-grep#60]
Currently, I am writing automation for my Vue project and due to AST headache, I am using REGEX to replace the content.

I found ast-grep and it looks promising ❤️ 

One thing missing in playground compared to CLI mode is rewriting. Can you please add it so someone can just paste and try it before running on CLI?

> _P.S. It will be great if you add more examples to docs_

**Comment by HerringtonDarkholme** [comment]
Hi @jd-solanki ! Thanks for the interest! Actually there is already a diff panel in the playground. [See this link](https://ast-grep.github.io/playground.html#eyJtb2RlIjoiQ29uZmlnIiwibGFuZyI6ImphdmFzY3JpcHQiLCJxdWVyeSI6ImNvbnNvbGUubG9nKCRNQVRDSCkiLCJjb25maWciOiIjIENvbmZpZ3VyZSBSdWxlIGluIFlBTUxcbnJ1bGU6XG4gIHBhdHRlcm46IGlmICh0cnVlKSB7ICQkJEEgfVxuZml4OlxuICAkJCRBIiwic291cmNlIjoiLyogQWxsIGNvbnNvbGUubG9nKCkgY2FsbCB3aWxsIGJlIGhpZ2hsaWdodGVkISovXG5cbmZ1bmN0aW9uIHRyeUFzdEdyZXAoKSB7XG4gIGNvbnNvbGUubG9nKCdIZWxsbyBXb3JsZCcpXG59XG5cbmNvbnN0IG11bHRpTGluZUV4cHJlc3Npb24gPVxuICBjb25zb2xlXG4gICAubG9nKCdBbHNvIG1hdGNoZWQhJylcblxuaWYgKHRydWUpIHtcbiAgY29uc3Qgbm90VGhpcyA9ICdjb25zb2xlLmxvZyhcIm5vdCBtZVwiKSdcbn0ifQ==)

<img width="752" alt="image" src="https://user-images.githubusercontent.com/2883231/193284540-f880f44c-2901-4cc0-b021-a123b0a43f7b.png">

**Comment by jd-solanki** [comment]
Ohk, great!
