### ISSUE TITLE
[bug] Problems when using CLI

### ISSUE THREAD

**Issue by lty12b9b0a1** [ast-grep/ast-grep#600]
During use in CLI, I find something very thorny.
For instance, I want to match "-x" in code.(python)
The python code is:

```
y = - x
```

Then when running CLI, I get:

![image](https://github.com/ast-grep/ast-grep/assets/85532852/d311aff8-cc42-45be-93a5-f8d3ec1b5061)

This is very thorny if only use CLI. I guess yaml can solve this.
Maybe I did not use it correctly, but I think the pattern has already been wrapped inside ' " ', it should not be regard as argument.
But overall, this is a very powerful tool, thanks for your contribution~

**Comment by HerringtonDarkholme** [comment]
Thanks for giving ast grep a try.

Argument string starting with hyphen will be confused with option flag.
This is a common issue and Bing told me to use -- .

Say

```bash
sg -p -- -$X
```

**Comment by lty12b9b0a1** [comment]
![image](https://github.com/ast-grep/ast-grep/assets/85532852/e82197a4-90f0-4a0f-976b-703cea4eb074)

**Comment by lty12b9b0a1** [comment]
![image](https://github.com/ast-grep/ast-grep/assets/85532852/2b8e20e3-4129-45bd-9634-3a7fe2aeb605)
Still not work. Maybe I should try yaml to match this kind of pattern.
