### ISSUE TITLE
Docs for TS API?

### ISSUE THREAD

**Issue by jd-solanki** [ast-grep/ast-grep#61]
I am using TS project to modify my source code.

Can you please add docs on TS API?

Thanks :)

**Comment by HerringtonDarkholme** [comment]
Hi! Currently I don't have plan to officially support TS API since napi's overhead is quite high. 

However, you can try `npm install @ast-grep/napi` and the corresponding API is in the TS definition file.

https://github.com/ast-grep/ast-grep/blob/main/crates/napi/index.d.ts
