### ISSUE TITLE
[feature] add PHP support

### ISSUE THREAD

**Issue by makotot** [ast-grep/ast-grep#639]
# ⭐ Suggestion

https://en.wikipedia.org/wiki/PHP

# 💻 Use Cases
use ast-grep with PHP

**Comment by HerringtonDarkholme** [comment]
Hi 👋 I do want to support PHP!
One problem is that PHP variable naming is quite uncommon. I will give it a try

**Comment by HerringtonDarkholme** [comment]
In case any one is interested in grabbing this issue, https://ast-grep.github.io/contributing/add-lang.html is a good starting point.

**Comment by montchr** [comment]
I'm interested – I use PHP heavily at work. I may give it a try, though I have zero experience writing Rust so if someone else gets there first, that's great too.

Found this, but it doesn't look like it's on crates.io (unless the main tree-sitter project releases grammars in some less-discoverable way?):

https://github.com/tree-sitter/tree-sitter-php

**Comment by HerringtonDarkholme** [comment]
php is pretty hard to support. Consider

```php
$A::test();
```

This is parsed as HTML, instead of PHP code.

```php
<?php 
$A::test();
```
Only this is correct.

**Comment by HerringtonDarkholme** [comment]
Hi! php is supported experimentally by the name `php-dev`.

Currently the pattern does not work well since `$test->method()` is parsed as HTML.
To use it as actual code, you need to use yaml.

```
rule:
  pattern:
    context: '<?php $test->method'
    selector: expression_statement
```
