### ISSUE TITLE
[bug] tests fail when packaging `v0.12.1` for nixpkgs

### ISSUE THREAD

**Issue by cafkafk** [ast-grep/ast-grep#645]
When packaging for nixpkgs, I found that [test_unmatching_id](https://github.com/ast-grep/ast-grep/blob/9c78663c100123b4cc33b394e08f200cf6ade59f/crates/cli/src/verify/test_case.rs#L190) no longer works.
![2023-09-26_06-36](https://github.com/ast-grep/ast-grep/assets/89321978/de8c842a-e80d-4c81-a6d6-fe9df359b771)

Ignoring this just lead to even more tests failing.
![2023-09-26_07-05](https://github.com/ast-grep/ast-grep/assets/89321978/95d91e7d-e4dc-4c20-8d8c-3a6f83364035)

Please see https://github.com/NixOS/nixpkgs/pull/257385 for full details.

**Comment by HerringtonDarkholme** [comment]
Thanks for the report! I will give it a look later.

**Comment by montchr** [comment]
I'm wondering why the tests in CI here are passing, while the tests as run in Nixpkgs are failing?

**Comment by montchr** [comment]
@HerringtonDarkholme Can you push a patch release including b8bdffb5882a37caedf56f278b3a7d90a6401ab7? It looks like you may have fixed the bug already.

**Comment by HerringtonDarkholme** [comment]
Thanks for debugging! I will try release a new version soon!

**Comment by HerringtonDarkholme** [comment]
0.12.2 released! Thanks for reporting!

**Comment by cafkafk** [comment]
Thanks for the quick fix!
