### ISSUE TITLE
[question] how to match function call with package selector in Go.

### ISSUE THREAD

**Issue by QuantumGhost** [ast-grep/ast-grep#646]
# ⏯ Playground Link

[Playground link with relevant code](https://ast-grep.github.io/playground.html#eyJtb2RlIjoiQ29uZmlnIiwibGFuZyI6ImdvIiwicXVlcnkiOiJQcmludGxuKCQkJEFSR1MpIiwicmV3cml0ZSI6IiIsImNvbmZpZyI6IlxucnVsZTpcbiAgcGF0dGVybjogZm10LlByaW50bG4oJCQkQVJHUylcbiIsInNvdXJjZSI6ImZ1bmMgbWFpbigpIHtcbiAgICBmbXQuUHJpbnRsbihcIk9LXCIpXG59In0=)

# 💻 Code

Code:

```go
func main() {
    fmt.Println("OK")
}
```

Pattern:

```yml
rule:
  pattern: fmt.Println($$$ARGS)
```

# 🙁 Actual behavior

`fmt.Println("OK")` is not matched.

# 🙂 Expected behavior

The pattern above matches the line `fmt.Println("OK")`.

If we replace `fmt.Println` with `print`, ast-grep works as expected.

I guess it's an issue of tree-sitter, which parses `fmt.Println($ARGS)` or `fmt.Println($$$ARGS)` as `type_conversion_expression`.

[Example of simple pattern](https://ast-grep.github.io/playground.html#eyJtb2RlIjoiUGF0Y2giLCJsYW5nIjoiZ28iLCJxdWVyeSI6ImZtdC5QcmludGxuKCRBUkcpIiwicmV3cml0ZSI6IiIsImNvbmZpZyI6IiMgWUFNTCBSdWxlIGlzIG1vcmUgcG93ZXJmdWwhXG4jIGh0dHBzOi8vYXN0LWdyZXAuZ2l0aHViLmlvL2d1aWRlL3J1bGUtY29uZmlnLmh0bWwjcnVsZVxucnVsZTpcbiAgYW55OlxuICAgIC0gcGF0dGVybjogXG5maXg6XG4gIGxvZ2dlci5sb2coJEEpIiwic291cmNlIjoiLy8gY29uc29sZS5sb2coKSB3aWxsIGJlIG1hdGNoZWQgYnkgcGF0dGVybiFcbi8vIGNsaWNrIGRpZmYgdGFiIHRvIHNlZSByZXdyaXRlLlxuZnVuYyBtYWluKCkge1xuICAgIGZtdC5QcmludGxuKFwiT0tcIilcbn0ifQ)

**Comment by HerringtonDarkholme** [comment]
Thanks for giving ast-grep a try!
This is a commonly asked question and indeed it is quite common to other languages as well. 

ast-grep has a feature called contextual pattern, in which we can write pattern wrapped in other code as context.
So ambiguous code (like `fmt.Println`) will be parsed correctly.

https://ast-grep.github.io/guide/rule-config/atomic-rule.html#pattern


```yaml
rule:
  pattern:
    context: 'func t() { fmt.Println($$$A) }'
    selector: call_expression

```

https://ast-grep.github.io/playground.html#eyJtb2RlIjoiQ29uZmlnIiwibGFuZyI6ImdvIiwicXVlcnkiOiIiLCJyZXdyaXRlIjoiIiwiY29uZmlnIjoiXG5ydWxlOlxuICBwYXR0ZXJuOlxuICAgIGNvbnRleHQ6ICdmdW5jIHQoKSB7IGZtdC5QcmludGxuKCQkJEEpIH0nXG4gICAgc2VsZWN0b3I6IGNhbGxfZXhwcmVzc2lvblxuIiwic291cmNlIjoiZnVuYyBtYWluKCkge1xuICAgIGZtdC5QcmludGxuKFwiT0tcIilcbn0ifQ==

**Comment by QuantumGhost** [comment]
Thanks for answering. Maybe we should add this to FAQ / Go example?

**Comment by HerringtonDarkholme** [comment]
Contribution welcome :)
https://github.com/ast-grep/ast-grep.github.io/edit/main/website/catalog/index.md

**Comment by HerringtonDarkholme** [comment]
I have added it as a FAQ in ast-grep/ast-grep.github.io@b1b196797bbeafc373b91e924c1fffa4d6634a0b

**Comment by your-diary** [comment]
[The proposed solution](https://github.com/ast-grep/ast-grep/issues/646#issuecomment-1736713849) worked like a charm, but I don't know why, so I just opened a discussion for it:

- https://github.com/ast-grep/ast-grep/discussions/2375
