### ISSUE TITLE
[bug] Multi Row Replacement

### ISSUE THREAD

**Issue by lty12b9b0a1** [ast-grep/ast-grep#647]
If the code(expression) is written in multirow(for readability or some other things), then one more non-exsist space will be added in each of the line in the replacement.

I test different languages and different multirow expression. This always happens when something is in front of the multirow exp (such as 't = '). But it will not happen if the line started directly with that multirow exp.

I'm not sure whether it is bug, or it's just a feature.

The example is in this link.

[Playground Link](https://ast-grep.github.io/playground.html#eyJtb2RlIjoiUGF0Y2giLCJsYW5nIjoicHl0aG9uIiwicXVlcnkiOiIkWDEgPSAkWDIiLCJyZXdyaXRlIjoiJFgxID0gJFgyIiwiY29uZmlnIjoiIyBZQU1MIFJ1bGUgaXMgbW9yZSBwb3dlcmZ1bCFcbiMgaHR0cHM6Ly9hc3QtZ3JlcC5naXRodWIuaW8vZ3VpZGUvcnVsZS1jb25maWcuaHRtbCNydWxlXG5ydWxlOlxuICBhbnk6XG4gICAgLSBwYXR0ZXJuOiBjb25zb2xlLmxvZygkQSlcbiAgICAtIHBhdHRlcm46IGNvbnNvbGUuZGVidWcoJEEpXG5maXg6XG4gIGxvZ2dlci5sb2coJEEpIiwic291cmNlIjoidCA9IFtcbiAgMSxcbiAgMixcbiAgM1xuXSJ9)

# 💻 Code

Code:

```
t = [
    1,
    2,
    3
]
```

Pattern:

```
$X1 = $X2
```

Replace:

```
$X1 = $X2
```

# 🙁 Actual behavior

An unexpected space is added in each of the line.

# 🙂 Expected behavior

As the replace is the same with the match pattern, the expected replacement code should be same with the input.

**Comment by HerringtonDarkholme** [comment]
Hi I cannot reproduce the issue. I see the playground diff tab is a noop. 

<img width="316" alt="image" src="https://github.com/ast-grep/ast-grep/assets/2883231/483073db-ab70-44b6-a70c-fa6922e15658">


would you like to provide more info?

**Comment by lty12b9b0a1** [comment]
Emm, maybe I'm not explain it clearly. You can copy the text in the 'diff' back to the 'source', and see it again. Repeat this, there will be more and more indent in front of the line(line 2 ~ 5).

**Comment by lty12b9b0a1** [comment]
> Hi I cannot reproduce the issue. I see the playground diff tab is a noop.
> 
> <img alt="image" width="316" src="https://user-images.githubusercontent.com/2883231/271466534-483073db-ab70-44b6-a70c-fa6922e15658.png">
> would you like to provide more info?

In source code, line 2-5 have only 2 space in front of the code. But in diff, it has 3. I dont' know where is the extra space comes from.

**Comment by HerringtonDarkholme** [comment]
Oh, gotcha. Thanks for the explanation.

**Comment by HerringtonDarkholme** [comment]
Just an update, I'm fixing this now
