### ISSUE TITLE
[bug] Cannot match Rust parameter

### ISSUE THREAD

**Issue by kaleidawave** [ast-grep/ast-grep#648]
# ⏯ Playground Link

[Playground link with relevant code](https://ast-grep.github.io/playground.html#eyJtb2RlIjoiUGF0Y2giLCJsYW5nIjoicnVzdCIsInF1ZXJ5IjoiJFA6ICZtdXQgU3RyaW5nIiwicmV3cml0ZSI6IiRQOiBTdHJpbmciLCJjb25maWciOiIjIFlBTUwgUnVsZSBpcyBtb3JlIHBvd2VyZnVsIVxuIyBodHRwczovL2FzdC1ncmVwLmdpdGh1Yi5pby9ndWlkZS9ydWxlLWNvbmZpZy5odG1sI3J1bGVcbnJ1bGU6XG4gIGFueTpcbiAgICAtIHBhdHRlcm46ICZtdXQgU3RyaW5nXG5maXg6XG4gIFN0cmluZyIsInNvdXJjZSI6ImZuIHgoYTogJm11dCBTdHJpbmcpIHtcclxuICAgIFxyXG59In0=)

# 💻 Code

Code:

```rust
fn x(a: &mut String) {
    
}
```

Pattern:

```yml
rule:
  any:
    - pattern: &mut String
fix:
  String
```

# 🙁 Actual behavior

Doesn't match the parameter

# 🙂 Expected behavior
It should match the parameter and output
```rust
fn x(a: String) {
    
}
```

**Comment by HerringtonDarkholme** [comment]
Hi, thanks for trying out ast-grep.

ast-grep is based on syntax, so

> Pattern code must be valid code that tree-sitter can parse.

https://ast-grep.github.io/guide/pattern-syntax.html#pattern-matching

<img width="397" alt="image" src="https://github.com/ast-grep/ast-grep/assets/2883231/0e74afbe-8479-495e-ac9a-b930ecb500a1">

You can construct a `pattern` using its object style API. https://ast-grep.github.io/reference/rule.html#pattern

<img width="800" alt="image" src="https://github.com/ast-grep/ast-grep/assets/2883231/4d9d55b8-f66d-4bf4-91f0-e32c3f02f2e3">


https://ast-grep.github.io/playground.html#eyJtb2RlIjoiQ29uZmlnIiwibGFuZyI6InJ1c3QiLCJxdWVyeSI6IiRQOiAmbXV0IFN0cmluZyIsInJld3JpdGUiOiIkUDogU3RyaW5nIiwiY29uZmlnIjoiIyBZQU1MIFJ1bGUgaXMgbW9yZSBwb3dlcmZ1bCFcbiMgaHR0cHM6Ly9hc3QtZ3JlcC5naXRodWIuaW8vZ3VpZGUvcnVsZS1jb25maWcuaHRtbCNydWxlXG5ydWxlOlxuICBwYXR0ZXJuOlxuICAgIHNlbGVjdG9yOiBwYXJhbWV0ZXJcbiAgICBjb250ZXh0OiAnZm4gbigkQTogJm11dCBTdHJpbmcpIHt9J1xuZml4OlxuICAnJEE6IFN0cmluZyciLCJzb3VyY2UiOiJmbiB4KGE6ICZtdXQgU3RyaW5nKSB7XHJcbiAgICBcclxufSJ9

**Comment by HerringtonDarkholme** [comment]
I have also added it as a FAQ in ast-grep/ast-grep.github.io@b1b196797bbeafc373b91e924c1fffa4d6634a0b

**Comment by kaleidawave** [comment]
Cool, so by default the `pattern` has to parse to a statement like AST? And using the `selector` field I can pull out the specific part I want to match?

Tool looks awesome BTW!

**Comment by HerringtonDarkholme** [comment]
> so by default the pattern has to parse to a statement like AST? And using the selector field I can pull out the specific part I want to match?

Yes! It is! Thanks for the summary I will incorporate it in the doc!
