### ISSUE TITLE
[RFC] ast-grep python API

### ISSUE THREAD

**Issue by HerringtonDarkholme** [ast-grep/ast-grep#672]
# Background

Related to #389. Currently ast-grep ships YAML rule and napi API. Both have dictionary-like APIs.  

Example in JS

```javascript
import { js } from '@ast-grep/napi';

const source = `console.log("hello world")`
const ast = js.parse(source)
const node = ast.root().find({
  rule: {
    kind: 'property_identifier',
    inside: {
      kind: 'pair'
    }
  }
})
```

# Dictionary API in Python
We can use similar dictionary style API in Python too. The example above will be 

The find method has signature like this

```python
class SgNode:
  def find(self, rule: Optional[Dict] = None, **rule_kwargs: Dict) -> SgNode:
     pass # reference only
```

1. Use with rule dictionary
```python
from ast_grep_pyo3 import SgRoot
ast = SgRoot('print(123)', 'python')
node = ast.root().find({
  "rule": dict(
    kind = 'property_identifier',
    inside=dict(kind = 'pair')
  )
})
```

2. Use with kwargs
```python
node = ast.root().find(
  kind = 'property_identifier',
  inside = dict(kind = 'pair'),
)
```

**Props**
* no new API introduced
* users can copy code from YAML

**Cons**
* API is not Pythonic

---

~~Pythonic API (abandoned)~~

```python
from ast_grep_pyo3 import SgRoot
ast = SgRoot('print(123)', 'python')
node = ast.root().find(
  All(
    Kind('identifier'),
    Inside(rule=Kind('pair'), stop_by = 'neighbor')
  )
)
```

**Props**
* Pythonic
* Has better typing/completion for Python users.

**Cons**
* users need learn extra stuffs
* playground output needs translation

**Comment by HerringtonDarkholme** [comment]
@q0w would you like to give some insights on the API design? You are an active Python and ast-grep user! Any input will be valued and appreciated. Thanks! 🤝

**Comment by Lynskylate** [comment]
It might be a better idea to refer to bs4's api, some possible api design
```python
ast = SgRoot('print(123)', python)
ast.find('identifier', stop_by='neighbor')
```

**Comment by Zheaoli** [comment]
Actually, I prefer plan1 not plan2.

Keep it as simple as we can(

**Comment by q0w** [comment]
You can improve type hints with TypedDict + Required/NotRequired annotations for plan1

**Comment by HerringtonDarkholme** [comment]
Thank you for all your inputs! I will roll out a new design and update it in the comments! 

Appreciate your help!

**Comment by HerringtonDarkholme** [comment]
Tracked in another issue
