### ISSUE TITLE
[feature] lsp documentation

### ISSUE THREAD

**Issue by chrisgrieser** [ast-grep/ast-grep#697]
Currently, the documentation on how to use ast-grep as LSP is rather sparse. I got it working in nvim, via `vim.lsp.start`, but commonly, LSPs have settings, initialization options, code actions (fixing stuff), etc. – even if there isn't a lot (yet), *knowing* that there is not much to configure would be useful.

# ⭐ Suggestion
1. Add some documentation on the LSP to the docs.
2. Add some documentation to `sg lsp --help`

# 💻 Use Cases
I create a PR to make it easier to add in the LSP in nvim: https://github.com/neovim/nvim-lspconfig/pull/2880
It works basically, but having being able to potentially configure more stuff could be useful

**Comment by HerringtonDarkholme** [comment]
Wow! Thanks for your question and contribution to nvim-lspconfig!

LSP now is somewhat crude and does not have configurations. 

Would you like to provide some advice on configuration options? Appreciate it! I will implement them and document them~

**Comment by 0xdevalias** [comment]
I noticed this was closed by this commit:

- https://github.com/ast-grep/ast-grep.github.io/commit/4270de992f3e6197724bb95de4242a0f10f8b069

But was wondering, should the `textDocument/didOpen`, `textDocument/didChange`, `textDocument/didClose` dotpoints in those docs link to something as they did above in https://github.com/ast-grep/ast-grep/issues/697#issuecomment-1802581627 ?

> Client capability:
> 
> * [textDocument/didOpen](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_didOpen)
> * [textDocument/didChange](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_didChange)
> * [textDocument/didClose](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_didClose)

**Comment by HerringtonDarkholme** [comment]
added @0xdevalias

**Comment by 0xdevalias** [comment]
> added

@HerringtonDarkholme Not sure if you misread what I said above, or it hasn't been pushed, but that doesn't seem to be the case?

- https://github.com/ast-grep/ast-grep.github.io/commits/4270de992f3e6197724bb95de4242a0f10f8b069/website/guide/tools/editors.md

Still points to this commit as the latest, which doesn't have the links I was asking about:

- https://github.com/ast-grep/ast-grep.github.io/commit/4270de992f3e6197724bb95de4242a0f10f8b069

Specifically:

> should the `textDocument/didOpen`, `textDocument/didChange`, `textDocument/didClose` dotpoints in those docs link to something

**Comment by HerringtonDarkholme** [comment]
https://github.com/ast-grep/ast-grep.github.io/commit/45dd4b13f5416dc87045a73e72d82f68a2a8e8ac

**Comment by 0xdevalias** [comment]
@HerringtonDarkholme Awesome, thankyou! :)
