### ISSUE TITLE
[bug] can't find some nested rust macro

### ISSUE THREAD

**Issue by eatradish** [ast-grep/ast-grep#702]
# ⏯ Playground Link

https://ast-grep.github.io/playground.html#eyJtb2RlIjoiUGF0Y2giLCJsYW5nIjoicnVzdCIsInF1ZXJ5IjoiZmwhKCQkJEFSR1MpIiwicmV3cml0ZSI6IiIsImNvbmZpZyI6IiMgWUFNTCBSdWxlIGlzIG1vcmUgcG93ZXJmdWwhXG4jIGh0dHBzOi8vYXN0LWdyZXAuZ2l0aHViLmlvL2d1aWRlL3J1bGUtY29uZmlnLmh0bWwjcnVsZVxucnVsZTpcbiAgYW55OlxuICAgIC0gcGF0dGVybjogY29uc29sZS5sb2coJEEpXG4gICAgLSBwYXR0ZXJuOiBjb25zb2xlLmRlYnVnKCRBKVxuZml4OlxuICBsb2dnZXIubG9nKCRBKSIsInNvdXJjZSI6IiAgICBwcmludGVyXG4gICAgICAgIC5wcmludChmb3JtYXQhKFxuICAgICAgICAgICAgXCJ7fVxcblwiLFxuICAgICAgICAgICAgZmwhKFxuICAgICAgICAgICAgICAgIFwib21hLW1heVwiLFxuICAgICAgICAgICAgICAgIGEgPSBzdHlsZShmbCEoXCJpbnN0YWxsXCIpKS5ncmVlbigpLnRvX3N0cmluZygpLFxuICAgICAgICAgICAgICAgIGIgPSBzdHlsZShmbCEoXCJyZW1vdmVcIikpLnJlZCgpLnRvX3N0cmluZygpLFxuICAgICAgICAgICAgICAgIGMgPSBzdHlsZShmbCEoXCJ1cGdyYWRlXCIpKS5jb2xvcjI1Nig4NykudG9fc3RyaW5nKCksXG4gICAgICAgICAgICAgICAgZCA9IHN0eWxlKGZsIShcImRvd25ncmFkZVwiKSkueWVsbG93KCkudG9fc3RyaW5nKCksXG4gICAgICAgICAgICAgICAgZSA9IHN0eWxlKGZsIShcInJlaW5zdGFsbFwiKSkuYmx1ZSgpLnRvX3N0cmluZygpXG4gICAgICAgICAgICApXG4gICAgICAgICkpXG4gICAgICAgIC5vaygpO1xuIn0=

# 💻 Code

Code:

```rust
    printer
        .print(format!(
            "{}\n",
            fl!(
                "oma-may",
                a = style(fl!("install")).green().to_string(),
                b = style(fl!("remove")).red().to_string(),
                c = style(fl!("upgrade")).color256(87).to_string(),
                d = style(fl!("downgrade")).yellow().to_string(),
                e = style(fl!("reinstall")).blue().to_string()
            )
        ))
        .ok();
```

Pattern:

```yml
# YAML Rule is more powerful!
# https://ast-grep.github.io/guide/rule-config.html#rule
rule:
  any:
    - pattern: fl!($$$ARGS)
```

# 🙁 Actual behavior

Unable to match its results

# 🙂 Expected behavior

Should it match its outermost and inner layers?

**Comment by HerringtonDarkholme** [comment]
Rust macro is parsed as token tree. So a macro inside another macro should be matched separately.
You can [inspect the ast output](https://ast-grep.github.io/reference/playground.html) in the playground. 

<img width="691" alt="image" src="https://github.com/ast-grep/ast-grep/assets/2883231/d7261889-83e5-4e4f-88ae-423fa3eaaad5">
