### ISSUE TITLE
[bug] Pattern from Playground not working with ast-grep (call with surrounding arguments)

### ISSUE THREAD

**Issue by last-partizan** [ast-grep/ast-grep#718]
Thank you for this project, this is game-changer! but i found what looks like a small bug:

I try to replace argument in my field definition, and it doesn't work in console, but working in playground.

I'm trying to replace `blank=True` with `required=False`, but this argument can be surrounded by other
```
name = fields.CharField(blank=True, help_text="...")
```

So, i try to use `'fields.$C($$$A blank=True $$$B)'`, and it works in Playground but doesn't work with the app.

# ⏯ Playground Link

https://ast-grep.github.io/playground.html#eyJtb2RlIjoiUGF0Y2giLCJsYW5nIjoicHl0aG9uIiwicXVlcnkiOiJmaWVsZHMuJEMoJCQkQSBibGFuaz1UcnVlICQkJEIpIiwicmV3cml0ZSI6ImZpZWxkcy4kQygkJCRBIHJlcXVpcmVkPUZhbHNlICQkJEIpIiwiY29uZmlnIjoiIyBZQU1MIFJ1bGUgaXMgbW9yZSBwb3dlcmZ1bCFcbiMgaHR0cHM6Ly9hc3QtZ3JlcC5naXRodWIuaW8vZ3VpZGUvcnVsZS1jb25maWcuaHRtbCNydWxlXG5ydWxlOlxuICBhbnk6XG4gICAgLSBwYXR0ZXJuOiBjb25zb2xlLmxvZygkQSlcbiAgICAtIHBhdHRlcm46IGNvbnNvbGUuZGVidWcoJEEpXG5maXg6XG4gIGxvZ2dlci5sb2coJEEpIiwic291cmNlIjoiXG5jbGFzcyBBdHRhY2hlZEZpbGUoRG9jdW1lbnQpOlxuICAgIG5hbWUgPSBmaWVsZHMuU3RyaW5nRmllbGQobWF4X2xlbmd0aD01MTIsIGJsYW5rPVRydWUpXG4gICAgYmxhbmsxID0gZmllbGRzLkZpbGVGaWVsZChibGFuaz1UcnVlKVxuICAgIGJsYW5rMiA9IGZpZWxkcy5GaWxlRmllbGQoYmxhbms9VHJ1ZSwgaGVscF90ZXh0PVwiXCIpXG4gICAgc2lnbiA9IGZpZWxkcy5TdHJpbmdGaWVsZChtYXhfbGVuZ3RoPTQwLCBkZWZhdWx0PVwiXCIpXG4gICAgY3JlYXRlZCA9IGZpZWxkcy5EYXRlVGltZUZpZWxkKGRlZmF1bHQ9dGltZXpvbmUubm93KVxuICAgIHJlbW92ZV9hZnRlciA9IGZpZWxkcy5EYXRlVGltZUZpZWxkKFxuICAgICAgICBoZWxwX3RleHQ9XCJSZW1vdmVkIGFmdGVyIHRoaXMgZGF0ZVwiLFxuICAgICAgICBudWxsPVRydWUsIGJsYW5rPVRydWUsXG4gICAgKSJ9

# 💻 Code

Save code to file and try:

```
> ast-grep --lang=python --pattern 'fields.$C($$$A blank=True $$$B)' /tmp/test.py
> 
```

Pattern:

# 🙁 Actual behavior

Pattern matches nothing

# 🙂 Expected behavior

It finds 4 matches.

**Comment by HerringtonDarkholme** [comment]
Thanks! I will give it a look later!

**Comment by HerringtonDarkholme** [comment]
I briefly looked at the input and looks like the pattern is not well formed. More specifically, `call($$$A arg $$$B)` is not a valid code.

ast-grep will try to ignore the error but the matching is not guaranteed to work. (for various reasons, e.g. different tree-sitter lib deps, different text encoding)

<img width="438" alt="image" src="https://github.com/ast-grep/ast-grep/assets/2883231/8f9993f9-4808-4186-840b-61d110cb30cf">

I would suggest using several patterns to achieve the same effect.

```
ast-grep --lang=python --pattern 'fields.$C($$$A, blank=True, $$$B)' /tmp/test.py
ast-grep --lang=python --pattern 'fields.$C($$$A, blank=True)' /tmp/test.py
ast-grep --lang=python --pattern 'fields.$C(blank=True)' /tmp/test.py
ast-grep --lang=python --pattern 'fields.$C(blank=True, $$$B)' /tmp/test.py
```

Alternatively, you can also use YAML rule.

https://ast-grep.github.io/playground.html#eyJtb2RlIjoiQ29uZmlnIiwibGFuZyI6InB5dGhvbiIsInF1ZXJ5IjoiZmllbGRzLiRDKCQkJEEgYmxhbms9VHJ1ZSAkJCRCKSIsInJld3JpdGUiOiJmaWVsZHMuJEMoJCQkQSByZXF1aXJlZD1GYWxzZSAkJCRCKSIsImNvbmZpZyI6InJ1bGU6XG4gIGtpbmQ6IGtleXdvcmRfYXJndW1lbnRcbiAgcmVnZXg6IGJsYW5rPVRydWVcbmZpeDogcmVxdWlyZWQ9RmFsc2UiLCJzb3VyY2UiOiJcbmNsYXNzIEF0dGFjaGVkRmlsZShEb2N1bWVudCk6XG4gICAgbmFtZSA9IGZpZWxkcy5TdHJpbmdGaWVsZChtYXhfbGVuZ3RoPTUxMiwgYmxhbms9VHJ1ZSlcbiAgICBibGFuazEgPSBmaWVsZHMuRmlsZUZpZWxkKGJsYW5rPVRydWUpXG4gICAgYmxhbmsyID0gZmllbGRzLkZpbGVGaWVsZChibGFuaz1UcnVlLCBoZWxwX3RleHQ9XCJcIilcbiAgICBzaWduID0gZmllbGRzLlN0cmluZ0ZpZWxkKG1heF9sZW5ndGg9NDAsIGRlZmF1bHQ9XCJcIilcbiAgICBjcmVhdGVkID0gZmllbGRzLkRhdGVUaW1lRmllbGQoZGVmYXVsdD10aW1lem9uZS5ub3cpXG4gICAgcmVtb3ZlX2FmdGVyID0gZmllbGRzLkRhdGVUaW1lRmllbGQoXG4gICAgICAgIGhlbHBfdGV4dD1cIlJlbW92ZWQgYWZ0ZXIgdGhpcyBkYXRlXCIsXG4gICAgICAgIG51bGw9VHJ1ZSwgYmxhbms9VHJ1ZSxcbiAgICApIn0=

<img width="1060" alt="image" src="https://github.com/ast-grep/ast-grep/assets/2883231/d89f2b6f-d200-4b46-b14c-2b7a07e6430f">

**Comment by last-partizan** [comment]
Thank you!

**Comment by last-partizan** [comment]
Another question here:

I want to add argument `required=True` for all fields, but this variants adds additional unneded comma. Is there better way?

https://ast-grep.github.io/playground.html#eyJtb2RlIjoiQ29uZmlnIiwibGFuZyI6InB5dGhvbiIsInF1ZXJ5IjoiZmllbGRzLiRDKCQkJEEgYmxhbms9VHJ1ZSAkJCRCKSIsInJld3JpdGUiOiJmaWVsZHMuJEMoJCQkQSByZXF1aXJlZD1GYWxzZSAkJCRCKSIsImNvbmZpZyI6ImlkOiBhZGQtcmVxdWlyZWQtYnktZGVmYXVsdFxubGFuZ3VhZ2U6IFB5dGhvblxucnVsZTpcbiAgYWxsOlxuICAgIC0gcGF0dGVybjogZmllbGRzLiRDKCQkJEEpXG4gICAgLSBub3Q6XG4gICAgICAgIGFueTpcbiAgICAgICAgICAtIHJlZ2V4OiByZXF1aXJlZD1cbiAgICAgICAgICAtIHJlZ2V4OiBibGFuaz1cbnRyYW5zZm9ybTpcbiAgTTE6XG4gICAgcmVwbGFjZTpcbiAgICAgIHNvdXJjZTogJCQkQVxuICAgICAgcmVwbGFjZTogJ14uKydcbiAgICAgIGJ5OiAnLCAnXG5maXg6IGZpZWxkcy4kQygkJCRBJE0xcmVxdWlyZWQ9VHJ1ZSkiLCJzb3VyY2UiOiJjbGFzcyBNZXNzYWdlKEVtYmVkZGVkRG9jdW1lbnQpOlxuICAgIGlkICA9IGZpZWxkcy5PYmplY3RJZEZpZWxkKClcbiAgICB1cGRhdGVkID0gZmllbGRzLkRhdGVUaW1lRmllbGQoZGVmYXVsdD10aW1lem9uZS5ub3cpXG4gICAgdHlwZSA9IGZpZWxkcy5TdHJpbmdGaWVsZChcbiAgICAgICAgbWF4X2xlbmd0aD0xMiwgZGVmYXVsdD1cImNvbW1lbnRcIiwgY2hvaWNlcz1UWVBFX0NIT0lDRVMsXG4gICAgKSJ9

**Comment by HerringtonDarkholme** [comment]
Off course!

Looks like you have already used a clever trick similar to https://ast-grep.github.io/catalog/c/#rewrite-method-to-function-call from [DasSurma](https://twitter.com/DasSurma)

The only thing need to change is tweaking the regex.

<img width="1021" alt="image" src="https://github.com/ast-grep/ast-grep/assets/2883231/215f0540-f9a9-45a4-8c50-d81859d19724">


https://ast-grep.github.io/playground.html#eyJtb2RlIjoiQ29uZmlnIiwibGFuZyI6InB5dGhvbiIsInF1ZXJ5IjoiZmllbGRzLiRDKCQkJEEgYmxhbms9VHJ1ZSAkJCRCKSIsInJld3JpdGUiOiJmaWVsZHMuJEMoJCQkQSByZXF1aXJlZD1GYWxzZSAkJCRCKSIsImNvbmZpZyI6ImlkOiBhZGQtcmVxdWlyZWQtYnktZGVmYXVsdFxubGFuZ3VhZ2U6IFB5dGhvblxucnVsZTpcbiAgYWxsOlxuICAgIC0gcGF0dGVybjogZmllbGRzLiRDKCQkJEEpXG4gICAgLSBub3Q6XG4gICAgICAgIGFueTpcbiAgICAgICAgICAtIHJlZ2V4OiByZXF1aXJlZD1cbiAgICAgICAgICAtIHJlZ2V4OiBibGFuaz1cbnRyYW5zZm9ybTpcbiAgTTE6XG4gICAgcmVwbGFjZTpcbiAgICAgIHNvdXJjZTogJCQkQVxuICAgICAgcmVwbGFjZTogJ14uK1teLF0kJ1xuICAgICAgYnk6ICcsICdcbmZpeDogZmllbGRzLiRDKCQkJEEkTTFyZXF1aXJlZD1UcnVlKSIsInNvdXJjZSI6ImNsYXNzIE1lc3NhZ2UoRW1iZWRkZWREb2N1bWVudCk6XG4gICAgaWQgID0gZmllbGRzLk9iamVjdElkRmllbGQoKVxuICAgIHVwZGF0ZWQgPSBmaWVsZHMuRGF0ZVRpbWVGaWVsZChkZWZhdWx0PXRpbWV6b25lLm5vdylcbiAgICB0eXBlID0gZmllbGRzLlN0cmluZ0ZpZWxkKFxuICAgICAgICBtYXhfbGVuZ3RoPTEyLCBkZWZhdWx0PVwiY29tbWVudFwiLCBjaG9pY2VzPVRZUEVfQ0hPSUNFUyxcbiAgICApIn0=

**Comment by last-partizan** [comment]
Beatiful! Thank you!
