### ISSUE TITLE
line number not clear on dark background

### ISSUE THREAD

**Issue by sibouras** [ast-grep/ast-grep#739]
right now the line number is using the theme's black color https://github.com/ast-grep/ast-grep/blob/116d1c519caca9e06d11e58a1824816860a07ed1/crates/cli/src/print/colored_print.rs#L585

`background` and `black` colors in dark themes are similar so its hard to see the line numbers

maybe the green color like ripgrep uses looks good on both dark and light backgrounds

**Comment by HerringtonDarkholme** [comment]
Thanks for your suggestion. I want to express that line number is less important so I chose the black color.
I will look at how to tweak the color.

**Comment by sibouras** [comment]
looks great, thanks
