### ISSUE TITLE
[feature] support languageGlobs for napi

### ISSUE THREAD

**Issue by zhiyuanzmj** [ast-grep/ast-grep#745]
# ⭐ Suggestion

How about add languageGlobs option to findInFiles.

# 💻 Use Cases

```tsx
html.findInFiles({
   languageGlobs: ['*.vue'],
   ...
})
```

**Comment by HerringtonDarkholme** [comment]
Nice addition!  This is not a too complex feature and contribution is welcome!

**Comment by ppppqp** [comment]
Hi, I am trying to implement this, but I have a few questions.
1. what is the definition of "languageGlobs" and what is ast-grep supposed to do when it finds a "*.vue" file (I think there's no vue sfc parser in ast-grep?) 
2. I think "languageGlobs" may be an optional config item. How will it interact with the "path" option? Will ast-grep look into the union?

Thanks!

**Comment by HerringtonDarkholme** [comment]
Hi you can see the relevant code here. 

https://github.com/ast-grep/ast-grep/blob/3c1e4babecd8364de9ae0db78b16dc9cab0325ae/crates/napi/src/lib.rs#L285-L328

And the doc for languageGlobs https://ast-grep.github.io/reference/sgconfig.html#languageglobs

**Comment by HerringtonDarkholme** [comment]
Fixed in #780 !
