### ISSUE TITLE
[feature] consider using fancy-regex to support look-around and backtracking

### ISSUE THREAD

**Issue by eugenesvk** [ast-grep/ast-grep#763]
# ⭐ Suggestion

Currently ast-grep regex support is missing a couple of features
> The regular expression is written in [Rust syntax](https://docs.rs/regex/latest/regex/), not the popular [PCRE like syntax](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions). So some features are not available like arbitrary look-ahead and back references."

However, there is this fancy regex crate that implements "look-around and backtracking" https://github.com/fancy-regex/fancy-regex, so it might be better to use that instead of the default regex

# 💻 Use Cases

Same use cases where you'd use regex, but richer and allowing for better matches

**Comment by HerringtonDarkholme** [comment]
Hi, thanks for the suggestion.

fancy-regex looks like not as mature as regex. I would await more feedback and benchmarks about fancy-regex for its integration.

**Comment by HerringtonDarkholme** [comment]
From fancy-regex's README

> Still in development, though the basic ideas are in place. Currently, the following features are missing:

The status is committed 7 years ago...

**Comment by eugenesvk** [comment]
Well, you could get feedback and benchmarks in the most important use case - AST-grepping - by adding that as an optional engine :)

Though from my "searching end user" perspective the issues linked are dwarfed by the lack of look-ahead and back-references, those I use often in alternative engines, and it's a big limitation of the "production ready" Rust's default one (even if the back-references,bugs in cases like `[\042\223\224\262\263\271]{2}\S{0,16}[\042\223\224\262\263\271]{2}` that I'll never encounter and some fuzzed incantation I'll also never use fails)
