### ISSUE TITLE
[bug] remove_dir_all RUSTSEC-2023-0018

### ISSUE THREAD

**Issue by jubalh** [ast-grep/ast-grep#765]
While packaging ast-grep 0.14.2 our tooling noted that it uses `remove_dir_all` in a certain version and might be affected by https://rustsec.org/advisories/RUSTSEC-2023-0018.

**Comment by HerringtonDarkholme** [comment]
Thanks for reporting! 

It is a transitive dependency from tempdir which is now deprecated.

https://docs.rs/tempfile/latest/tempfile/ tempfile looks a promising replacement for it.

**Comment by HerringtonDarkholme** [comment]
Released in 0.14.4!
