### ISSUE TITLE
[bug] Python wheel contains two copies of LICENSE

### ISSUE THREAD

**Issue by simonw** [ast-grep/ast-grep#766]
Download `ast_grep_cli-0.14.2-py3-none-macosx_10_7_x86_64.whl` from https://pypi.org/project/ast-grep-cli/#files and run the following command:
```bash
unzip -l ast_grep_cli-0.14.2-py3-none-macosx_10_7_x86_64.whl
```
Output:
```
  Length      Date    Time    Name
---------  ---------- -----   ----
     6207  12-03-2023 07:34   ast_grep_cli-0.14.2.dist-info/METADATA
      102  12-03-2023 07:34   ast_grep_cli-0.14.2.dist-info/WHEEL
     1077  12-03-2023 07:34   ast_grep_cli-0.14.2.dist-info/license_files/LICENSE
     1077  12-03-2023 07:34   ast_grep_cli-0.14.2.dist-info/license_files/LICENSE
 32865880  12-03-2023 07:34   ast_grep_cli-0.14.2.data/scripts/sg
 32865880  12-03-2023 07:34   ast_grep_cli-0.14.2.data/scripts/ast-grep
      639  12-03-2023 07:34   ast_grep_cli-0.14.2.dist-info/RECORD
---------                     -------
 65740862                     7 files
```
The `LICENSE` file is listed twice. I didn't know zip files could do that!

I'm pretty sure this doesn't actually matter - the wheel installs just fine. I only noticed this because I got this message when I tried to unzip the wheel myself:
```bash
unzip ast_grep_cli-0.14.2-py3-none-macosx_10_7_x86_64.whl
```
```
Archive:  ast_grep_cli-0.14.2-py3-none-macosx_10_7_x86_64.whl
  inflating: ast_grep_cli-0.14.2.dist-info/METADATA  
  inflating: ast_grep_cli-0.14.2.dist-info/WHEEL  
  inflating: ast_grep_cli-0.14.2.dist-info/license_files/LICENSE  
replace ast_grep_cli-0.14.2.dist-info/license_files/LICENSE? [y]es, [n]o, [A]ll, [N]one, [r]ename: 
```

**Comment by HerringtonDarkholme** [comment]
Hi Simon! Thanks for reporting. I will investigate it when I have time :) 

By the way, I truly appreciate your words on HN. I am so grateful you find the ast-grep's packaging useful. I spent a lot of time designing and making the tool usable for many scenarios.

**Comment by simonw** [comment]
It's really cool!

I blogged it https://simonwillison.net/2023/Dec/10/ast-grep/ and sent it out in my newsletter too: https://simonw.substack.com/p/datasette-enrichments-a-new-plugin

**Comment by HerringtonDarkholme** [comment]
Found the issue coming from https://github.com/PyO3/maturin/issues/861

**Comment by HerringtonDarkholme** [comment]
I created an upstream issue for duplicate license. https://github.com/PyO3/maturin/issues/2066

Track the issue in the maturin repo and close the issue for now.

**Comment by icp1994** [comment]
Instead of using `license-file`, I tried `include = ["/src/", "/tests/", "../../LICENSE"]` but it doesn't work according to the output of `cargo package --list --allow-dirty`. So maybe relative paths aren't supported under `include`? I could get it working by copying the root license file into the cli crate.
