### ISSUE TITLE
Setup CodeRabbit (uses ast-grep and AI to review PRs)

### ISSUE THREAD

**Issue by harjotgill** [ast-grep/ast-grep#769]
# ⭐ Suggestion

We are a big fan of `ast-grep`, and we recently started using it at [CodeRabbit](https://coderabbit.ai). We review pull requests with AI and use `gpt-4` to generate ast-grep search patterns to dive deep into the codebase and search for missing changes. We are getting excellent results so far.

We recommend setting up CodeRabbit in this project (it's free for all OSS projects) and seeing AI-powered `ast-grep` in action!

ast-grep is powering review comments such as these - https://github.com/openreplay/openreplay/pull/1775#discussion_r1425480406

**Comment by HerringtonDarkholme** [comment]
Hi @harjotgill I have enabled code rabbit but I didn't see any review coming in?

This is my dashboard. CR is detecting new pull requests and shows there are 2 reviews.

<img width="1291" alt="image" src="https://github.com/ast-grep/ast-grep/assets/2883231/b332e873-ae7b-4a3d-85ce-7d2d89dfeaed">

But I didn't see comment in the pull request.

https://github.com/ast-grep/ast-grep/pull/781

**Comment by HerringtonDarkholme** [comment]
Also, if you don't mind adding your logo in https://github.com/ast-grep/ast-grep/issues/373, I will add a link to CodeRabbit in ast-grep's home page :)

**Comment by guritfaq** [comment]
@HerringtonDarkholme  - 

Thanks for installing CodeRabbit. 
These file types are filtered out by default. However , you can change the filter pattern via the UI( under repositoiry settings) or by adding a yaml - https://coderabbit.ai/docs/get-started/customize-coderabbit. 

We will make a change to post a PR comment when the review is skipped because of the file path pattern.

**Comment by HerringtonDarkholme** [comment]
Wow, it works like a charm. Thanks!

**Comment by harjotgill** [comment]
> Wow, it works like a charm. Thanks!

Try chatting with the bot. Ask it anything about the codebase and it will generate ast-grep patterns :)

**Comment by HerringtonDarkholme** [comment]
@harjotgill CodeRabbit has amazing output! Thought chains + script execution makes me feel it understands my code. Great job!

**Comment by HerringtonDarkholme** [comment]
https://ast-grep.github.io/

Added via https://github.com/ast-grep/ast-grep.github.io/commit/5ff1eb81ae4998672bf775d7348ab8d5401641f8

**Comment by guritfaq** [comment]
Appreciate it. Also, thank you for the shout-out on X.
