### ISSUE TITLE
[feature] support import package automaticly

### ISSUE THREAD

**Issue by imcuttle** [ast-grep/ast-grep#774]
# ⭐ Suggestion

I want to fix the code which using global variable instead of package.

# 💻 Use Cases

### Before
```
const val = __global_value;
```

### Fixed
```
import { globalValue } from 'some-package';

const val = globalValue;
```

**Comment by HerringtonDarkholme** [comment]
Sorry, I don't know your question. Are you asking how to write rule? 
If so, https://ast-grep.github.io/guide/quick-start.html please read the documentation.

**Comment by imcuttle** [comment]
@HerringtonDarkholme  I want to know how to rewrite code by importing code.
The current rule replaces pattern simply.

**Comment by HerringtonDarkholme** [comment]
It's not possible at the moment. But it is tracked by https://github.com/ast-grep/ast-grep/issues/656

**Comment by HerringtonDarkholme** [comment]
Tracked by #656. I think we should discuss there for ideations.
