### ISSUE TITLE
[bug] please rename sg to ag (sg is now used in semgrep)

### ISSUE THREAD

**Issue by aryx** [ast-grep/ast-grep#778]
The semgrep program now includes a shortcut called 'sg' https://github.com/semgrep/semgrep/tree/develop/cli/bin
for semgrep, so it would be better to rename your 'sg' to 'ag'.

# ⏯ Playground Link

[Playground link with relevant code](https://ast-grep.github.io/playground.html)

# 💻 Code

Code:

```
```

Pattern:

```yml
```

# 🙁 Actual behavior

# 🙂 Expected behavior

**Comment by HerringtonDarkholme** [comment]
Hi Padioleau, thank you for dropping a comment on ast-grep! We appreciate your feedback and understand your concerns regarding the `sg` command name.

The release timing of our `sg` command overlaps with semgrep's, but it's important to note that ast-grep has been in circulation for approximately one year while semgrep's alias was added [one month ago](https://github.com/semgrep/semgrep/commits/develop/cli/bin/sg). 

Additionally, the `ag` alias is already claimed by the [silversearcher project](https://github.com/ggreer/the_silver_searcher). Adopting `ag` also creates conflicting command names. 
Indeed, `sg` itself has been used in the Linux ecosystem as switchgroup command for 16 years. Changing ast-grep's alias will not stop semgrep from conflicting with the Linux command.

To address potential conflicts and ensure a smooth user experience, maintaining both the full ast-grep command and the sg alias offers a [balanced solution](https://github.com/ast-grep/ast-grep/issues/56).  

This approach aligns with existing usage within ast-grep and minimizes the risk of confusion with other projects.

**Comment by aryx** [comment]
And what 's' stands for in sg in ast-grep ???
ast-grep is already a clear clone of semgrep ... I think using 'sg' for its alias is a bit insulting.
Maybe 'asg' ?

**Comment by HerringtonDarkholme** [comment]
Thank you for your comment on ast-grep. I am glad to hear from you and I value your input.

> And what 's' stands for in sg in ast-grep ???

The `s` stands for _syntax_ as in the Abstract Syntax Tree, which is on the [homepage](https://ast-grep.github.io/).

<img width="611" alt="image" src="https://github.com/ast-grep/ast-grep/assets/2883231/91fff1ed-974e-44aa-95f9-5ab4ca35685b">

Indeed, ast-grep does not have _semantic_ features like taint-analysis or constant propagation. And it is not designed to do so.

> ast-grep is already a clear clone of semgrep

I appreciate your interest in ast-grep and I would like to explain how it differs from semgrep. While both tools use abstract syntax trees to analyze code, they have different goals and features.  As previously explained elsewhere[1] [2], ast-grep offers unique capabilities (like a CSS selector-like rule) and caters to different user needs (refactoring and searching).

[1] https://news.ycombinator.com/item?id=38594457
[2] https://ast-grep.github.io/advanced/tool-comparison.html

> I think using 'sg' for its alias is a bit insulting.

I am sorry to hear that you find the name sg insulting. That was never my intention. The name sg was chosen to reflect the syntax-based approach of ast-grep and it has been used consistently since the first release in October 2022.

While I hold great admiration for the semgrep project and its author, the adoption of a later naming scheme shouldn't automatically restrict earlier names, would you agree? :)

**Comment by aryx** [comment]
As the semgrep author, I made the request; Of course you're free to ignore it. I think it's confusing to have a tool called ast-grep, which is clone of semgrep, and which uses 'sg' for its shortcut, while the tool is actually called ast-grep ... now if you don't see the obvious, there's not much I can do.

**Comment by HerringtonDarkholme** [comment]
Thank you for your reply again, and I value your input!

>  uses 'sg' for its shortcut, while the tool is actually called ast-grep 

ast-grep was designed to be fast and can be used frequently on command line as `rg`/`ag`/`grep`. Search finishes in sub second and typing the full `ast-grep` name defeats its purpose of being fast.

This was how I came up with the short name:
* ag: It was already taken by silversearcher
* sg: I was not aware of shadow-utils then but it does not conflict with OSX/windows utils
* tg: This instantly reminds me of telegram and also there was a package there https://github.com/vysheng/tg

I chose sg after considering several alternatives and finding it the most suitable for ast-grep.

> a tool called ast-grep, which is clone of semgrep,

ast-grep is inspired by semgrep, but it has many unique features that distinguish it from semgrep.

* A [CSS-inspired rule system](https://ast-grep.github.io/guide/rule-config/atomic-rule.html#kind) to precisely match syntax nodes.
* A [indentation sensitive rewrite](https://ast-grep.github.io/guide/rewrite-code.html#rewrite-is-indentation-sensitive) inspired by [ssr.nvim](https://github.com/cshuaimin/ssr.nvim)
* ast-grep's own innovation: [recursive utility rule](https://ast-grep.github.io/guide/rule-config/utility-rule.html)! A powerful and declarative construct that unlocks Turing-complete tree matching!
* A not so innovative but useful feature to [transform matched variable](https://ast-grep.github.io/guide/rewrite-code.html#use-transform-in-rewrite)
* A set of [APIs](https://ast-grep.github.io/guide/api-usage.html) for programmatic usage.

ast-grep doesn't have semantic features like semgrep. But it deserves the name of syntax-grep. I would be happy if you have time and can take a look at ast-grep's documentation site! As a quick spoiler, ast-grep can easily match [Python generator expression](https://github.com/ast-grep/ast-grep/discussions/430), while, to my best knowledge, it is challenging to do so in semgrep.

> now if you don't see the obvious, there's not much I can do.

It is not a shame to acknowledge ast-grep is inspired by semgrep. I have paid [respects](https://ast-grep.github.io/advanced/tool-comparison.html) [multiple times](https://ast-grep.github.io/guide/introduction.html#features) in the doc.

That said, I don't think it is confusing for users to misunderstand sg with semgrep/ast-grep. There are tons of [similar](https://www.npmjs.com/search?q=ast-grep&page=0&perPage=20) [projects](https://pypi.org/search/?q=ast-grep) on the internet where syntax-aware searching have similar names. Indeed, we already have predecessors like `more`/`less`, `git`/`tig`. Similar names for similar projects are quite common.

Thank you again for your reply and your interest in ast-grep. I hope this clarifies some of the questions and concerns you had. 

And I hope, if possible, the documentation site can pique your interest about its uniqueness! :)

**Comment by aryx** [comment]
Ok, I'll close then.
Thx indeed for the reference to semgrep in the doc.

**Comment by milahu** [comment]
both are wrong. both `ag` and `sg` are too short as program names

when users want alias names, they should learn to use their shell

```sh
alias sg=ast-grep
```
