### ISSUE TITLE
👎  npm i @ast-grep/cli -g 👎

### ISSUE THREAD

**Issue by ThomasGHenry** [ast-grep/ast-grep#79]
I look forward to trying this someday when I can install it! If this is working for anyone else, I'll come back with more details. For now, I have to run so it's just a friendly heads up. I'm on a MBP (intel) Monterey 12.6, fish shell, node 16.17.0, npm 8.15.0. 

Thanks! Good luck!

**Comment by HerringtonDarkholme** [comment]
What's your CLI output?

**Comment by HerringtonDarkholme** [comment]
Please try again.

**Comment by ThomasGHenry** [comment]
I think this was it. https://github.com/ast-grep/ast-grep/commit/62cb249394b42b52577e313e1c8308867708ba14 

It appears to be working now and I'm stoked!

Thanks!
