### ISSUE TITLE
[question] Unable to search for pattern using -p in cpp files

### ISSUE THREAD

**Issue by daedroza** [ast-grep/ast-grep#792]
# ⏯ Playground Link
[Playground link with relevant code](https://ast-grep.github.io/playground.html#eyJtb2RlIjoiUGF0Y2giLCJsYW5nIjoiY3BwIiwicXVlcnkiOiJTZWNvbmRTdGFnZU1haW4iLCJyZXdyaXRlIjoiIiwiY29uZmlnIjoiIyBZQU1MIFJ1bGUgaXMgbW9yZSBwb3dlcmZ1bCFcbiMgaHR0cHM6Ly9hc3QtZ3JlcC5naXRodWIuaW8vZ3VpZGUvcnVsZS1jb25maWcuaHRtbCNydWxlXG5ydWxlOlxuICBhbnk6XG4gICAgLSBwYXR0ZXJuOiBjb25zb2xlLmxvZygkQSlcbiAgICAtIHBhdHRlcm46IGNvbnNvbGUuZGVidWcoJEEpXG5maXg6XG4gIGxvZ2dlci5sb2coJEEpIiwic291cmNlIjoiI2luY2x1ZGUgXCJidWlsdGlucy5oXCJcbiNpbmNsdWRlIFwiZmlyc3Rfc3RhZ2VfaW5pdC5oXCJcbiNpbmNsdWRlIFwiaW5pdC5oXCJcbiNpbmNsdWRlIFwic2VsaW51eC5oXCJcbiNpbmNsdWRlIFwic3ViY29udGV4dC5oXCJcbiNpbmNsdWRlIFwidWV2ZW50ZC5oXCJcblxuI2luY2x1ZGUgPGFuZHJvaWQtYmFzZS9sb2dnaW5nLmg+XG5cbiNpZiBfX2hhc19mZWF0dXJlKGFkZHJlc3Nfc2FuaXRpemVyKVxuI2luY2x1ZGUgPHNhbml0aXplci9hc2FuX2ludGVyZmFjZS5oPlxuI2VuZGlmXG5cbiNpZiBfX2hhc19mZWF0dXJlKGFkZHJlc3Nfc2FuaXRpemVyKVxuLy8gTG9hZCBhc2FuLm9wdGlvbnMgaWYgaXQgZXhpc3RzIHNpbmNlIHRoZXNlIGFyZSBub3QgeWV0IGluIHRoZSBlbnZpcm9ubWVudC5cbi8vIEFsd2F5cyBlbnN1cmUgZGV0ZWN0X2NvbnRhaW5lcl9vdmVyZmxvdz0wIGFzIHRoZXJlIGFyZSBmYWxzZSBwb3NpdGl2ZXMgd2l0aCB0aGlzIGNoZWNrLlxuLy8gQWx3YXlzIGVuc3VyZSBhYm9ydF9vbl9lcnJvcj0xIHRvIGVuc3VyZSB3ZSByZWJvb3QgdG8gYm9vdGxvYWRlciBmb3IgZGV2ZWxvcG1lbnQgYnVpbGRzLlxuZXh0ZXJuIFwiQ1wiIGNvbnN0IGNoYXIqIF9fYXNhbl9kZWZhdWx0X29wdGlvbnMoKSB7XG4gICAgcmV0dXJuIFwiaW5jbHVkZV9pZl9leGlzdHM9L3N5c3RlbS9hc2FuLm9wdGlvbnM6ZGV0ZWN0X2NvbnRhaW5lcl9vdmVyZmxvdz0wOmFib3J0X29uX2Vycm9yPTFcIjtcbn1cblxuX19hdHRyaWJ1dGVfXygobm9fc2FuaXRpemUoXCJhZGRyZXNzXCIsIFwibWVtb3J5XCIsIFwidGhyZWFkXCIsIFwidW5kZWZpbmVkXCIpKSkgZXh0ZXJuIFwiQ1wiIHZvaWRcbl9fc2FuaXRpemVyX3JlcG9ydF9lcnJvcl9zdW1tYXJ5KGNvbnN0IGNoYXIqIHN1bW1hcnkpIHtcbiAgICBMT0coRVJST1IpIDw8IFwiSW5pdCAoZXJyb3Igc3VtbWFyeSk6IFwiIDw8IHN1bW1hcnk7XG59XG5cbl9fYXR0cmlidXRlX18oKG5vX3Nhbml0aXplKFwiYWRkcmVzc1wiLCBcIm1lbW9yeVwiLCBcInRocmVhZFwiLCBcInVuZGVmaW5lZFwiKSkpIHN0YXRpYyB2b2lkXG5Bc2FuUmVwb3J0Q2FsbGJhY2soY29uc3QgY2hhciogc3RyKSB7XG4gICAgTE9HKEVSUk9SKSA8PCBcIkluaXQ6IFwiIDw8IHN0cjtcbn1cbiNlbmRpZlxuXG51c2luZyBuYW1lc3BhY2UgYW5kcm9pZDo6aW5pdDtcblxuaW50IG1haW4oaW50IGFyZ2MsIGNoYXIqKiBhcmd2KSB7XG4jaWYgX19oYXNfZmVhdHVyZShhZGRyZXNzX3Nhbml0aXplcilcbiAgICBfX2FzYW5fc2V0X2Vycm9yX3JlcG9ydF9jYWxsYmFjayhBc2FuUmVwb3J0Q2FsbGJhY2spO1xuI2VuZGlmXG4gICAgLy8gQm9vc3QgcHJpbyB3aGljaCB3aWxsIGJlIHJlc3RvcmVkIGxhdGVyXG4gICAgc2V0cHJpb3JpdHkoUFJJT19QUk9DRVNTLCAwLCAtMjApO1xuICAgIGlmICghc3RyY21wKGJhc2VuYW1lKGFyZ3ZbMF0pLCBcInVldmVudGRcIikpIHtcbiAgICAgICAgcmV0dXJuIHVldmVudGRfbWFpbihhcmdjLCBhcmd2KTtcbiAgICB9XG5cbiAgICBpZiAoYXJnYyA+IDEpIHtcbiAgICAgICAgaWYgKCFzdHJjbXAoYXJndlsxXSwgXCJzdWJjb250ZXh0XCIpKSB7XG4gICAgICAgICAgICBhbmRyb2lkOjpiYXNlOjpJbml0TG9nZ2luZyhhcmd2LCAmYW5kcm9pZDo6YmFzZTo6S2VybmVsTG9nZ2VyKTtcbiAgICAgICAgICAgIGNvbnN0IEJ1aWx0aW5GdW5jdGlvbk1hcCYgZnVuY3Rpb25fbWFwID0gR2V0QnVpbHRpbkZ1bmN0aW9uTWFwKCk7XG5cbiAgICAgICAgICAgIHJldHVybiBTdWJjb250ZXh0TWFpbihhcmdjLCBhcmd2LCAmZnVuY3Rpb25fbWFwKTtcbiAgICAgICAgfVxuXG4gICAgICAgIGlmICghc3RyY21wKGFyZ3ZbMV0sIFwic2VsaW51eF9zZXR1cFwiKSkge1xuICAgICAgICAgICAgcmV0dXJuIFNldHVwU2VsaW51eChhcmd2KTtcbiAgICAgICAgfVxuXG4gICAgICAgIGlmICghc3RyY21wKGFyZ3ZbMV0sIFwic2Vjb25kX3N0YWdlXCIpKSB7XG4gICAgICAgICAgICByZXR1cm4gU2Vjb25kU3RhZ2VNYWluKGFyZ2MsIGFyZ3YpO1xuICAgICAgICB9XG4gICAgfVxuXG4gICAgcmV0dXJuIEZpcnN0U3RhZ2VNYWluKGFyZ2MsIGFyZ3YpO1xufVxuIn0=)

# 💻 Code

Code:

```
SecondStageMain
```

Pattern:

```
SecondStageMain
```

# 🙁 Actual behavior
sg -p 'SecondStageMain' should return the appropriate function in results. However, nothing is printed. I'm using `ast-grep 0.14.4`.

This only happens with cpp files and it's functions. I'm able to grep appropriately in java files. Unsure what else is broken.

# 🙂 Expected behavior
It should print the relevant results. The playground is able to detect tree-sitter node. However, unsure why the command line API fails.

**Comment by HerringtonDarkholme** [comment]
Playground shows the pattern has `type_identifier` kind.

<img width="419" alt="image" src="https://github.com/ast-grep/ast-grep/assets/2883231/a715f8f6-0956-4f85-9855-d807681ed341">

While the target code has kind `identifier`.

<img width="707" alt="image" src="https://github.com/ast-grep/ast-grep/assets/2883231/e83eef05-61b5-45ac-96ae-7fa429def2ae">


You can use YAML rule to avoid wrong pattern interpretation.

<img width="986" alt="image" src="https://github.com/ast-grep/ast-grep/assets/2883231/59c3f71d-753d-44d5-b268-86782375447c">

https://ast-grep.github.io/playground.html#eyJtb2RlIjoiQ29uZmlnIiwibGFuZyI6ImNwcCIsInF1ZXJ5IjoiU2Vjb25kU3RhZ2VNYWluIiwicmV3cml0ZSI6IiIsImNvbmZpZyI6InJ1bGU6XG4gIGtpbmQ6IGlkZW50aWZpZXJcbiAgcmVnZXg6IFNlY29uZFN0YWdlTWFpbiIsInNvdXJjZSI6InVzaW5nIG5hbWVzcGFjZSBhbmRyb2lkOjppbml0O1xuXG5pbnQgbWFpbihpbnQgYXJnYywgY2hhcioqIGFyZ3YpIHtcbiAgICBpZiAoYXJnYyA+IDEpIHtcbiAgICAgICAgaWYgKCFzdHJjbXAoYXJndlsxXSwgXCJzZWNvbmRfc3RhZ2VcIikpIHtcbiAgICAgICAgICAgIHJldHVybiBTZWNvbmRTdGFnZU1haW4oYXJnYywgYXJndik7XG4gICAgICAgIH1cbiAgICB9XG4gICAgcmV0dXJuIEZpcnN0U3RhZ2VNYWluKGFyZ2MsIGFyZ3YpO1xufVxuIn0=

**Comment by HerringtonDarkholme** [comment]
Pattern doc also has a relevant section about how to avoid unwanted parsing.

https://ast-grep.github.io/guide/rule-config/atomic-rule.html#pattern

**Comment by daedroza** [comment]
Hmm, do you have some examples like SecondStageMain($$$A) regex and what $$$ does?

The use-case for me is to use ast-grep as a search tool. So let's say I would like to find definition of SecondStageMain without the rule config, how would I achieve it?

Maybe I want to combine both references and definition, what kind of regex can I build to achieve that?

I can see that I can use method_declaration, method_invocation, class_declaration. However I don't want to pass my regex query in to rule.yml.

Many questions, but the tool and it's conceptualization is really great!

**Comment by HerringtonDarkholme** [comment]
> Hmm, do you have some examples like SecondStageMain($$$A) regex and what $$$ does?

Please read the doc. https://ast-grep.github.io/guide/pattern-syntax.html#multi-meta-variable

> I can see that I can use method_declaration, method_invocation, class_declaration. However I don't want to pass my regex query in to rule.yml.

You can specify multiple kinds by using https://ast-grep.github.io/guide/rule-config/atomic-rule.html#kind and https://ast-grep.github.io/guide/rule-config/composite-rule.html


> The use-case for me is to use ast-grep as a search tool. So let's say I would like to find definition of SecondStageMain without the rule config, how would I achieve it?

ast-grep's next version will have `inline-rules` option https://github.com/ast-grep/ast-grep/issues/396

**Comment by daedroza** [comment]
Thanks, I will play around with related information.

One last question, can I pass the rule.yml to `sg run` for one time search? I cannot see it in documentation but would be a super cool feature to have.

**Comment by HerringtonDarkholme** [comment]
> One last question, can I pass the rule.yml to sg run for one time search? I cannot see it in documentation but would be a super cool feature to have.

Yes, you can! 

```
sg scan -r rule.yml
```

https://ast-grep.github.io/guide/tooling-overview.html#run-one-single-query-or-one-single-rule

> What if I've a sgconfig.yml and it's relevant rules, would sg respect those with it's run one time search command?

Nope, `sg run` and `sg scan -r rule.yml` will not use the rules specified in sgconfig.yml. However, the custom languages registered in the sgconfig.yml will be loaded during run/scan.
