### ISSUE TITLE
[bug] Playground doesn't match the code while CLI does

### ISSUE THREAD

**Issue by nomyfan** [ast-grep/ast-grep#799]
# ⏯ Playground Link

[Playground link with relevant code](https://ast-grep.github.io/playground.html#eyJtb2RlIjoiUGF0Y2giLCJsYW5nIjoicnVzdCIsInF1ZXJ5IjoidGltZXIuc3RlcCgkQyk7IiwicmV3cml0ZSI6ImZvciBfIGluIDAuLiRDIHtcbiAgICB0aW1lci5zdGVwKCk7XG59IiwiY29uZmlnIjoiIyBZQU1MIFJ1bGUgaXMgbW9yZSBwb3dlcmZ1bCFcbiMgaHR0cHM6Ly9hc3QtZ3JlcC5naXRodWIuaW8vZ3VpZGUvcnVsZS1jb25maWcuaHRtbCNydWxlXG5ydWxlOlxuICBhbnk6XG4gICAgLSBwYXR0ZXJuOiBjb25zb2xlLmxvZygkQSlcbiAgICAtIHBhdHRlcm46IGNvbnNvbGUuZGVidWcoJEEpXG5maXg6XG4gIGxvZ2dlci5sb2coJEEpIiwic291cmNlIjoidGltZXIuc3RlcCgzNSk7In0=)

# 💻 Code

Code:

```
timer.step(35);
```

Pattern:

```yml
timer.step($C);
```

# 🙁 Actual behavior

It said "No match found". And I find there's an error in the browser console when I type the trailing semi-colon.

<img width="1406" alt="image" src="https://github.com/ast-grep/ast-grep/assets/19922814/330031a9-cee0-4466-8565-2086f7ae4855">

# 🙂 Expected behavior

It should be able to match the code like CLI.

<img width="379" alt="image" src="https://github.com/ast-grep/ast-grep/assets/19922814/5c00a29d-b53e-4e6d-9948-1d7d3d33880f">

**Comment by HerringtonDarkholme** [comment]
Thanks for the reporting!

**Comment by HerringtonDarkholme** [comment]
fixed in https://github.com/ast-grep/ast-grep.github.io/commit/465e8f34560a02bf74d96aa977c32e5eb3c0f48b
