### ISSUE TITLE
[bug] ast-grep-core pattern parsing is confusing

### ISSUE THREAD

**Issue by Boarders** [ast-grep/ast-grep#805]
when using `ast-grep-core` and writing the input pattern as a string, it seems confusing how to use the different kinds of metavariables work. In the following code I try to use an unnamed metavariable, but the debug print output tells me it is giving back a named variable.
# 💻 Code

Code:

```rust
    #[test]
    fn ast_grep_1() -> Result<(), String> {
        let lang: tree_sitter::Language = tree_sitter_cpp::language();
        let ast_lang: TSLanguage = TSLanguage::from(lang);
        let pat_str = "false || $$A";
        let pat = Pattern::try_new(pat_str, ast_lang).expect("pattern failed");
	println!("{:?}", pat);
        Ok(())
    }
```

# 🙁 Actual behavior

This gives the following output:
```bash
[false, ||, Named("", false), A]
```

# 🙂 Expected behavior

I'm not completely sure how the parsing should work when used as a library. I would have thought this gives an unnamed metavariable perhaps. If this is a mistaken impression for how it works as a library then let me know. I would also be interested if there is a more convenient way to be constructing patterns when using it as a library (it is a bit hard to figure out the best way to use the rust API.

**Comment by HerringtonDarkholme** [comment]
Thanks for reporting! 

There is no bug here but the name is confusing. `Named` here should be something like `Captured`, see https://ast-grep.github.io/guide/pattern-syntax.html#meta-variable-capturing

You also need to figure out the usage by reading a lot of source code. https://github.com/ast-grep/ast-grep/blob/main/crates/core/src/meta_var.rs#L189-L198

The rust API is not stable at the moment. e.g. I will probably rename the Named => Captured.

**Comment by Boarders** [comment]
Thanks, that is really helpful to know. I think I was led to my confusion by something else then. If I have the following code:
```rust
#[test]
    fn ast_grep_1() -> Result<(), String> {
	let sc : &str = "int main() { if (false || (true && false)) { return 0;} }";
        let lang: tree_sitter::Language = tree_sitter_cpp::language();
        let ast_lang: TSLanguage = TSLanguage::from(lang);
        let doc = StrDoc::new(sc, ast_lang.clone());
        let s_tree = doc.parse(None).expect("Unable to parse");
	let grep = AstGrep::new(sc, ast_lang.clone());
        let root : ast_grep_core::Node<_> = AstGrep::root(&grep);
        let pat_str = "true && $A";
        let pat = Pattern::try_new(pat_str, ast_lang).expect("pattern failed");
	println!("{:?}", pat);
	for p in ast_grep_core::Node::find_all(&root, pat) {
	    println!("match");
	    println!(
		"match is {:?}",
		Node::to_sexp(NodeMatch::get_node(&p))
	    );
	}
        Ok(())
    }
```

This pattern doesn't have any matches (though it does if I change `$A` to `false`). On the online playground it does seem to have a match. I think I may just be confused about something more basic, do you have any ideas?

Thanks btw for the really cool library!

**Comment by HerringtonDarkholme** [comment]
@Boarders are you verifying your code by looking at stdout?

The code runs in test so the output is swallowed by cargo.

**Comment by Boarders** [comment]
I am running with:
```bash
run test parse::tests::ast_grep_1 -- --exact --nocapture
```
When I run with the pattern:
```rust
let pat_str = "true && false";
```
I get:
```bash
match is "(binary_expression left: (true) right: (false))"
```
If I run with the pattern:
```rust
let pat_str = "true && $A";
```
then I get no matches output.

**Comment by HerringtonDarkholme** [comment]
You need to implement expando_char and pre_process_pattern like here

https://github.com/ast-grep/ast-grep/blob/main/crates/language/src/lib.rs

Please read the doc in the Language trait

<img width="1039" alt="image" src="https://github.com/ast-grep/ast-grep/assets/2883231/2f50a2fc-e623-4b36-b77e-f3d94da91322">

**Comment by Boarders** [comment]
Great, thank you for the help!
