### ISSUE TITLE
[feature] Support Makefiles

### ISSUE THREAD

**Issue by guettli** [ast-grep/ast-grep#844]
# ⭐ Suggestion

It would be nice if you could support Makefiles.

I see:
```
target:
    cmd1
    cmd2
```

I would like to know where `target` gets used.

**Comment by HerringtonDarkholme** [comment]
Hi, thanks for using ast-grep.

You can use custom language loading https://ast-grep.github.io/advanced/custom-language.html
 and this tree-sitter library to support make https://github.com/alemuller/tree-sitter-make
