### ISSUE TITLE
[feature] multiple languages in napi (JavaScript API)

### ISSUE THREAD

**Issue by infi-pc** [ast-grep/ast-grep#845]
# ⭐ Suggestion

Support in Javascript API all languages that are supported in CLI. [Docs](https://ast-grep.github.io/reference/api.html#supported-languages) say `@ast-grep/napi supports html, js, jsx, ts and tsx.` but it would be cool if it supported all other languages from https://ast-grep.github.io/reference/languages.html 

# 💻 Use Cases

I am building a NodeJS app that finds translation keys in many different codebases. Ast-grep would make it much easier than writing tree-sitter queries. 

Note: I can help by contributing to JS/TS if I get the right directions.

**Comment by HerringtonDarkholme** [comment]
Hi thanks for using ast-grep. Building a tree-sitter parser in napi docker image is pretty challenging. 

May I ask if it is possible to use https://ast-grep.github.io/guide/api-usage/py-api.html python API?

**Comment by infi-pc** [comment]
aha, thanks :) Python is too inconvenient for my current use case; sticking with just a tree-sitter query is easier for now, but maybe later :) 

I also plan to explore running it in a browser for my next use case; it seems to be possible from checking the playground repo. Btw. do you plan to publish `ast-grep-wasm` with some docs? It would be super cool.

**Comment by HerringtonDarkholme** [comment]
`ast-grep-wasm` is on the roadmap! But I don't have a precise timeline since there will be pretty many work there :(

**Comment by HerringtonDarkholme** [comment]
NAPI's ast-grep has supported the same language list of Python now!

https://ast-grep.github.io/guide/api-usage/js-api.html#use-other-language
