### ISSUE TITLE
[bug] Capturing parameter of JS arrow functions without parens

### ISSUE THREAD

**Issue by sseppola** [ast-grep/ast-grep#846]
# ⏯ Playground Link
[Playground link with relevant code](https://ast-grep.github.io/playground.html#eyJtb2RlIjoiUGF0Y2giLCJsYW5nIjoidHN4IiwicXVlcnkiOiIkJCRGTl9BUkdTID0+ICQkJEZOX0JPRFkiLCJyZXdyaXRlIjoiJCQkRk5fQVJHUyA9PiAkJCRGTl9CT0RZIiwiY29uZmlnIjoiIyBZQU1MIFJ1bGUgaXMgbW9yZSBwb3dlcmZ1bCFcbiMgaHR0cHM6Ly9hc3QtZ3JlcC5naXRodWIuaW8vZ3VpZGUvcnVsZS1jb25maWcuaHRtbCNydWxlXG5ydWxlOlxuICBhbnk6XG4gICAgLSBwYXR0ZXJuOiBjb25zb2xlLmxvZygkQSlcbiAgICAtIHBhdHRlcm46IGNvbnNvbGUuZGVidWcoJEEpXG5maXg6XG4gIGxvZ2dlci5sb2coJEEpIiwic291cmNlIjoiY29uc3QgYSA9IChzdGF0ZSwgcGF5bG9hZCkgPT4gcGF5bG9hZDtcbmNvbnN0IGIgPSBzdGF0ZSA9PiBzdGF0ZTtcbmNvbnN0IGMgPSAoc3RhdGUpID0+IHtcbiAgICByZXR1cm4gc3RhdGVcbn1cbiJ9)

![Screenshot 2024-01-12 at 15 55 28](https://github.com/ast-grep/ast-grep/assets/4065840/038a208d-ec18-409d-84c8-953d212f3744)

# 💻 Code

Code:

```
const a = (state, payload) => payload;
const b = state => state;
const c = (state) => {
    return state
}
```

Pattern:

```yml
$$$FN_ARGS => $$$FN_BODY
```

# 🙁 Actual behavior
I'm trying to write a pattern that captures the function args and body separately, which works for most cases as long as you wrap `$$$FN_ARGS` in `()`. This however doesn't capture arrow functions without `()` eg `state => state`, and I cannot figure out how to do it.

I expected my pattern to capture the parameters and body of the function, however the parameters are ignored and the `=>` is included in the body even when it is part of my pattern. The diff shows pretty clearly why this problematic.

# 🙂 Expected behavior

Capture function parameters and body separately because pattern separates them by `=>`

**Comment by HerringtonDarkholme** [comment]
JavaScript 's argument is one single AST node called `formal_parameters`.

Using `$$$ARGS` will wrongly match more nodes.

<img width="474" alt="image" src="https://github.com/ast-grep/ast-grep/assets/2883231/21f4540e-88de-4000-a4e8-167231751f53">

The solution is use single meta var

```js
$FN_ARGS => $$$FN_BODY
```

<img width="750" alt="image" src="https://github.com/ast-grep/ast-grep/assets/2883231/2f31a4eb-3ce4-4388-99cb-9e6977687d38">

**Comment by sseppola** [comment]
Brilliant, I didn't treat it as a single node in my script which was a much better approach. Thank you!
