### ISSUE TITLE
[feature] AST diff, with option to ignore variable/function name changes

### ISSUE THREAD

**Issue by 0xdevalias** [ast-grep/ast-grep#901]
# ⭐ Suggestion

It would be cool if ast-grep was able to show a diff between 2 files, but do it using the AST rather than just a raw text compare. Ideally we would be able to provide options to this, such as ignoring chunks where the only change is to a variable/function name (eg. for diffing minimised JavaScript webpack builds)

Ideally the output would be text still (not the AST tree), but the actually diffing could be done at the AST level.

# 💻 Use Cases

This would be really useful for minimising the noise when diffing minimised source builds looking for the 'real changes' between the builds (not just minimised variable names churning, etc)

Looking through current diff output formats shows all of the variable name changes as well, which equates to a lot of noise while looking for the relevant changes.

Some alternative potential workarounds I've considered are either pre-processing the files to standardize their variable/function names; and/or post-processing the diff output to try and detect when the only changes in a chunk are variable/function names, and then suppressing that chunk. Currently I'm just relying on `git diff --diff-algorithm=minimal -- thefile.js`

**Comment by HerringtonDarkholme** [comment]
Thanks for the suggestion. But I would think this feature should be implemented in https://github.com/Wilfred/difftastic or https://github.com/afnanenayet/diffsitter ?

**Comment by 0xdevalias** [comment]
> But I would think this feature should be implemented in [Wilfred/difftastic](https://github.com/Wilfred/difftastic) or [afnanenayet/diffsitter](https://github.com/afnanenayet/diffsitter) ?

@HerringtonDarkholme Yeah, that's fair enough. Originally I wasn't sure it would make sense in `ast-grep`; but then I saw this issue and figured maybe I had missed something/it could fit here:

- https://github.com/ast-grep/ast-grep/issues/155

**Comment by HerringtonDarkholme** [comment]
scope-aware diff is more like given a statement, finding its relevant surrounding function/scope to display diff.
It is something different from ast diffing.

**Comment by 0xdevalias** [comment]
> It is something different from ast diffing

That's fair enough. If this isn't a good fit, then definitely feel free to close. I'll take a look into those other two that you mentioned and see if it would work there better. Thanks for the tip! 🖤
