### ISSUE TITLE
[feature] search function invocation without specifying arguments.

### ISSUE THREAD

**Issue by winter-loo** [ast-grep/ast-grep#903]
# ⭐ Suggestion

Search function invocation without specifying arguments.

# 💻 Use Cases

```shell
ast-grep --pattern '$A = many_params_function(...)'
ast-grep --pattern 'many_params_function(...)'
````

Due to the function has many arguments, it could span multiple lines. A simple regex seems not possible. Is it possible implemented by `ast-grep` using AST?

Currently, If I specify only function name, `ast-grep` can not find the function invocation location.

**Comment by HerringtonDarkholme** [comment]
Thanks for using ast-grep.

Please read the doc https://ast-grep.github.io/guide/pattern-syntax.html#multi-meta-variable
