### ISSUE TITLE
[feature] Add TOML support

### ISSUE THREAD

**Issue by boidolr** [ast-grep/ast-grep#914]
# ⭐ Suggestion

Support of the TOML language.
A crate is already be available with https://crates.io/crates/tree-sitter-toml

# 💻 Use Cases

- Updating `pyproject.toml` to change versions across multiple repos.
- Tool configuration changes.

**Comment by HerringtonDarkholme** [comment]
I'm more leaning to not add toml since it is not maintained by the official community. Also see https://ast-grep.github.io/contributing/add-lang.html#requirements-and-constraints

**Comment by benkeil** [comment]
Would be a super helpful feature to update dependencies.
