### ISSUE TITLE
[feature] Add Elm support

### ISSUE THREAD

**Issue by Janiczek** [ast-grep/ast-grep#920]
# ⭐ Suggestion

Support for the Elm language.
There is a tree sitter at https://github.com/elm-tooling/tree-sitter-elm

# 💻 Use Cases

Simplifying patterns, eg.
```elm
xyz
|> Result.toMaybe
|> Maybe.map foo
|> Maybe.withDefault default
```
⬇️ 
```elm
xyz
|> Result.map foo
|> Result.withDefault default
```

**Comment by HerringtonDarkholme** [comment]
Hi! new language can be supported by custom language loading. https://ast-grep.github.io/advanced/custom-language.html
