### ISSUE TITLE
[bug] C++ matching doesn't work on function declaration body

### ISSUE THREAD

**Issue by bradphelan** [ast-grep/ast-grep#946]
# ⏯ [Playground link](https://ast-grep.github.io/playground.html#eyJtb2RlIjoiQ29uZmlnIiwibGFuZyI6ImNwcCIsInF1ZXJ5IjoiJFJFVCBGb28oaW50IHgsIGludCB5KXskJCRCT0RZfSIsInJld3JpdGUiOiIiLCJjb25maWciOiJpZDogbWF0Y2gtZnVuY3Rpb24tY2FsbFxubGFuZ3VhZ2U6IENQUFxucnVsZTpcbiAga2luZDogZnVuY3Rpb25fZGVmaW5pdGlvblxuICBwYXR0ZXJuOiAndm9pZCBGb28oJCQkQVJHUyl7JCQkRVhQUn0nXG4gICAiLCJzb3VyY2UiOiJcbnZvaWQgRm9vKGludCB4LCBpbnQgeSlcbntcblx0Zm9vKCk7XG5cdGJhcigpO1xufVxuXG52b2lkIEZvbyhpbnQgeClcbntcblx0Zm9vKCk7XG5cdGJhcigpO1xufVxuXG52b2lkIEZvbyhpbnQgeClcbntcblx0Zm9vKCk7XG5cdGJhcigpO1xuXHRiYXooKTtcbn1cblxuIn0=)

# 💻 Code

```
void Foo(int x, int y)
{
	foo();
	bar();
}

void Foo(int x)
{
	foo();
	bar();
}

void Foo(int x)
{
	foo();
	bar();
	baz();
}
```

Pattern:

```yml
id: match-function-call
language: CPP
rule:
  kind: function_definition
  pattern: 'void Foo($$$ARGS){$$$EXPR}'
```

# 🙁 Actual behavior

Nothing is matched

# 🙂 Expected behavior

It should match all three functions. The problematic issue is that $$$EXPR doesn't match the function body.

```
'void Foo($$$ARGS){$A;$B;$C}'
```

matches the third version but it doesn't seem possible to match the whole body irrespective of the body contents. There are some variations that match some things see this [link](https://ast-grep.github.io/playground.html#eyJtb2RlIjoiQ29uZmlnIiwibGFuZyI6ImNwcCIsInF1ZXJ5IjoiJFJFVCBGb28oaW50IHgsIGludCB5KXskJCRCT0RZfSIsInJld3JpdGUiOiIiLCJjb25maWciOiJpZDogbWF0Y2gtZnVuY3Rpb24tY2FsbFxubGFuZ3VhZ2U6IENQUFxucnVsZTpcbiAga2luZDogZnVuY3Rpb25fZGVmaW5pdGlvblxuICBwYXR0ZXJuOiAndm9pZCBGb28oJCQkQVJHUyl7JCQkRVhQUjA7JCQkRVhQUjF9J1xuICAgIiwic291cmNlIjoiXG52b2lkIEZvbygpXG57XG59XG5cbnZvaWQgRm9vKGludCB4LCBpbnQgeSlcbntcblx0Zm9vKCk7XG59XG5cbnZvaWQgRm9vKGludCB4KVxue1xuXHRmb28oKTtcblx0YmFyKCk7XG59XG5cbnZvaWQgRm9vKGRvdWJsZSB4KVxue1xuXHRmb28oKTtcblx0YmFyKCk7XG5cdGJheigpO1xufVxuXG4ifQ==)

Interesting the bug seems to go away when [switching to C](https://ast-grep.github.io/playground.html#eyJtb2RlIjoiUGF0Y2giLCJsYW5nIjoiYyIsInF1ZXJ5IjoiJFJFVCAkRlVOQygkJCRBUkdTKSB7ICQkJCB9IiwicmV3cml0ZSI6IiIsImNvbmZpZyI6ImlkOiBtYXRjaC1mdW5jdGlvbi1jYWxsXG5sYW5ndWFnZTogQ1BQXG5ydWxlOlxuICBraW5kOiBmdW5jdGlvbl9kZWZpbml0aW9uXG4gIHBhdHRlcm46IFxuICAgIGNvbnRleHQ6ICAgJyRSRVQgTmV4dE9mZnNldCgkJCRBUkdTKXskJCR9J1xuICAgIHNlbGVjdG9yOiAgZnVuY3Rpb25fZGVmaW5pdGlvblxuXG4gICAiLCJzb3VyY2UiOiJpbnQgZm9vKGludCBiYXIpIHtcbiAgcmV0dXJuIGJhcjtcbn1cblxudm9pZCBub29wKCkge31cblxudm9pZCBhZGQoaW50IGEsIGRvdWJsZSBiLCBzdGQ6OnN0cmluZyBjKSB7XG4gIGZvbyhhKTtcbiAgcmV0dXJuIGEgKyBiICsgYztcbn0ifQ==) but the same code does not work when the [parser is  c++](https://ast-grep.github.io/playground.html#eyJtb2RlIjoiUGF0Y2giLCJsYW5nIjoiY3BwIiwicXVlcnkiOiIkUkVUICRGVU5DKCQkJEFSR1MpIHsgJCQkIH0iLCJyZXdyaXRlIjoiIiwiY29uZmlnIjoiaWQ6IG1hdGNoLWZ1bmN0aW9uLWNhbGxcbmxhbmd1YWdlOiBDUFBcbnJ1bGU6XG4gIGtpbmQ6IGZ1bmN0aW9uX2RlZmluaXRpb25cbiAgcGF0dGVybjogXG4gICAgY29udGV4dDogICAnJFJFVCBOZXh0T2Zmc2V0KCQkJEFSR1MpeyQkJH0nXG4gICAgc2VsZWN0b3I6ICBmdW5jdGlvbl9kZWZpbml0aW9uXG5cbiAgICIsInNvdXJjZSI6ImludCBmb28oaW50IGJhcikge1xuICByZXR1cm4gYmFyO1xufVxuXG52b2lkIG5vb3AoKSB7fVxuXG52b2lkIGFkZChpbnQgYSwgZG91YmxlIGIsIHN0ZDo6c3RyaW5nIGMpIHtcbiAgZm9vKGEpO1xuICByZXR1cm4gYSArIGIgKyBjO1xufSJ9) 

Maybe the problem is with treesitter itself

``$RET $FUN($ARGS){$$$BODY}`` has the ``{$$$BODY}`` section parsed as *initializer_list* rather than *compound_statement*. You can force it to match as compound statement if you add in an extra semicolon as in
``$RET $FUN($ARGS){$$$BODY;}`` but this causes other issues and the matching will still fail

**Comment by HerringtonDarkholme** [comment]
Hi thanks for using ast-grep.

> $RET $FUN($ARGS){$$$BODY} has the {$$$BODY} section parsed as initializer_list rather than compound_statement.

Yes, this is tree-sitter's parsing decision and C++ is famous for its ambiguity. To avoid ambiguity, you can use https://ast-grep.github.io/guide/rule-config/atomic-rule.html rule.

**Comment by HerringtonDarkholme** [comment]
>  There are some variations that match some things 

The limitation of tree-sitter can be circumvented by tricky patterns and yaml rules. See 

https://ast-grep.github.io/playground.html#eyJtb2RlIjoiQ29uZmlnIiwibGFuZyI6ImNwcCIsInF1ZXJ5IjoiJFJFVCBGb28oaW50IHgsIGludCB5KXskJCRCT0RZfSIsInJld3JpdGUiOiIiLCJjb25maWciOiJpZDogbWF0Y2gtZnVuY3Rpb24tY2FsbFxubGFuZ3VhZ2U6IENQUFxucnVsZTpcbiAga2luZDogZnVuY3Rpb25fZGVmaW5pdGlvblxuICBhbnk6XG4gIC0gcGF0dGVybjogJ3ZvaWQgRm9vKCQkJEFSR1MpeyQkJEVYUFIwOyQkJEVYUFIxfSdcbiAgLSBwYXR0ZXJuOiAndm9pZCBGb28oJCQkQVJHUyl7fSdcbiIsInNvdXJjZSI6Ilxudm9pZCBGb28oKVxue1xufVxuXG52b2lkIEZvbyhpbnQgeCwgaW50IHkpXG57XG5cdGZvbygpO1xufVxuXG52b2lkIEZvbyhpbnQgeClcbntcblx0Zm9vKCk7XG5cdGJhcigpO1xufVxuXG52b2lkIEZvbyhkb3VibGUgeClcbntcblx0Zm9vKCk7XG5cdGJhcigpO1xuXHRiYXooKTtcbn1cblxuIn0=

**Comment by bradphelan** [comment]
May I propose adding a *where* operator by which it becomes possible to define the structure of match variables. For example

```
id: match-function-call
language: CPP
rule:
  kind: function_definition
  any:
  - pattern: '$RET $FN($$$ARGS){$BODY}'
    where:
      - 
        BODY:
          any:
            -pattern: {$$$}
            -pattern: {$$$;$$$}
fix: |
  $RET $FN($$ARGS) {
    $BODY
  }
```

or 

```
id: match-function-call
language: CPP
utils:
  patterns:
    function-body 
      any:
        -pattern: {$$$}
        -pattern: {$$$;$$$}
rule:
  kind: function_definition
  any:
  - pattern: '$RET $FN($$$ARGS){$BODY}'
    where:
      BODY:
        matches: function-body
```

**Comment by HerringtonDarkholme** [comment]
@bradphelan hi, we already have a `constraints` object in the rule.

https://ast-grep.github.io/reference/yaml.html#constraints
