### ISSUE TITLE
[bug] Metavariables in C++ seem to depend on length

### ISSUE THREAD

**Issue by Boarders** [ast-grep/ast-grep#947]
# ⏯ Playground Link

[Playground link with relevant code](https://ast-grep.github.io/playground.html#eyJtb2RlIjoiUGF0Y2giLCJsYW5nIjoiY3BwIiwicXVlcnkiOiJmYWxzZSAkQ09NTUVOVCB8fCAkQSIsInJld3JpdGUiOiIkQSIsImNvbmZpZyI6IiMgWUFNTCBSdWxlIGlzIG1vcmUgcG93ZXJmdWwhXG4jIGh0dHBzOi8vYXN0LWdyZXAuZ2l0aHViLmlvL2d1aWRlL3J1bGUtY29uZmlnLmh0bWwjcnVsZVxucnVsZTpcbiAgYW55OlxuICAgIC0gcGF0dGVybjogY29uc29sZS5sb2coJEEpXG4gICAgLSBwYXR0ZXJuOiBjb25zb2xlLmRlYnVnKCRBKVxuZml4OlxuICBsb2dnZXIubG9nKCRBKSIsInNvdXJjZSI6ImludCBwcm9kdWN0aW9uKCkge3JldHVybiA0Mjt9XG5pbnQgZG9fbm90X3J1bigpIHsgcmV0dXJuIDU3OyB9XG5cbmF1dG8gYiA9IHRydWU7XG5cbmludCBtYWluICgpIHtcbiAgaWYgKGZhbHNlIC8qIHNvbWUgY29tbWVudCAqLyB8fCAoZmFsc2UgfHwgKGZhbHNlIHx8IChmYWxzZSAgIHx8IGZhbHNlKSkpKSB7XG4gICAgZG9fbm90X3J1bigpO1xuICB9IGVsc2Uge1xuICAgIHByb2R1Y3Rpb24oKTtcbiAgfVxuXG4gIGlmICh0cnVlICYmIChmYWxzZSB8fCB0cnVlKSB8fCBiKSB7XG4gICAgcHJvZHVjdGlvbigpO1xuICB9XG4gIHByb2R1Y3Rpb24oKTtcblxufSJ9)

# 💻 Code

Code:

```
int production() {return 42;}
int do_not_run() { return 57; }

auto b = true;

int main () {
  if (false /* some comment */ || (false || (false || (false   || false)))) {
    do_not_run();
  } else {
    production();
  }

  if (true && (false || true) || b) {
    production();
  }
  production();

}
```

Pattern:

```yml
false $COMMENT || $A
```

# 🙁 Actual behavior

This doesn't match `false` with a comment followed by `||`, however it does if I use a metavariable of length 3 or less.

# 🙂 Expected behavior

I would expect this not to depend on the length of the metavariable name.

**Comment by HerringtonDarkholme** [comment]
Hi, this is because the pattern 

```
false $COMMENT || $A

```

has invalid syntax. tree-sitter, the underlying parser library, will try to recover from the invalid input by inserting `ERROR` token.

The error recovery is based on heuristics. So the metavariable length does impact the parsing.


> Pattern code must be valid code that tree-sitter can parse.
 
https://ast-grep.github.io/guide/pattern-syntax.html#pattern-matching

In this case, I would recommend you using YAML rule.

**Comment by Boarders** [comment]
That is really helpful, thank you (and thanks for the excellent project!)
