### ISSUE TITLE
[bug] Please bump tree-sitter-swift to 0.4.3 to unbreak build

### ISSUE THREAD

**Issue by grembo** [ast-grep/ast-grep#996]
The release of tree-sitter 0.22 broke the build, which should be fixed in tree-sitter-swift 0.4.3.

See https://github.com/alex-pinkus/tree-sitter-swift/issues/386 for details.

**Comment by HerringtonDarkholme** [comment]
How are you installing ast-grep? the cargo.lock should resolve the correct tree-sitter-switft version.

**Comment by HerringtonDarkholme** [comment]
`cargo install` ignores lock unless using `--locked`
https://github.com/rust-lang/cargo/issues/7169

**Comment by grembo** [comment]
@HerringtonDarkholme You're right (I didn't test after 0.4.3 landed), sorry for the noise.
